version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - /server-rs
      - /server-rs/tools/graphql-gen
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
