// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"tallyo/internal/money"
	"time"
)

// Wealth-owned property details exposed on account records.
type AccountWealthProperty interface {
	IsAccountWealthProperty()
}

// Discriminated union of type-specific asset details.
// The `assetType` field on the parent `Asset` determines which variant is returned,
// or null when the asset has no side-table (e.g. CURRENCY).
type AssetDetails interface {
	IsAssetDetails()
}

// A Plaid item or other data provider.
type ConnectionProvider interface {
	IsConnectionProvider()
}

type Node interface {
	IsNode()
	GetID() GlobalID
}

type Account struct {
	ID GlobalID `json:"id"`
	// The data provider connection for this account. Null for manual accounts.
	Connection *Connection `json:"connection,omitempty"`
	Owner      *Owner      `json:"owner"`
	Name       string      `json:"name"`
	Type       AccountType `json:"type"`
	Subtype    *string     `json:"subtype,omitempty"`
	// Last 4 digits of the account number. Null for manually created accounts.
	Mask *string `json:"mask,omitempty"`
	// Free-form documentation notes visible only in account details.
	Notes  *string `json:"notes,omitempty"`
	Closed bool    `json:"closed"`
	Hidden bool    `json:"hidden"`
	// True when the provider could not infer the account type and defaulted it.
	//   Cleared when a user sets or confirms the type via updateAccount.
	NeedsReview bool `json:"needsReview"`
	// True for accounts created manually (not synced from Plaid).
	Manual bool `json:"manual"`
	// True when the account type is managed by its backing link and cannot be edited directly.
	TypeLocked   bool       `json:"typeLocked"`
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	// Most recent account snapshot, including the per-asset holdings captured for that local day.
	LatestSnapshot *AccountSnapshot `json:"latestSnapshot,omitempty"`
	// Wealth-owned property details for PROPERTY accounts backed by linked assets.
	AccountWealthProperty AccountWealthProperty `json:"accountWealthProperty,omitempty"`
}

func (Account) IsNode()              {}
func (this Account) GetID() GlobalID { return this.ID }

type AccountList struct {
	Items []*Account `json:"items"`
}

// A single stored balance snapshot for one account on one local day, with per-asset holdings.
type AccountSnapshot struct {
	ID GlobalID `json:"id"`
	// Owning account ID.
	AccountID GlobalID `json:"accountId"`
	// Local-timezone day this snapshot represents (YYYY-MM-DD).
	Date Date `json:"date"`
	// Stored total balance in USD for countable holdings in the snapshot.
	BalanceUsd money.Cents `json:"balanceUSD"`
	// Sign-aware account value for this snapshot: assets are positive, liabilities negative.
	NetContributionUsd money.Cents `json:"netContributionUSD"`
	// Per-asset breakdown, including the CASH (USD) line.
	Holdings []*Holding `json:"holdings,omitempty"`
	// True when this snapshot is currently flagged by spike protection.
	Flagged bool `json:"flagged"`
}

func (AccountSnapshot) IsNode()              {}
func (this AccountSnapshot) GetID() GlobalID { return this.ID }

type AccountSnapshotConnection struct {
	Edges      []*AccountSnapshotEdge `json:"edges"`
	PageInfo   *PageInfo              `json:"pageInfo"`
	TotalCount int32                  `json:"totalCount"`
}

type AccountSnapshotEdge struct {
	Node   *AccountSnapshot `json:"node"`
	Cursor string           `json:"cursor"`
}

type AccountSnapshotInput struct {
	// Resolve a specific snapshot row directly by its ID.
	SnapshotID *GlobalID `json:"snapshotId,omitempty"`
	// Resolve by account. With date: latest snapshot on that local day. Without date: most recent snapshot.
	AccountID *GlobalID `json:"accountId,omitempty"`
	// Local-timezone day (YYYY-MM-DD). Optional; omit for most recent.
	Date *Date `json:"date,omitempty"`
}

type AccountSnapshotsInput struct {
	AccountID GlobalID `json:"accountId"`
	First     *int32   `json:"first,omitempty"`
	After     *string  `json:"after,omitempty"`
}

type AddUserInput struct {
	Email string `json:"email"`
	Role  *Role  `json:"role,omitempty"`
}

type AddUserPayload struct {
	User *User `json:"user"`
}

type Address struct {
	Street   *string `json:"street,omitempty"`
	City     *string `json:"city,omitempty"`
	State    *string `json:"state,omitempty"`
	Zip      *string `json:"zip,omitempty"`
	HomeType *string `json:"homeType,omitempty"`
}

// A single holding's contribution to an analysis slice.
type AnalysisHolding struct {
	Asset *Asset `json:"asset"`
	// USD value this holding contributes to the parent slice.
	ValueUsd money.Cents `json:"valueUSD"`
	// Percentage of the parent slice's total value (0-100).
	Percent float64 `json:"percent"`
}

type AnalysisInput struct {
	View                AnalysisView `json:"view"`
	OwnerIds            []*GlobalID  `json:"ownerIds,omitempty"`
	AccountSubtypes     []string     `json:"accountSubtypes,omitempty"`
	AccountIds          []*GlobalID  `json:"accountIds,omitempty"`
	IncludeUnclassified *bool        `json:"includeUnclassified,omitempty"`
}

// Result of the analysis query: a full breakdown for a single view.
type AnalysisReport struct {
	View AnalysisView `json:"view"`
	// Total USD value of all analyzed PUBLIC holdings before slicing.
	TotalValueUsd money.Cents `json:"totalValueUSD"`
	// Breakdown segments, sorted descending by valueUSD.
	Slices []*AnalysisSlice `json:"slices"`
}

// One segment of an analysis breakdown, e.g. 'US Equity' or 'Technology'.
type AnalysisSlice struct {
	// Human-readable label for this segment.
	Label string `json:"label"`
	// Total USD value attributed to this segment.
	ValueUsd money.Cents `json:"valueUSD"`
	// Percentage of the total analyzed portfolio (0-100).
	Percent float64 `json:"percent"`
	// Individual holdings that contribute to this segment.
	Holdings []*AnalysisHolding `json:"holdings"`
}

type AssetAdapterSource struct {
	SourceAdapter AssetSourceAdapter `json:"sourceAdapter"`
	SourceID      string             `json:"sourceId"`
}

type AssetList struct {
	Items []*Asset `json:"items"`
}

// Live price quote for a single ticker.
type AssetQuote struct {
	Ticker   string    `json:"ticker"`
	PriceUsd float64   `json:"priceUSD"`
	AsOf     time.Time `json:"asOf"`
}

// Computed current-position projection for one asset. Not persisted; no Node ID.
type AssetSnapshot struct {
	// Latest contributing account snapshot date; older accounts carry forward.
	AsOfDate Date `json:"asOfDate"`
	// Null when any contributing provider supplies valuation without quantity.
	TotalHeldQuantity *float64    `json:"totalHeldQuantity,omitempty"`
	TotalHeldValueUsd money.Cents `json:"totalHeldValueUSD"`
	Holdings          []*Holding  `json:"holdings,omitempty"`
}

type AssetsInput struct {
	AssetType         *AssetType          `json:"assetType,omitempty"`
	PriceConnectivity *ConnectivityStatus `json:"priceConnectivity,omitempty"`
	IncludeHistorical *bool               `json:"includeHistorical,omitempty"`
	// Full-text query matched against asset identifier and name; results are ranked by relevance.
	Search                 *string             `json:"search,omitempty"`
	InvestmentConnectivity *ConnectivityStatus `json:"investmentConnectivity,omitempty"`
}

type AuthorizationConfiguration struct {
	MasterPassword        *string  `json:"masterPassword,omitempty"`
	DisableAllAuth        bool     `json:"disableAllAuth"`
	OauthIssuerURL        string   `json:"oauthIssuerUrl"`
	FrontendRedirectUris  []string `json:"frontendRedirectUris"`
	AccessTokenLifetime   string   `json:"accessTokenLifetime"`
	RefreshTokenLifetime  string   `json:"refreshTokenLifetime"`
	DevCorsAllowedOrigins []string `json:"devCorsAllowedOrigins,omitempty"`
}

type AuthorizationConfigurationInput struct {
	MasterPassword        *string  `json:"masterPassword,omitempty"`
	DisableAllAuth        bool     `json:"disableAllAuth"`
	OauthIssuerURL        string   `json:"oauthIssuerUrl"`
	FrontendRedirectUris  []string `json:"frontendRedirectUris"`
	AccessTokenLifetime   string   `json:"accessTokenLifetime"`
	RefreshTokenLifetime  string   `json:"refreshTokenLifetime"`
	DevCorsAllowedOrigins []string `json:"devCorsAllowedOrigins,omitempty"`
}

// A flagged balance snapshot review for a single account.
type BalanceSnapshotReview struct {
	ID                     GlobalID    `json:"id"`
	Account                *Account    `json:"account"`
	FirstFlaggedDate       Date        `json:"firstFlaggedDate"`
	LatestFlaggedDate      Date        `json:"latestFlaggedDate"`
	FlaggedSnapshotCount   int32       `json:"flaggedSnapshotCount"`
	ProviderBalanceUsd     money.Cents `json:"providerBalanceUSD"`
	CarryForwardBalanceUsd money.Cents `json:"carryForwardBalanceUSD"`
	FlagReason             *string     `json:"flagReason,omitempty"`
	CreatedAt              time.Time   `json:"createdAt"`
	UpdatedAt              time.Time   `json:"updatedAt"`
}

func (BalanceSnapshotReview) IsNode()              {}
func (this BalanceSnapshotReview) GetID() GlobalID { return this.ID }

type BalanceSnapshotReviewList struct {
	Items []*BalanceSnapshotReview `json:"items"`
}

// A single per-category budget target for a given month.
type Budget struct {
	ID       GlobalID    `json:"id"`
	Month    string      `json:"month"`
	Category *Category   `json:"category"`
	Amount   money.Cents `json:"amount"`
}

func (Budget) IsNode()              {}
func (this Budget) GetID() GlobalID { return this.ID }

// A budget line for one category — budgeted vs actual for the month.
type BudgetLine struct {
	// The budget row ID; null when only actuals exist (no budget target set).
	ID        *GlobalID   `json:"id,omitempty"`
	Category  *Category   `json:"category"`
	Budgeted  money.Cents `json:"budgeted"`
	Actual    money.Cents `json:"actual"`
	Remaining money.Cents `json:"remaining"`
}

// Budget report for a single month with section-level rollups.
type BudgetReport struct {
	Month             string           `json:"month"`
	ExpensesBudgeted  money.Cents      `json:"expensesBudgeted"`
	ExpensesActual    money.Cents      `json:"expensesActual"`
	IncomeBudgeted    money.Cents      `json:"incomeBudgeted"`
	IncomeActual      money.Cents      `json:"incomeActual"`
	RemainingBudgeted money.Cents      `json:"remainingBudgeted"`
	RemainingActual   money.Cents      `json:"remainingActual"`
	Sections          []*BudgetSection `json:"sections"`
}

// Budget report history, ordered by month descending.
type BudgetReportHistory struct {
	Items []*BudgetReport `json:"items"`
}

type BudgetReportHistoryInput struct {
	// Start month in YYYY-MM format, inclusive.
	StartMonth *string `json:"startMonth,omitempty"`
	// End month in YYYY-MM format, exclusive.
	EndMonth *string `json:"endMonth,omitempty"`
}

type BudgetReportInput struct {
	// Month in YYYY-MM format.
	Month string `json:"month"`
}

// A budget section grouped by category group.
type BudgetSection struct {
	Label     string         `json:"label"`
	Group     *CategoryGroup `json:"group"`
	Budgeted  money.Cents    `json:"budgeted"`
	Actual    money.Cents    `json:"actual"`
	Remaining money.Cents    `json:"remaining"`
	Lines     []*BudgetLine  `json:"lines"`
}

type BulkDeleteTransactionsInput struct {
	// Exactly one of transactionIds or filter must be supplied.
	TransactionIds []*GlobalID         `json:"transactionIds,omitempty"`
	Filter         *TransactionsFilter `json:"filter,omitempty"`
}

type BulkDeleteTransactionsPayload struct {
	DeletedCount int32 `json:"deletedCount"`
}

type BulkUpdateTransactionsInput struct {
	// Exactly one of transactionIds or filter must be supplied.
	TransactionIds []*GlobalID         `json:"transactionIds,omitempty"`
	Filter         *TransactionsFilter `json:"filter,omitempty"`
	Updates        *TransactionUpdates `json:"updates"`
}

type BulkUpdateTransactionsPayload struct {
	UpdatedCount int32          `json:"updatedCount"`
	Transactions []*Transaction `json:"transactions"`
}

// Spending or income total for a single category within a cash flow period.
type CashFlowBreakdown struct {
	Category         *Category   `json:"category"`
	Total            money.Cents `json:"total"`
	TransactionCount int32       `json:"transactionCount"`
	PercentOfTotal   float64     `json:"percentOfTotal"`
}

// Cash flow data for a single time bucket (month, quarter, or year).
type CashFlowPeriod struct {
	PeriodLabel string           `json:"periodLabel"`
	PeriodStart Date             `json:"periodStart"`
	PeriodEnd   Date             `json:"periodEnd"`
	Summary     *CashFlowSummary `json:"summary"`
	// Income categories with their totals, sorted by total descending.
	IncomeByCategory []*CashFlowBreakdown `json:"incomeByCategory"`
	// Expense categories with their totals, sorted by total descending.
	ExpensesByCategory []*CashFlowBreakdown `json:"expensesByCategory"`
}

// Envelope type for the cashFlow query.
type CashFlowReport struct {
	Periods []*CashFlowPeriod `json:"periods"`
}

// Aggregate income, expenses, savings, and savings rate for a period.
type CashFlowSummary struct {
	// Total income (sum of transactions in income categories).
	Income money.Cents `json:"income"`
	// Total expenses (sum of transactions in non-income, non-transfer categories).
	Expenses money.Cents `json:"expenses"`
	Savings  money.Cents `json:"savings"`
	// Savings / income as a percentage (0–100). 0 if income is zero.
	SavingsRate float64 `json:"savingsRate"`
}

type Category struct {
	ID             GlobalID     `json:"id"`
	Name           string       `json:"name"`
	Emoji          string       `json:"emoji"`
	GroupName      string       `json:"groupName"`
	GroupEmoji     string       `json:"groupEmoji"`
	Kind           CategoryKind `json:"kind"`
	SortOrder      int32        `json:"sortOrder"`
	PlaidPFC2Codes []string     `json:"plaidPFC2Codes"`
}

func (Category) IsNode()              {}
func (this Category) GetID() GlobalID { return this.ID }

type CategoryGroup struct {
	ID         GlobalID     `json:"id"`
	Name       string       `json:"name"`
	Emoji      string       `json:"emoji"`
	Kind       CategoryKind `json:"kind"`
	Categories []*Category  `json:"categories"`
}

func (CategoryGroup) IsNode()              {}
func (this CategoryGroup) GetID() GlobalID { return this.ID }

type CategoryGroupList struct {
	Items []*CategoryGroup `json:"items"`
}

type CategoryList struct {
	Items []*Category `json:"items"`
}

// Aggregate spending stats for a single category.
type CategorySpendingAggregate struct {
	Category         *Category                 `json:"category"`
	TotalAmount      money.Cents               `json:"totalAmount"`
	TransactionCount int32                     `json:"transactionCount"`
	PercentOfTotal   float64                   `json:"percentOfTotal"`
	Periods          []*CategorySpendingPeriod `json:"periods"`
}

// Aggregate spending stats for a category within a single time bucket.
type CategorySpendingPeriod struct {
	PeriodLabel      string      `json:"periodLabel"`
	PeriodStart      Date        `json:"periodStart"`
	PeriodEnd        Date        `json:"periodEnd"`
	TotalAmount      money.Cents `json:"totalAmount"`
	TransactionCount int32       `json:"transactionCount"`
	PercentOfTotal   float64     `json:"percentOfTotal"`
}

type ChangeAccountSnapshotInput struct {
	// Snapshot ID returned by accountSnapshot(); updated in place.
	SnapshotID GlobalID `json:"snapshotId"`
	// Full replacement holdings set. Include 0-quantity lines to zero an asset.
	Holdings []*SnapshotHoldingInput `json:"holdings"`
}

type ChangeAccountSnapshotPayload struct {
	Snapshot *AccountSnapshot `json:"snapshot"`
	// The refreshed account, so clients can update net worth and holdings views.
	Account *Account `json:"account"`
}

type ClassifierBreakdown struct {
	Classifier      AssetClassifier  `json:"classifier"`
	Label           string           `json:"label"`
	ValueUsd        money.Cents      `json:"valueUSD"`
	PercentOfAssets float64          `json:"percentOfAssets"`
	AssetCount      int32            `json:"assetCount"`
	Holdings        []*HoldingRollup `json:"holdings"`
}

// One data point in the historical per-classifier asset series.
type ClassifierHistoryPoint struct {
	Date       Date            `json:"date"`
	Classifier AssetClassifier `json:"classifier"`
	// Human-readable label, e.g. Public Assets.
	Label    string      `json:"label"`
	ValueUsd money.Cents `json:"valueUSD"`
}

type CompleteLinkUpdatePayload struct {
	Item *PlaidItem `json:"item"`
}

// Resolved server configuration. Secret values are obfuscated.
type Configuration struct {
	ConfigFilePath    *string                         `json:"configFilePath,omitempty"`
	DbPath            string                          `json:"dbPath"`
	Port              string                          `json:"port"`
	SyncOff           bool                            `json:"syncOff"`
	Locale            *Locale                         `json:"locale"`
	General           *GeneralConfiguration           `json:"general"`
	Authorization     *AuthorizationConfiguration     `json:"authorization"`
	LlmCategorization *LlmCategorizationConfiguration `json:"llmCategorization"`
	GoogleAuthn       *GoogleAuthnConfiguration       `json:"googleAuthn"`
	PassKeyAuthn      *PassKeyAuthnConfiguration      `json:"passKeyAuthn"`
	EmailCodeAuthn    *EmailCodeAuthnConfiguration    `json:"emailCodeAuthn"`
	Mcp               *McpConfiguration               `json:"mcp"`
	Security          *SecurityConfiguration          `json:"security"`
}

type ConnectionList struct {
	Items []*Connection `json:"items"`
}

type ConnectionsInput struct {
	IncludeInactive *bool `json:"includeInactive,omitempty"`
}

type CopyBudgetsInput struct {
	FromMonth string `json:"fromMonth"`
	ToMonth   string `json:"toMonth"`
}

type CopyBudgetsPayload struct {
	CopiedCount int32 `json:"copiedCount"`
}

type CreateAssetInput struct {
	AssetType  AssetType       `json:"assetType"`
	Identifier string          `json:"identifier"`
	Name       *string         `json:"name,omitempty"`
	Classifier AssetClassifier `json:"classifier"`
	// Fixed USD price per unit.
	ForcedUsdPrice     *float64                  `json:"forcedUsdPrice,omitempty"`
	TrackingTicker     *string                   `json:"trackingTicker,omitempty"`
	TrackingMultiplier *float64                  `json:"trackingMultiplier,omitempty"`
	Security           *CreateSecurityAssetInput `json:"security,omitempty"`
}

type CreateAssetPayload struct {
	Asset *Asset `json:"asset"`
}

type CreateCategoryGroupInput struct {
	Name  string       `json:"name"`
	Emoji string       `json:"emoji"`
	Kind  CategoryKind `json:"kind"`
}

type CreateCategoryGroupPayload struct {
	Group *CategoryGroup `json:"group"`
}

type CreateCategoryInput struct {
	Name    string   `json:"name"`
	Emoji   string   `json:"emoji"`
	GroupID GlobalID `json:"groupId"`
}

type CreateCategoryPayload struct {
	Category *Category `json:"category"`
}

type CreateInviteLinkInput struct {
	UserID GlobalID `json:"userId"`
}

type CreateInviteLinkPayload struct {
	URL       string    `json:"url"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type CreateLinkTokenInput struct {
	CredentialID int32    `json:"credentialId"`
	OwnerID      GlobalID `json:"ownerId"`
}

type CreateLinkTokenPayload struct {
	LinkToken  string    `json:"linkToken"`
	Expiration time.Time `json:"expiration"`
}

type CreateManualAccountInput struct {
	// The Connection (provider) this account is grouped under. Null for truly manual accounts.
	ConnectionID *GlobalID   `json:"connectionId,omitempty"`
	Name         string      `json:"name"`
	OwnerID      GlobalID    `json:"ownerId"`
	Type         AccountType `json:"type"`
	Notes        *string     `json:"notes,omitempty"`
	Closed       *bool       `json:"closed,omitempty"`
	Hidden       *bool       `json:"hidden,omitempty"`
}

type CreateManualAccountPayload struct {
	Account *Account `json:"account"`
}

type CreateOwnerInput struct {
	Name string `json:"name"`
}

type CreatePlaidCredentialInput struct {
	ClientID    string           `json:"clientId"`
	Secret      string           `json:"secret"`
	Environment PlaidEnvironment `json:"environment"`
	Label       *string          `json:"label,omitempty"`
}

type CreatePlaidCredentialPayload struct {
	Credential *PlaidCredential `json:"credential"`
}

type CreateRuleInput struct {
	MerchantPattern    *string             `json:"merchantPattern,omitempty"`
	OriginalPattern    *string             `json:"originalPattern,omitempty"`
	Changes            *TransactionUpdates `json:"changes"`
	AccountIds         []*GlobalID         `json:"accountIds,omitempty"`
	AmountMin          *money.Cents        `json:"amountMin,omitempty"`
	AmountMax          *money.Cents        `json:"amountMax,omitempty"`
	Priority           *int32              `json:"priority,omitempty"`
	ApplyRetroactively *bool               `json:"applyRetroactively,omitempty"`
}

type CreateRulePayload struct {
	Rule                 *Rule `json:"rule"`
	RetroactivelyUpdated int32 `json:"retroactivelyUpdated"`
}

type CreateSecurityAssetInput struct {
	Cusip *string `json:"cusip,omitempty"`
	Isin  *string `json:"isin,omitempty"`
}

type CreateSimpleFinAccessTokenInput struct {
	// The base64-encoded one-time Setup Token from SimpleFIN Bridge.
	SetupToken string   `json:"setupToken"`
	OwnerID    GlobalID `json:"ownerId"`
	Label      *string  `json:"label,omitempty"`
}

type CreateSimpleFinAccessTokenPayload struct {
	AccessToken *SimpleFinAccessToken  `json:"accessToken"`
	Connections []*SimpleFinConnection `json:"connections"`
	Accounts    []*Account             `json:"accounts"`
}

type CreateTagInput struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type CreateTagPayload struct {
	Tag *Tag `json:"tag"`
}

type CreateTransactionInput struct {
	AccountID    GlobalID    `json:"accountId"`
	Date         Date        `json:"date"`
	Amount       money.Cents `json:"amount"`
	MerchantName *string     `json:"merchantName,omitempty"`
	OriginalName *string     `json:"originalName,omitempty"`
	CategoryID   *GlobalID   `json:"categoryId,omitempty"`
	Notes        *string     `json:"notes,omitempty"`
	IsRecurring  *bool       `json:"isRecurring,omitempty"`
	IsHidden     *bool       `json:"isHidden,omitempty"`
}

type CreateTransactionPayload struct {
	Transaction *Transaction `json:"transaction"`
}

type DateTimeRange struct {
	// Inclusive lower bound as an ISO 8601 timestamp.
	From *time.Time `json:"from,omitempty"`
	// Exclusive upper bound as an ISO 8601 timestamp.
	To *time.Time `json:"to,omitempty"`
}

type DeleteBudgetInput struct {
	ID GlobalID `json:"id"`
}

type DeleteBudgetPayload struct {
	Success bool `json:"success"`
}

type DeleteCategoryGroupPayload struct {
	Success bool `json:"success"`
}

type DeleteCategoryPayload struct {
	Success bool `json:"success"`
}

type DeleteConnectionInput struct {
	ConnectionID GlobalID `json:"connectionId"`
}

type DeleteConnectionPayload struct {
	Success bool `json:"success"`
}

type DeletePlaidCredentialInput struct {
	ID int32 `json:"id"`
}

type DeletePlaidCredentialPayload struct {
	Success bool `json:"success"`
}

type DeleteRulePayload struct {
	Success bool `json:"success"`
}

type DeleteTagPayload struct {
	Success bool `json:"success"`
}

type DeleteTransactionPayload struct {
	Success bool `json:"success"`
}

type EVMChain struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type EVMChainList struct {
	Items []*EVMChain `json:"items"`
}

// An EVM wallet. Balances are synced across chains via an external provider.
type EVMWallet struct {
	Address  string   `json:"address"`
	ChainIds []string `json:"chainIds"`
}

func (EVMWallet) IsConnectionProvider() {}

type EmailCodeAuthnConfiguration struct {
	Enabled      bool    `json:"enabled"`
	SMTPHost     *string `json:"smtpHost,omitempty"`
	SMTPPort     string  `json:"smtpPort"`
	SMTPFrom     *string `json:"smtpFrom,omitempty"`
	SMTPUsername *string `json:"smtpUsername,omitempty"`
	SMTPPassword *string `json:"smtpPassword,omitempty"`
}

type EmailCodeAuthnConfigurationInput struct {
	Enabled      bool    `json:"enabled"`
	SMTPHost     *string `json:"smtpHost,omitempty"`
	SMTPPort     string  `json:"smtpPort"`
	SMTPFrom     *string `json:"smtpFrom,omitempty"`
	SMTPUsername *string `json:"smtpUsername,omitempty"`
	SMTPPassword *string `json:"smtpPassword,omitempty"`
}

type ExchangePublicTokenInput struct {
	PublicToken     string   `json:"publicToken"`
	CredentialID    int32    `json:"credentialId"`
	OwnerID         GlobalID `json:"ownerId"`
	InstitutionID   *string  `json:"institutionId,omitempty"`
	InstitutionName *string  `json:"institutionName,omitempty"`
}

type ExchangePublicTokenPayload struct {
	Item *PlaidItem `json:"item"`
	// Accounts discovered during the initial item sync.
	Accounts []*Account `json:"accounts"`
}

type GeneralConfiguration struct {
	DisableTransactionTracking bool `json:"disableTransactionTracking"`
	DisableWealthTracking      bool `json:"disableWealthTracking"`
	HideOwners                 bool `json:"hideOwners"`
}

type GeneralConfigurationInput struct {
	DisableTransactionTracking bool `json:"disableTransactionTracking"`
	DisableWealthTracking      bool `json:"disableWealthTracking"`
	HideOwners                 bool `json:"hideOwners"`
}

type GoogleAuthnConfiguration struct {
	Enabled            bool    `json:"enabled"`
	GoogleClientID     *string `json:"googleClientId,omitempty"`
	GoogleClientSecret *string `json:"googleClientSecret,omitempty"`
}

type GoogleAuthnConfigurationInput struct {
	Enabled            bool    `json:"enabled"`
	GoogleClientID     *string `json:"googleClientId,omitempty"`
	GoogleClientSecret *string `json:"googleClientSecret,omitempty"`
}

type HistoricalNetWorthInput struct {
	Range       NetWorthRange  `json:"range"`
	Granularity *Granularity   `json:"granularity,omitempty"`
	Filters     *NetWorthInput `json:"filters,omitempty"`
}

// Historical net worth and per-classifier breakdown over a date range.
type HistoricalNetWorthReport struct {
	// Net worth time series over the requested range.
	Series []*NetWorthPoint `json:"series"`
	// Per-classifier asset value series over the requested range.
	ClassifierSeries []*ClassifierHistoryPoint `json:"classifierSeries"`
	// Per-category liability value series over the requested range.
	LiabilitySeries []*LiabilityHistoryPoint `json:"liabilitySeries"`
}

type Holding struct {
	AssetID   GlobalID `json:"assetId"`
	Asset     *Asset   `json:"asset"`
	AccountID GlobalID `json:"accountId"`
	Account   *Account `json:"account"`
	// May be null when a provider supplies valuation without quantity.
	Quantity *float64    `json:"quantity,omitempty"`
	ValueUsd money.Cents `json:"valueUSD"`
	// True for user-managed snapshot holdings.
	Manual bool `json:"manual"`
}

type HoldingRollup struct {
	Asset *Asset `json:"asset"`
	// Null when any contributing provider supplies valuation without quantity.
	TotalQuantity       *float64    `json:"totalQuantity,omitempty"`
	ValueUsd            money.Cents `json:"valueUSD"`
	PercentOfClassifier float64     `json:"percentOfClassifier"`
	Holdings            []*Holding  `json:"holdings,omitempty"`
}

type LiabilityBreakdown struct {
	Category             LiabilityCategory `json:"category"`
	Label                string            `json:"label"`
	ValueUsd             money.Cents       `json:"valueUSD"`
	PercentOfLiabilities float64           `json:"percentOfLiabilities"`
	AccountCount         int32             `json:"accountCount"`
	Accounts             []*Account        `json:"accounts"`
}

// One data point in the historical per-category liability series.
type LiabilityHistoryPoint struct {
	Date     Date              `json:"date"`
	Category LiabilityCategory `json:"category"`
	// Human-readable label, e.g. Credit Card.
	Label string `json:"label"`
	// Negative USD value representing the liability amount.
	ValueUsd money.Cents `json:"valueUSD"`
}

type LinkEVMWalletInput struct {
	// EVM address (0x followed by 40 hex characters).
	Address  string   `json:"address"`
	ChainIds []string `json:"chainIds"`
	OwnerID  GlobalID `json:"ownerId"`
	// Human-readable label; defaults to a truncated version of the address.
	Label *string `json:"label,omitempty"`
}

type LinkEVMWalletPayload struct {
	Connection *Connection `json:"connection"`
	Account    *Account    `json:"account"`
}

type LinkRealEstateInput struct {
	Street             *string     `json:"street,omitempty"`
	City               *string     `json:"city,omitempty"`
	State              *string     `json:"state,omitempty"`
	Zip                *string     `json:"zip,omitempty"`
	HomeType           *string     `json:"homeType,omitempty"`
	OwnerID            GlobalID    `json:"ownerId"`
	Label              *string     `json:"label,omitempty"`
	ManualValuationUsd money.Cents `json:"manualValuationUSD"`
}

type LinkRealEstatePayload struct {
	Connection   *Connection `json:"connection"`
	Account      *Account    `json:"account"`
	ValuationUsd money.Cents `json:"valuationUSD"`
}

type LlmCategorizationConfiguration struct {
	Enabled  bool        `json:"enabled"`
	Provider LlmProvider `json:"provider"`
	// Providers selectable in this deployment.
	AllowedProviders []LlmProvider                `json:"allowedProviders"`
	Ollama           *OllamaProviderConfiguration `json:"ollama"`
}

type LlmCategorizationConfigurationInput struct {
	Enabled  bool                              `json:"enabled"`
	Provider LlmProvider                       `json:"provider"`
	Ollama   *OllamaProviderConfigurationInput `json:"ollama"`
}

type Locale struct {
	Timezone string `json:"timezone"`
}

type LocaleConfigurationInput struct {
	Timezone string `json:"timezone"`
}

type McpConfiguration struct {
	Enabled bool `json:"enabled"`
	// Hosts allowed as HTTPS redirect URIs for dynamically registered MCP clients.
	DynamicRedirectHosts []string `json:"dynamicRedirectHosts,omitempty"`
}

type McpConfigurationInput struct {
	Enabled              bool     `json:"enabled"`
	DynamicRedirectHosts []string `json:"dynamicRedirectHosts,omitempty"`
}

type MergeAssetInput struct {
	// Identifies the adapter-source row to re-point (currently on the duplicate).
	SourceAdapter AssetSourceAdapter `json:"sourceAdapter"`
	SourceID      string             `json:"sourceId"`
	// The surviving asset that absorbs the duplicate.
	AssetID GlobalID `json:"assetId"`
}

type MergeAssetPayload struct {
	Asset *Asset `json:"asset"`
}

type Mutation struct {
}

type NetWorthInput struct {
	OwnerIds   []*GlobalID `json:"ownerIds,omitempty"`
	AccountIds []*GlobalID `json:"accountIds,omitempty"`
}

type NetWorthPoint struct {
	Date                Date        `json:"date"`
	TotalAssetsUsd      money.Cents `json:"totalAssetsUSD"`
	TotalLiabilitiesUsd money.Cents `json:"totalLiabilitiesUSD"`
	NetWorthUsd         money.Cents `json:"netWorthUSD"`
}

type NetWorthReport struct {
	AsOfDate              *Date                  `json:"asOfDate,omitempty"`
	CurrentNetWorthUsd    money.Cents            `json:"currentNetWorthUSD"`
	CurrentAssetsUsd      money.Cents            `json:"currentAssetsUSD"`
	CurrentLiabilitiesUsd money.Cents            `json:"currentLiabilitiesUSD"`
	ClassifierBreakdown   []*ClassifierBreakdown `json:"classifierBreakdown"`
	LiabilityBreakdown    []*LiabilityBreakdown  `json:"liabilityBreakdown"`
}

type OllamaProviderConfiguration struct {
	URL   *string `json:"url,omitempty"`
	Model string  `json:"model"`
}

type OllamaProviderConfigurationInput struct {
	URL   *string `json:"url,omitempty"`
	Model string  `json:"model"`
}

// A household owner that accounts and connections are attributed to.
type Owner struct {
	ID   GlobalID `json:"id"`
	Name string   `json:"name"`
}

func (Owner) IsNode()              {}
func (this Owner) GetID() GlobalID { return this.ID }

type OwnerList struct {
	Items []*Owner `json:"items"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type PassKeyAuthnConfiguration struct {
	Enabled           bool     `json:"enabled"`
	WebauthnRpID      *string  `json:"webauthnRpId,omitempty"`
	WebauthnRpName    string   `json:"webauthnRpName"`
	WebauthnRpOrigins []string `json:"webauthnRpOrigins,omitempty"`
}

type PassKeyAuthnConfigurationInput struct {
	Enabled           bool     `json:"enabled"`
	WebauthnRpID      *string  `json:"webauthnRpId,omitempty"`
	WebauthnRpName    string   `json:"webauthnRpName"`
	WebauthnRpOrigins []string `json:"webauthnRpOrigins,omitempty"`
}

// A Plaid API credential pair (client_id + secret). Secrets are never exposed
// via the API — only the client_id and metadata are returned.
type PlaidCredential struct {
	ID          int32            `json:"id"`
	ClientID    string           `json:"clientId"`
	Environment PlaidEnvironment `json:"environment"`
	// Human-readable label for credential selection UI (e.g. "Primary", "Overflow").
	Label *string `json:"label,omitempty"`
	// Number of active PlaidItems using this credential.
	ItemCount int32     `json:"itemCount"`
	CreatedAt time.Time `json:"createdAt"`
}

type PlaidCredentialList struct {
	Items []*PlaidCredential `json:"items"`
}

// A linked Plaid connection representing one financial institution. Each item
// holds an access token and sync cursor, and maps to one or more Accounts.
type PlaidItem struct {
	ID         GlobalID         `json:"id"`
	Credential *PlaidCredential `json:"credential"`
	// Plaid institution ID (e.g. "ins_3").
	InstitutionID *string    `json:"institutionId,omitempty"`
	Accounts      []*Account `json:"accounts"`
	LastSyncedAt  *time.Time `json:"lastSyncedAt,omitempty"`
	// Current Plaid Item health state. LINK_UPDATE_REQUIRED means use Link update mode.
	HealthState PlaidItemHealthState `json:"healthState"`
	// Last Plaid error code that changed healthState, if any.
	HealthErrorCode *string `json:"healthErrorCode,omitempty"`
	// Last Plaid error message that changed healthState, if any.
	HealthErrorMessage *string `json:"healthErrorMessage,omitempty"`
	// When the current healthState was last written.
	HealthUpdatedAt     *time.Time `json:"healthUpdatedAt,omitempty"`
	SyncCron            string     `json:"syncCron"`
	RecurringSyncCron   string     `json:"recurringSyncCron"`
	NextSyncAt          *time.Time `json:"nextSyncAt,omitempty"`
	NextRecurringSyncAt *time.Time `json:"nextRecurringSyncAt,omitempty"`
	// Whether this item is actively syncing. False = soft-deleted.
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

func (PlaidItem) IsConnectionProvider() {}

func (PlaidItem) IsNode()              {}
func (this PlaidItem) GetID() GlobalID { return this.ID }

type PlaidItemList struct {
	Items []*PlaidItem `json:"items"`
}

type PlaidItemsInput struct {
	IncludeInactive *bool `json:"includeInactive,omitempty"`
}

type Query struct {
}

// Type-specific details for a real-estate asset.
type RealEstateAssetDetails struct {
	Address *Address `json:"address"`
}

func (RealEstateAssetDetails) IsAssetDetails() {}

func (RealEstateAssetDetails) IsAccountWealthProperty() {}

// A recurring transaction stream sourced from Plaid's /transactions/recurring/get.
type RecurringCharge struct {
	ID              GlobalID            `json:"id"`
	MerchantName    string              `json:"merchantName"`
	EstimatedAmount money.Cents         `json:"estimatedAmount"`
	Interval        *RecurrenceInterval `json:"interval,omitempty"`
	Category        *Category           `json:"category,omitempty"`
	Transactions    []*Transaction      `json:"transactions"`
	FirstDate       Date                `json:"firstDate"`
	LastDate        Date                `json:"lastDate"`
	LastAmount      money.Cents         `json:"lastAmount"`
	IsUserModified  bool                `json:"isUserModified"`
	// Computed from lastDate + interval. Null if interval is unknown.
	NextExpectedDate *Date                 `json:"nextExpectedDate,omitempty"`
	Status           RecurringStreamStatus `json:"status"`
	IsActive         bool                  `json:"isActive"`
}

func (RecurringCharge) IsNode()              {}
func (this RecurringCharge) GetID() GlobalID { return this.ID }

type RecurringChargeList struct {
	Items []*RecurringCharge `json:"items"`
}

type RemoveManualAccountInput struct {
	ID GlobalID `json:"id"`
}

type RemoveManualAccountPayload struct {
	Success bool `json:"success"`
}

type RemoveUserInput struct {
	ID GlobalID `json:"id"`
}

type RemoveUserPayload struct {
	Success bool `json:"success"`
}

type ReorderCategoriesInput struct {
	GroupID GlobalID `json:"groupId"`
	// Full ordered list of category IDs; backend assigns sort_order 1..N.
	CategoryIds []*GlobalID `json:"categoryIds"`
}

type ReorderCategoriesPayload struct {
	Group *CategoryGroup `json:"group"`
}

type ReprocessUncategorizedTransactionsPayload struct {
	StagedCount int32 `json:"stagedCount"`
}

type ResolveBalanceReviewInput struct {
	ID GlobalID `json:"id"`
	// APPROVE_CHANGES keeps carry-forward; USE_PROVIDER restores provider data.
	Action BalanceReviewAction `json:"action"`
}

type ResolveBalanceReviewPayload struct {
	Success bool `json:"success"`
}

type Rule struct {
	ID                GlobalID     `json:"id"`
	MerchantPattern   *string      `json:"merchantPattern,omitempty"`
	OriginalPattern   *string      `json:"originalPattern,omitempty"`
	MerchantName      *string      `json:"merchantName,omitempty"`
	Category          *Category    `json:"category,omitempty"`
	Tags              []*Tag       `json:"tags,omitempty"`
	ShouldHide        *bool        `json:"shouldHide,omitempty"`
	ShouldBeRecurring *bool        `json:"shouldBeRecurring,omitempty"`
	Accounts          []*Account   `json:"accounts,omitempty"`
	AmountMin         *money.Cents `json:"amountMin,omitempty"`
	AmountMax         *money.Cents `json:"amountMax,omitempty"`
	Priority          int32        `json:"priority"`
	CreatedAt         time.Time    `json:"createdAt"`
}

func (Rule) IsNode()              {}
func (this Rule) GetID() GlobalID { return this.ID }

type RuleList struct {
	Items []*Rule `json:"items"`
}

type RulesInput struct {
	MerchantPattern *string      `json:"merchantPattern,omitempty"`
	OriginalPattern *string      `json:"originalPattern,omitempty"`
	AccountIds      []*GlobalID  `json:"accountIds,omitempty"`
	AmountMin       *money.Cents `json:"amountMin,omitempty"`
	AmountMax       *money.Cents `json:"amountMax,omitempty"`
}

type SecurityConfiguration struct {
	TrustedProxyCidrs []string `json:"trustedProxyCidrs"`
}

type SecurityConfigurationInput struct {
	TrustedProxyCidrs []string `json:"trustedProxyCidrs"`
}

type SetBudgetInput struct {
	Month      string      `json:"month"`
	CategoryID GlobalID    `json:"categoryId"`
	Amount     money.Cents `json:"amount"`
}

type SetBudgetPayload struct {
	Budget *Budget `json:"budget"`
}

// A claimed SimpleFIN Access Token. The underlying Access URL is write-only.
type SimpleFinAccessToken struct {
	ID           GlobalID               `json:"id"`
	Label        *string                `json:"label,omitempty"`
	Owner        *Owner                 `json:"owner"`
	Connections  []*SimpleFinConnection `json:"connections"`
	SyncCron     string                 `json:"syncCron"`
	LastSyncedAt *time.Time             `json:"lastSyncedAt,omitempty"`
	NextSyncAt   *time.Time             `json:"nextSyncAt,omitempty"`
	CreatedAt    time.Time              `json:"createdAt"`
}

func (SimpleFinAccessToken) IsNode()              {}
func (this SimpleFinAccessToken) GetID() GlobalID { return this.ID }

type SimpleFinAccessTokenList struct {
	Items []*SimpleFinAccessToken `json:"items"`
}

// A linked SimpleFIN connection (one institution under an Access Token).
type SimpleFinConnection struct {
	ID           GlobalID   `json:"id"`
	OrgDomain    *string    `json:"orgDomain,omitempty"`
	OrgURL       *string    `json:"orgUrl,omitempty"`
	Accounts     []*Account `json:"accounts"`
	LastSyncedAt *time.Time `json:"lastSyncedAt,omitempty"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
}

func (SimpleFinConnection) IsNode()              {}
func (this SimpleFinConnection) GetID() GlobalID { return this.ID }

func (SimpleFinConnection) IsConnectionProvider() {}

type SnapshotHoldingInput struct {
	AssetID GlobalID `json:"assetId"`
	// New quantity. For cash this is the USD amount.
	Quantity *float64 `json:"quantity,omitempty"`
	// New USD value for the holding line.
	ValueUsd money.Cents `json:"valueUSD"`
}

// Aggregate spending stats for a single time bucket.
type SpendingAggregatePeriod struct {
	PeriodLabel      string      `json:"periodLabel"`
	PeriodStart      Date        `json:"periodStart"`
	PeriodEnd        Date        `json:"periodEnd"`
	TotalAmount      money.Cents `json:"totalAmount"`
	TransactionCount int32       `json:"transactionCount"`
}

// Combined spending report for totals, periods, and categories.
type SpendingByCategoryReport struct {
	TotalAmount      money.Cents                  `json:"totalAmount"`
	TransactionCount int32                        `json:"transactionCount"`
	Periods          []*SpendingAggregatePeriod   `json:"periods"`
	Categories       []*CategorySpendingAggregate `json:"categories"`
}

type SpendingFilter struct {
	DatetimeRange *DateTimeRange `json:"datetimeRange"`
	// Optional for spendingByCategory; required by bucketed reports when period granularity matters.
	Granularity *Granularity `json:"granularity,omitempty"`
	CategoryIds []*GlobalID  `json:"categoryIds,omitempty"`
	OwnerIds    []*GlobalID  `json:"ownerIds,omitempty"`
	AccountIds  []*GlobalID  `json:"accountIds,omitempty"`
	IsHidden    *bool        `json:"isHidden,omitempty"`
	TagIds      []*GlobalID  `json:"tagIds,omitempty"`
	Untagged    *bool        `json:"untagged,omitempty"`
}

type Tag struct {
	ID               GlobalID `json:"id"`
	Name             string   `json:"name"`
	Color            string   `json:"color"`
	TransactionCount int32    `json:"transactionCount"`
}

func (Tag) IsNode()              {}
func (this Tag) GetID() GlobalID { return this.ID }

type TagList struct {
	Items []*Tag `json:"items"`
}

type Transaction struct {
	ID      GlobalID    `json:"id"`
	Account *Account    `json:"account"`
	Amount  money.Cents `json:"amount"`
	// ISO 8601 datetime when the transaction was authorized (YYYY-MM-DDTHH:mm:ssZ).
	Datetime time.Time `json:"datetime"`
	// ISO 8601 datetime when the transaction posted/settled (YYYY-MM-DDTHH:mm:ssZ).
	PostedDatetime time.Time `json:"postedDatetime"`
	MerchantName   *string   `json:"merchantName,omitempty"`
	OriginalName   *string   `json:"originalName,omitempty"`
	// Merchant logo URL sourced from Plaid. Null when unavailable.
	LogoURL *string `json:"logoUrl,omitempty"`
	// Always present — uncategorized transactions use the sentinel category (id 0).
	Category      *Category `json:"category"`
	IsRecurring   bool      `json:"isRecurring"`
	IsReviewed    bool      `json:"isReviewed"`
	Notes         *string   `json:"notes,omitempty"`
	PlaidCategory *string   `json:"plaidCategory,omitempty"`
	Pending       bool      `json:"pending"`
	IsHidden      bool      `json:"isHidden"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Tags          []*Tag    `json:"tags"`
}

func (Transaction) IsNode()              {}
func (this Transaction) GetID() GlobalID { return this.ID }

type TransactionConnection struct {
	Edges      []*TransactionEdge `json:"edges"`
	PageInfo   *PageInfo          `json:"pageInfo"`
	TotalCount int32              `json:"totalCount"`
}

type TransactionEdge struct {
	Node   *Transaction `json:"node"`
	Cursor string       `json:"cursor"`
}

type TransactionSort struct {
	Field     TransactionSortField `json:"field"`
	Direction SortDirection        `json:"direction"`
}

type TransactionUpdates struct {
	MerchantName *string     `json:"merchantName,omitempty"`
	Notes        *string     `json:"notes,omitempty"`
	IsRecurring  *bool       `json:"isRecurring,omitempty"`
	IsHidden     *bool       `json:"isHidden,omitempty"`
	CategoryID   *GlobalID   `json:"categoryId,omitempty"`
	TagIds       []*GlobalID `json:"tagIds,omitempty"`
}

type TransactionsFilter struct {
	DatetimeRange    *DateTimeRange `json:"datetimeRange,omitempty"`
	CategoryIds      []*GlobalID    `json:"categoryIds,omitempty"`
	AccountIds       []*GlobalID    `json:"accountIds,omitempty"`
	OwnerIds         []*GlobalID    `json:"ownerIds,omitempty"`
	IsReviewed       *bool          `json:"isReviewed,omitempty"`
	IsRecurring      *bool          `json:"isRecurring,omitempty"`
	IsPending        *bool          `json:"isPending,omitempty"`
	IsHidden         *bool          `json:"isHidden,omitempty"`
	MerchantPrefix   *string        `json:"merchantPrefix,omitempty"`
	OriginalPrefix   *string        `json:"originalPrefix,omitempty"`
	ExcludeTransfers *bool          `json:"excludeTransfers,omitempty"`
	ExcludeIncome    *bool          `json:"excludeIncome,omitempty"`
	AmountMin        *money.Cents   `json:"amountMin,omitempty"`
	AmountMax        *money.Cents   `json:"amountMax,omitempty"`
	ExactAmount      *money.Cents   `json:"exactAmount,omitempty"`
	TagIds           []*GlobalID    `json:"tagIds,omitempty"`
	Untagged         *bool          `json:"untagged,omitempty"`
	// Full-text query matched against merchant name, original name, and notes.
	Search *string `json:"search,omitempty"`
}

type TransactionsInput struct {
	Filter *TransactionsFilter `json:"filter,omitempty"`
	Sort   *TransactionSort    `json:"sort,omitempty"`
	First  *int32              `json:"first,omitempty"`
	After  *string             `json:"after,omitempty"`
	Last   *int32              `json:"last,omitempty"`
	Before *string             `json:"before,omitempty"`
}

type TransactionsStagedForCategorization struct {
	Count int32 `json:"count"`
}

// Aggregate statistics for a filtered set of transactions.
type TransactionsSummary struct {
	TotalCount    int32       `json:"totalCount"`
	TotalAmount   money.Cents `json:"totalAmount"`
	AverageAmount money.Cents `json:"averageAmount"`
	LargestAmount money.Cents `json:"largestAmount"`
	// Date of the earliest matching transaction.
	FirstDate *Date `json:"firstDate,omitempty"`
	// Date of the most recent matching transaction.
	LastDate *Date `json:"lastDate,omitempty"`
}

type UpdateAccountInput struct {
	ID      GlobalID     `json:"id"`
	Name    *string      `json:"name,omitempty"`
	OwnerID *GlobalID    `json:"ownerId,omitempty"`
	Type    *AccountType `json:"type,omitempty"`
	// Plaid account subtype (e.g. "checking", "credit card"). Must be a valid Plaid subtype string.
	Subtype *string `json:"subtype,omitempty"`
	Notes   *string `json:"notes,omitempty"`
	Closed  *bool   `json:"closed,omitempty"`
	Hidden  *bool   `json:"hidden,omitempty"`
}

type UpdateAccountPayload struct {
	Account *Account `json:"account"`
}

type UpdateAssetInput struct {
	ID         GlobalID         `json:"id"`
	Identifier *string          `json:"identifier,omitempty"`
	Name       *string          `json:"name,omitempty"`
	Classifier *AssetClassifier `json:"classifier,omitempty"`
	// When false, clear any forced USD price. When true, forcedUsdPrice must be provided.
	ForcePrice *bool `json:"forcePrice,omitempty"`
	// Fixed USD price per unit.
	ForcedUsdPrice         *float64                  `json:"forcedUsdPrice,omitempty"`
	TrackingTicker         *string                   `json:"trackingTicker,omitempty"`
	TrackingMultiplier     *float64                  `json:"trackingMultiplier,omitempty"`
	PriceConnectivity      *ConnectivityStatus       `json:"priceConnectivity,omitempty"`
	Security               *UpdateSecurityAssetInput `json:"security,omitempty"`
	InvestmentConnectivity *ConnectivityStatus       `json:"investmentConnectivity,omitempty"`
}

type UpdateAssetPayload struct {
	Asset *Asset `json:"asset"`
}

type UpdateCategoryGroupInput struct {
	ID    GlobalID `json:"id"`
	Name  string   `json:"name"`
	Emoji string   `json:"emoji"`
}

type UpdateCategoryGroupPayload struct {
	Group *CategoryGroup `json:"group"`
}

type UpdateCategoryInput struct {
	ID             GlobalID `json:"id"`
	Name           string   `json:"name"`
	Emoji          string   `json:"emoji"`
	GroupID        GlobalID `json:"groupId"`
	PlaidPFC2Codes []string `json:"plaidPFC2Codes,omitempty"`
}

type UpdateCategoryPayload struct {
	Category *Category `json:"category"`
}

type UpdateConfigurationInput struct {
	Locale            *LocaleConfigurationInput            `json:"locale,omitempty"`
	General           *GeneralConfigurationInput           `json:"general,omitempty"`
	Authorization     *AuthorizationConfigurationInput     `json:"authorization,omitempty"`
	LlmCategorization *LlmCategorizationConfigurationInput `json:"llmCategorization,omitempty"`
	GoogleAuthn       *GoogleAuthnConfigurationInput       `json:"googleAuthn,omitempty"`
	PassKeyAuthn      *PassKeyAuthnConfigurationInput      `json:"passKeyAuthn,omitempty"`
	EmailCodeAuthn    *EmailCodeAuthnConfigurationInput    `json:"emailCodeAuthn,omitempty"`
	Mcp               *McpConfigurationInput               `json:"mcp,omitempty"`
	Security          *SecurityConfigurationInput          `json:"security,omitempty"`
	SetupComplete     *bool                                `json:"setupComplete,omitempty"`
}

type UpdateConfigurationPayload struct {
	Configuration *Configuration `json:"configuration"`
}

type UpdateConnectionInput struct {
	ConnectionID      GlobalID `json:"connectionId"`
	IsActive          *bool    `json:"isActive,omitempty"`
	SyncCron          *string  `json:"syncCron,omitempty"`
	RecurringSyncCron *string  `json:"recurringSyncCron,omitempty"`
	ChainIds          []string `json:"chainIds,omitempty"`
}

type UpdateConnectionPayload struct {
	Connection *Connection `json:"connection"`
}

type UpdatePlaidCredentialInput struct {
	ID          int32            `json:"id"`
	Secret      string           `json:"secret"`
	Environment PlaidEnvironment `json:"environment"`
}

type UpdatePlaidCredentialPayload struct {
	Credential *PlaidCredential `json:"credential"`
}

type UpdateRealEstateInput struct {
	ConnectionID GlobalID     `json:"connectionId"`
	Name         *string      `json:"name,omitempty"`
	Street       *string      `json:"street,omitempty"`
	City         *string      `json:"city,omitempty"`
	State        *string      `json:"state,omitempty"`
	Zip          *string      `json:"zip,omitempty"`
	HomeType     *string      `json:"homeType,omitempty"`
	ValuationUsd *money.Cents `json:"valuationUSD,omitempty"`
}

type UpdateRealEstatePayload struct {
	Account *Account `json:"account"`
}

type UpdateRuleInput struct {
	ID                 GlobalID            `json:"id"`
	MerchantPattern    *string             `json:"merchantPattern,omitempty"`
	OriginalPattern    *string             `json:"originalPattern,omitempty"`
	Changes            *TransactionUpdates `json:"changes"`
	AccountIds         []*GlobalID         `json:"accountIds,omitempty"`
	AmountMin          *money.Cents        `json:"amountMin,omitempty"`
	AmountMax          *money.Cents        `json:"amountMax,omitempty"`
	Priority           *int32              `json:"priority,omitempty"`
	ApplyRetroactively *bool               `json:"applyRetroactively,omitempty"`
}

type UpdateRulePayload struct {
	Rule                 *Rule `json:"rule"`
	RetroactivelyUpdated int32 `json:"retroactivelyUpdated"`
}

type UpdateSecurityAssetInput struct {
	Cusip *string `json:"cusip,omitempty"`
	Isin  *string `json:"isin,omitempty"`
}

type UpdateTagInput struct {
	ID    GlobalID `json:"id"`
	Name  string   `json:"name"`
	Color string   `json:"color"`
}

type UpdateTagPayload struct {
	Tag *Tag `json:"tag"`
}

type UpdateTransactionInput struct {
	ID      GlobalID            `json:"id"`
	Updates *TransactionUpdates `json:"updates"`
}

type UpdateTransactionPayload struct {
	Transaction *Transaction `json:"transaction"`
}

type UpdateUserInput struct {
	ID   GlobalID `json:"id"`
	Role Role     `json:"role"`
}

type UpdateUserPayload struct {
	User *User `json:"user"`
}

// A user authorized to access the dashboard.
type User struct {
	ID        GlobalID  `json:"id"`
	Email     string    `json:"email"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"createdAt"`
}

func (User) IsNode()              {}
func (this User) GetID() GlobalID { return this.ID }

type UserList struct {
	Items []*User `json:"items"`
}

type AccountType string

const (
	AccountTypeDepository   AccountType = "DEPOSITORY"
	AccountTypeCredit       AccountType = "CREDIT"
	AccountTypeLoan         AccountType = "LOAN"
	AccountTypeInvestment   AccountType = "INVESTMENT"
	AccountTypeOther        AccountType = "OTHER"
	AccountTypeProperty     AccountType = "PROPERTY"
	AccountTypeCryptoWallet AccountType = "CRYPTO_WALLET"
)

var AllAccountType = []AccountType{
	AccountTypeDepository,
	AccountTypeCredit,
	AccountTypeLoan,
	AccountTypeInvestment,
	AccountTypeOther,
	AccountTypeProperty,
	AccountTypeCryptoWallet,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeDepository, AccountTypeCredit, AccountTypeLoan, AccountTypeInvestment, AccountTypeOther, AccountTypeProperty, AccountTypeCryptoWallet:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AnalysisView string

const (
	AnalysisViewComposition         AnalysisView = "COMPOSITION"
	AnalysisViewMorningstarCategory AnalysisView = "MORNINGSTAR_CATEGORY"
	AnalysisViewMorningstarGroup    AnalysisView = "MORNINGSTAR_GROUP"
	AnalysisViewSectors             AnalysisView = "SECTORS"
)

var AllAnalysisView = []AnalysisView{
	AnalysisViewComposition,
	AnalysisViewMorningstarCategory,
	AnalysisViewMorningstarGroup,
	AnalysisViewSectors,
}

func (e AnalysisView) IsValid() bool {
	switch e {
	case AnalysisViewComposition, AnalysisViewMorningstarCategory, AnalysisViewMorningstarGroup, AnalysisViewSectors:
		return true
	}
	return false
}

func (e AnalysisView) String() string {
	return string(e)
}

func (e *AnalysisView) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnalysisView(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnalysisView", str)
	}
	return nil
}

func (e AnalysisView) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnalysisView) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnalysisView) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssetClassifier string

const (
	AssetClassifierCash           AssetClassifier = "CASH"
	AssetClassifierPublic         AssetClassifier = "PUBLIC"
	AssetClassifierCompanyEquity  AssetClassifier = "COMPANY_EQUITY"
	AssetClassifierCryptocurrency AssetClassifier = "CRYPTOCURRENCY"
	AssetClassifierStablecoin     AssetClassifier = "STABLECOIN"
	AssetClassifierRealEstate     AssetClassifier = "REAL_ESTATE"
)

var AllAssetClassifier = []AssetClassifier{
	AssetClassifierCash,
	AssetClassifierPublic,
	AssetClassifierCompanyEquity,
	AssetClassifierCryptocurrency,
	AssetClassifierStablecoin,
	AssetClassifierRealEstate,
}

func (e AssetClassifier) IsValid() bool {
	switch e {
	case AssetClassifierCash, AssetClassifierPublic, AssetClassifierCompanyEquity, AssetClassifierCryptocurrency, AssetClassifierStablecoin, AssetClassifierRealEstate:
		return true
	}
	return false
}

func (e AssetClassifier) String() string {
	return string(e)
}

func (e *AssetClassifier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetClassifier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetClassifier", str)
	}
	return nil
}

func (e AssetClassifier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetClassifier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetClassifier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssetSourceAdapter string

const (
	AssetSourceAdapterPlaid     AssetSourceAdapter = "PLAID"
	AssetSourceAdapterSimplefin AssetSourceAdapter = "SIMPLEFIN"
	AssetSourceAdapterDebank    AssetSourceAdapter = "DEBANK"
)

var AllAssetSourceAdapter = []AssetSourceAdapter{
	AssetSourceAdapterPlaid,
	AssetSourceAdapterSimplefin,
	AssetSourceAdapterDebank,
}

func (e AssetSourceAdapter) IsValid() bool {
	switch e {
	case AssetSourceAdapterPlaid, AssetSourceAdapterSimplefin, AssetSourceAdapterDebank:
		return true
	}
	return false
}

func (e AssetSourceAdapter) String() string {
	return string(e)
}

func (e *AssetSourceAdapter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetSourceAdapter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetSourceAdapter", str)
	}
	return nil
}

func (e AssetSourceAdapter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetSourceAdapter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetSourceAdapter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssetType string

const (
	AssetTypeCurrency   AssetType = "CURRENCY"
	AssetTypeSecurity   AssetType = "SECURITY"
	AssetTypeCrypto     AssetType = "CRYPTO"
	AssetTypeRealEstate AssetType = "REAL_ESTATE"
	AssetTypeOther      AssetType = "OTHER"
)

var AllAssetType = []AssetType{
	AssetTypeCurrency,
	AssetTypeSecurity,
	AssetTypeCrypto,
	AssetTypeRealEstate,
	AssetTypeOther,
}

func (e AssetType) IsValid() bool {
	switch e {
	case AssetTypeCurrency, AssetTypeSecurity, AssetTypeCrypto, AssetTypeRealEstate, AssetTypeOther:
		return true
	}
	return false
}

func (e AssetType) String() string {
	return string(e)
}

func (e *AssetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetType", str)
	}
	return nil
}

func (e AssetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BalanceReviewAction string

const (
	BalanceReviewActionApproveChanges BalanceReviewAction = "APPROVE_CHANGES"
	BalanceReviewActionUseProvider    BalanceReviewAction = "USE_PROVIDER"
)

var AllBalanceReviewAction = []BalanceReviewAction{
	BalanceReviewActionApproveChanges,
	BalanceReviewActionUseProvider,
}

func (e BalanceReviewAction) IsValid() bool {
	switch e {
	case BalanceReviewActionApproveChanges, BalanceReviewActionUseProvider:
		return true
	}
	return false
}

func (e BalanceReviewAction) String() string {
	return string(e)
}

func (e *BalanceReviewAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BalanceReviewAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BalanceReviewAction", str)
	}
	return nil
}

func (e BalanceReviewAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BalanceReviewAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BalanceReviewAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BalanceReviewDecision string

const (
	BalanceReviewDecisionInReview        BalanceReviewDecision = "IN_REVIEW"
	BalanceReviewDecisionApprovedChanges BalanceReviewDecision = "APPROVED_CHANGES"
)

var AllBalanceReviewDecision = []BalanceReviewDecision{
	BalanceReviewDecisionInReview,
	BalanceReviewDecisionApprovedChanges,
}

func (e BalanceReviewDecision) IsValid() bool {
	switch e {
	case BalanceReviewDecisionInReview, BalanceReviewDecisionApprovedChanges:
		return true
	}
	return false
}

func (e BalanceReviewDecision) String() string {
	return string(e)
}

func (e *BalanceReviewDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BalanceReviewDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BalanceReviewDecision", str)
	}
	return nil
}

func (e BalanceReviewDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BalanceReviewDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BalanceReviewDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CategoryKind string

const (
	CategoryKindExpense  CategoryKind = "EXPENSE"
	CategoryKindIncome   CategoryKind = "INCOME"
	CategoryKindTransfer CategoryKind = "TRANSFER"
)

var AllCategoryKind = []CategoryKind{
	CategoryKindExpense,
	CategoryKindIncome,
	CategoryKindTransfer,
}

func (e CategoryKind) IsValid() bool {
	switch e {
	case CategoryKindExpense, CategoryKindIncome, CategoryKindTransfer:
		return true
	}
	return false
}

func (e CategoryKind) String() string {
	return string(e)
}

func (e *CategoryKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryKind", str)
	}
	return nil
}

func (e CategoryKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectivityStatus string

const (
	ConnectivityStatusHealthy  ConnectivityStatus = "HEALTHY"
	ConnectivityStatusNotFound ConnectivityStatus = "NOT_FOUND"
	ConnectivityStatusIgnore   ConnectivityStatus = "IGNORE"
)

var AllConnectivityStatus = []ConnectivityStatus{
	ConnectivityStatusHealthy,
	ConnectivityStatusNotFound,
	ConnectivityStatusIgnore,
}

func (e ConnectivityStatus) IsValid() bool {
	switch e {
	case ConnectivityStatusHealthy, ConnectivityStatusNotFound, ConnectivityStatusIgnore:
		return true
	}
	return false
}

func (e ConnectivityStatus) String() string {
	return string(e)
}

func (e *ConnectivityStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectivityStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectivityStatus", str)
	}
	return nil
}

func (e ConnectivityStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectivityStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectivityStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Granularity string

const (
	GranularityDaily     Granularity = "DAILY"
	GranularityWeekly    Granularity = "WEEKLY"
	GranularityMonthly   Granularity = "MONTHLY"
	GranularityQuarterly Granularity = "QUARTERLY"
	GranularityYearly    Granularity = "YEARLY"
)

var AllGranularity = []Granularity{
	GranularityDaily,
	GranularityWeekly,
	GranularityMonthly,
	GranularityQuarterly,
	GranularityYearly,
}

func (e Granularity) IsValid() bool {
	switch e {
	case GranularityDaily, GranularityWeekly, GranularityMonthly, GranularityQuarterly, GranularityYearly:
		return true
	}
	return false
}

func (e Granularity) String() string {
	return string(e)
}

func (e *Granularity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Granularity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Granularity", str)
	}
	return nil
}

func (e Granularity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Granularity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Granularity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LiabilityCategory string

const (
	LiabilityCategoryCard     LiabilityCategory = "CARD"
	LiabilityCategoryMortgage LiabilityCategory = "MORTGAGE"
	LiabilityCategoryLoan     LiabilityCategory = "LOAN"
	LiabilityCategoryOther    LiabilityCategory = "OTHER"
)

var AllLiabilityCategory = []LiabilityCategory{
	LiabilityCategoryCard,
	LiabilityCategoryMortgage,
	LiabilityCategoryLoan,
	LiabilityCategoryOther,
}

func (e LiabilityCategory) IsValid() bool {
	switch e {
	case LiabilityCategoryCard, LiabilityCategoryMortgage, LiabilityCategoryLoan, LiabilityCategoryOther:
		return true
	}
	return false
}

func (e LiabilityCategory) String() string {
	return string(e)
}

func (e *LiabilityCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LiabilityCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LiabilityCategory", str)
	}
	return nil
}

func (e LiabilityCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LiabilityCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LiabilityCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// LLM transaction-categorization backend.
type LlmProvider string

const (
	LlmProviderOllama LlmProvider = "OLLAMA"
)

var AllLlmProvider = []LlmProvider{
	LlmProviderOllama,
}

func (e LlmProvider) IsValid() bool {
	switch e {
	case LlmProviderOllama:
		return true
	}
	return false
}

func (e LlmProvider) String() string {
	return string(e)
}

func (e *LlmProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LlmProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LlmProvider", str)
	}
	return nil
}

func (e LlmProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LlmProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LlmProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NetWorthRange string

const (
	NetWorthRangeOneMonth   NetWorthRange = "ONE_MONTH"
	NetWorthRangeThreeMonth NetWorthRange = "THREE_MONTH"
	NetWorthRangeYtd        NetWorthRange = "YTD"
	NetWorthRangeOneYear    NetWorthRange = "ONE_YEAR"
	NetWorthRangeAll        NetWorthRange = "ALL"
)

var AllNetWorthRange = []NetWorthRange{
	NetWorthRangeOneMonth,
	NetWorthRangeThreeMonth,
	NetWorthRangeYtd,
	NetWorthRangeOneYear,
	NetWorthRangeAll,
}

func (e NetWorthRange) IsValid() bool {
	switch e {
	case NetWorthRangeOneMonth, NetWorthRangeThreeMonth, NetWorthRangeYtd, NetWorthRangeOneYear, NetWorthRangeAll:
		return true
	}
	return false
}

func (e NetWorthRange) String() string {
	return string(e)
}

func (e *NetWorthRange) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NetWorthRange(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NetWorthRange", str)
	}
	return nil
}

func (e NetWorthRange) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NetWorthRange) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NetWorthRange) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlaidEnvironment string

const (
	PlaidEnvironmentSandbox     PlaidEnvironment = "SANDBOX"
	PlaidEnvironmentDevelopment PlaidEnvironment = "DEVELOPMENT"
	PlaidEnvironmentProduction  PlaidEnvironment = "PRODUCTION"
)

var AllPlaidEnvironment = []PlaidEnvironment{
	PlaidEnvironmentSandbox,
	PlaidEnvironmentDevelopment,
	PlaidEnvironmentProduction,
}

func (e PlaidEnvironment) IsValid() bool {
	switch e {
	case PlaidEnvironmentSandbox, PlaidEnvironmentDevelopment, PlaidEnvironmentProduction:
		return true
	}
	return false
}

func (e PlaidEnvironment) String() string {
	return string(e)
}

func (e *PlaidEnvironment) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlaidEnvironment(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlaidEnvironment", str)
	}
	return nil
}

func (e PlaidEnvironment) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlaidEnvironment) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlaidEnvironment) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlaidItemHealthState string

const (
	PlaidItemHealthStateHealthy            PlaidItemHealthState = "HEALTHY"
	PlaidItemHealthStateLinkUpdateRequired PlaidItemHealthState = "LINK_UPDATE_REQUIRED"
	PlaidItemHealthStateSyncError          PlaidItemHealthState = "SYNC_ERROR"
)

var AllPlaidItemHealthState = []PlaidItemHealthState{
	PlaidItemHealthStateHealthy,
	PlaidItemHealthStateLinkUpdateRequired,
	PlaidItemHealthStateSyncError,
}

func (e PlaidItemHealthState) IsValid() bool {
	switch e {
	case PlaidItemHealthStateHealthy, PlaidItemHealthStateLinkUpdateRequired, PlaidItemHealthStateSyncError:
		return true
	}
	return false
}

func (e PlaidItemHealthState) String() string {
	return string(e)
}

func (e *PlaidItemHealthState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlaidItemHealthState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlaidItemHealthState", str)
	}
	return nil
}

func (e PlaidItemHealthState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlaidItemHealthState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlaidItemHealthState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurrenceInterval string

const (
	RecurrenceIntervalWeekly    RecurrenceInterval = "WEEKLY"
	RecurrenceIntervalBiweekly  RecurrenceInterval = "BIWEEKLY"
	RecurrenceIntervalMonthly   RecurrenceInterval = "MONTHLY"
	RecurrenceIntervalQuarterly RecurrenceInterval = "QUARTERLY"
	RecurrenceIntervalYearly    RecurrenceInterval = "YEARLY"
)

var AllRecurrenceInterval = []RecurrenceInterval{
	RecurrenceIntervalWeekly,
	RecurrenceIntervalBiweekly,
	RecurrenceIntervalMonthly,
	RecurrenceIntervalQuarterly,
	RecurrenceIntervalYearly,
}

func (e RecurrenceInterval) IsValid() bool {
	switch e {
	case RecurrenceIntervalWeekly, RecurrenceIntervalBiweekly, RecurrenceIntervalMonthly, RecurrenceIntervalQuarterly, RecurrenceIntervalYearly:
		return true
	}
	return false
}

func (e RecurrenceInterval) String() string {
	return string(e)
}

func (e *RecurrenceInterval) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurrenceInterval(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurrenceInterval", str)
	}
	return nil
}

func (e RecurrenceInterval) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurrenceInterval) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurrenceInterval) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurringStreamStatus string

const (
	RecurringStreamStatusMature         RecurringStreamStatus = "MATURE"
	RecurringStreamStatusEarlyDetection RecurringStreamStatus = "EARLY_DETECTION"
	RecurringStreamStatusTombstoned     RecurringStreamStatus = "TOMBSTONED"
	RecurringStreamStatusUnknown        RecurringStreamStatus = "UNKNOWN"
)

var AllRecurringStreamStatus = []RecurringStreamStatus{
	RecurringStreamStatusMature,
	RecurringStreamStatusEarlyDetection,
	RecurringStreamStatusTombstoned,
	RecurringStreamStatusUnknown,
}

func (e RecurringStreamStatus) IsValid() bool {
	switch e {
	case RecurringStreamStatusMature, RecurringStreamStatusEarlyDetection, RecurringStreamStatusTombstoned, RecurringStreamStatusUnknown:
		return true
	}
	return false
}

func (e RecurringStreamStatus) String() string {
	return string(e)
}

func (e *RecurringStreamStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurringStreamStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurringStreamStatus", str)
	}
	return nil
}

func (e RecurringStreamStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurringStreamStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurringStreamStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Access role assigned to a user.
type Role string

const (
	RoleAdmin            Role = "ADMIN"
	RoleWriter           Role = "WRITER"
	RoleReadonly         Role = "READONLY"
	RoleSpendTracker     Role = "SPEND_TRACKER"
	RoleCashflowTracker  Role = "CASHFLOW_TRACKER"
	RoleNetWorthTracker  Role = "NET_WORTH_TRACKER"
	RolePortfolioTracker Role = "PORTFOLIO_TRACKER"
)

var AllRole = []Role{
	RoleAdmin,
	RoleWriter,
	RoleReadonly,
	RoleSpendTracker,
	RoleCashflowTracker,
	RoleNetWorthTracker,
	RolePortfolioTracker,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleAdmin, RoleWriter, RoleReadonly, RoleSpendTracker, RoleCashflowTracker, RoleNetWorthTracker, RolePortfolioTracker:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Role) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Role) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransactionSortField string

const (
	TransactionSortFieldDate   TransactionSortField = "DATE"
	TransactionSortFieldAmount TransactionSortField = "AMOUNT"
)

var AllTransactionSortField = []TransactionSortField{
	TransactionSortFieldDate,
	TransactionSortFieldAmount,
}

func (e TransactionSortField) IsValid() bool {
	switch e {
	case TransactionSortFieldDate, TransactionSortFieldAmount:
		return true
	}
	return false
}

func (e TransactionSortField) String() string {
	return string(e)
}

func (e *TransactionSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionSortField", str)
	}
	return nil
}

func (e TransactionSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransactionSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransactionSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
