package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"tallyo/internal/graph/model"
	"time"
)

// Connection is the resolver for the connection field.
func (r *accountResolver) Connection(ctx context.Context, obj *model.Account) (*model.Connection, error) {
	return r.Resolver.AccountConnection(ctx, obj)
}

// TypeLocked is the resolver for the typeLocked field.
func (r *accountResolver) TypeLocked(ctx context.Context, obj *model.Account) (bool, error) {
	return obj.Type == model.AccountTypeProperty || (!obj.Manual && obj.Type == model.AccountTypeCryptoWallet), nil
}

// LastSyncedAt is the resolver for the lastSyncedAt field.
func (r *accountResolver) LastSyncedAt(ctx context.Context, obj *model.Account) (*time.Time, error) {
	return r.Resolver.AccountLastBalanceSyncedAt(ctx, obj)
}

// Provider is the resolver for the provider field.
func (r *connectionResolver) Provider(ctx context.Context, obj *model.Connection) (model.ConnectionProvider, error) {
	return r.Resolver.ConnectionProvider(ctx, obj)
}

// CreateOwner is the resolver for the createOwner field.
func (r *mutationResolver) CreateOwner(ctx context.Context, input model.CreateOwnerInput) (*model.Owner, error) {
	return r.Resolver.CreateOwner(ctx, input)
}

// DeleteOwner is the resolver for the deleteOwner field.
func (r *mutationResolver) DeleteOwner(ctx context.Context, id model.GlobalID) (bool, error) {
	return r.Resolver.DeleteOwner(ctx, id)
}

// CreateManualAccount is the resolver for the createManualAccount field.
func (r *mutationResolver) CreateManualAccount(ctx context.Context, input model.CreateManualAccountInput) (*model.CreateManualAccountPayload, error) {
	return r.Resolver.CreateManualAccount(ctx, input)
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, input model.UpdateAccountInput) (*model.UpdateAccountPayload, error) {
	return r.Resolver.UpdateAccount(ctx, input)
}

// RemoveManualAccount is the resolver for the removeManualAccount field.
func (r *mutationResolver) RemoveManualAccount(ctx context.Context, input model.RemoveManualAccountInput) (*model.RemoveManualAccountPayload, error) {
	return r.Resolver.RemoveManualAccount(ctx, input)
}

// UpdateConnection is the resolver for the updateConnection field.
func (r *mutationResolver) UpdateConnection(ctx context.Context, input model.UpdateConnectionInput) (*model.UpdateConnectionPayload, error) {
	return r.Resolver.UpdateConnection(ctx, input)
}

// DeleteConnection is the resolver for the deleteConnection field.
func (r *mutationResolver) DeleteConnection(ctx context.Context, input model.DeleteConnectionInput) (*model.DeleteConnectionPayload, error) {
	return r.Resolver.DeleteConnection(ctx, input)
}

// LinkEVMWallet is the resolver for the linkEVMWallet field.
func (r *mutationResolver) LinkEVMWallet(ctx context.Context, input model.LinkEVMWalletInput) (*model.LinkEVMWalletPayload, error) {
	return r.Resolver.LinkEVMWallet(ctx, input)
}

// UnlinkEVMWallet is the resolver for the unlinkEVMWallet field.
func (r *mutationResolver) UnlinkEVMWallet(ctx context.Context, id model.GlobalID) (bool, error) {
	return r.Resolver.UnlinkEVMWallet(ctx, id)
}

// CreateLinkToken is the resolver for the createLinkToken field.
func (r *mutationResolver) CreateLinkToken(ctx context.Context, input model.CreateLinkTokenInput) (*model.CreateLinkTokenPayload, error) {
	return r.Resolver.CreateLinkToken(ctx, input)
}

// ExchangePublicToken is the resolver for the exchangePublicToken field.
func (r *mutationResolver) ExchangePublicToken(ctx context.Context, input model.ExchangePublicTokenInput) (*model.ExchangePublicTokenPayload, error) {
	return r.Resolver.ExchangePublicToken(ctx, input)
}

// CreateUpdateLinkToken is the resolver for the createUpdateLinkToken field.
func (r *mutationResolver) CreateUpdateLinkToken(ctx context.Context, itemID model.GlobalID) (*model.CreateLinkTokenPayload, error) {
	return r.Resolver.CreateUpdateLinkToken(ctx, itemID)
}

// CompleteLinkUpdate is the resolver for the completeLinkUpdate field.
func (r *mutationResolver) CompleteLinkUpdate(ctx context.Context, itemID model.GlobalID) (*model.CompleteLinkUpdatePayload, error) {
	return r.Resolver.CompleteLinkUpdate(ctx, itemID)
}

// CreateSimpleFinAccessToken is the resolver for the createSimpleFinAccessToken field.
func (r *mutationResolver) CreateSimpleFinAccessToken(ctx context.Context, input model.CreateSimpleFinAccessTokenInput) (*model.CreateSimpleFinAccessTokenPayload, error) {
	return r.Resolver.CreateSimpleFinAccessToken(ctx, input)
}

// DeleteSimpleFinAccessToken is the resolver for the deleteSimpleFinAccessToken field.
func (r *mutationResolver) DeleteSimpleFinAccessToken(ctx context.Context, id model.GlobalID) (bool, error) {
	return r.Resolver.DeleteSimpleFinAccessToken(ctx, id)
}

// ResetSimpleFinSync is the resolver for the resetSimpleFinSync field.
func (r *mutationResolver) ResetSimpleFinSync(ctx context.Context, id model.GlobalID) (*model.SimpleFinAccessToken, error) {
	return r.Resolver.ResetSimpleFinSync(ctx, id)
}

// Credential is the resolver for the credential field.
func (r *plaidItemResolver) Credential(ctx context.Context, obj *model.PlaidItem) (*model.PlaidCredential, error) {
	if obj.Credential == nil {
		return nil, nil
	}
	if obj.Credential.ClientID != "" {
		return obj.Credential, nil
	}
	credential, err := loadersFrom(ctx).PlaidCredential.Load(ctx, obj.Credential.ID)()
	if credential != nil || err != nil {
		return credential, err
	}
	return obj.Credential, nil
}

// Accounts is the resolver for the accounts field.
func (r *plaidItemResolver) Accounts(ctx context.Context, obj *model.PlaidItem) ([]*model.Account, error) {
	if obj.Accounts != nil {
		return obj.Accounts, nil
	}
	return loadersFrom(ctx).ItemAccounts.Load(ctx, obj.ID.Int64())()
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) (*model.AccountList, error) {
	return r.Resolver.Accounts(ctx)
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id model.GlobalID) (*model.Account, error) {
	return r.Resolver.QueryAccount(ctx, id)
}

// Owners is the resolver for the owners field.
func (r *queryResolver) Owners(ctx context.Context) (*model.OwnerList, error) {
	return r.Resolver.GetOwners(ctx)
}

// PlaidItems is the resolver for the plaidItems field.
func (r *queryResolver) PlaidItems(ctx context.Context, input *model.PlaidItemsInput) (*model.PlaidItemList, error) {
	return r.Resolver.PlaidItems(ctx, input)
}

// Connections is the resolver for the connections field.
func (r *queryResolver) Connections(ctx context.Context, input *model.ConnectionsInput) (*model.ConnectionList, error) {
	return r.Resolver.Connections(ctx, input)
}

// EvmChains is the resolver for the evmChains field.
func (r *queryResolver) EvmChains(ctx context.Context) (*model.EVMChainList, error) {
	return r.Resolver.EVMChains(ctx)
}

// SimpleFinAccessTokens is the resolver for the simpleFinAccessTokens field.
func (r *queryResolver) SimpleFinAccessTokens(ctx context.Context) (*model.SimpleFinAccessTokenList, error) {
	return r.Resolver.SimpleFinAccessTokens(ctx)
}

// Connections is the resolver for the connections field.
func (r *simpleFinAccessTokenResolver) Connections(ctx context.Context, obj *model.SimpleFinAccessToken) ([]*model.SimpleFinConnection, error) {
	return r.Resolver.SimpleFinAccessTokenConnections(ctx, obj)
}

// Account returns AccountResolver implementation.
func (r *Resolver) Account() AccountResolver { return &accountResolver{r} }

// Connection returns ConnectionResolver implementation.
func (r *Resolver) Connection() ConnectionResolver { return &connectionResolver{r} }

// PlaidItem returns PlaidItemResolver implementation.
func (r *Resolver) PlaidItem() PlaidItemResolver { return &plaidItemResolver{r} }

// SimpleFinAccessToken returns SimpleFinAccessTokenResolver implementation.
func (r *Resolver) SimpleFinAccessToken() SimpleFinAccessTokenResolver {
	return &simpleFinAccessTokenResolver{r}
}

type (
	accountResolver              struct{ *Resolver }
	connectionResolver           struct{ *Resolver }
	plaidItemResolver            struct{ *Resolver }
	simpleFinAccessTokenResolver struct{ *Resolver }
)
