package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"tallyo/internal/graph/model"
)

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, input model.AddUserInput) (*model.AddUserPayload, error) {
	return r.Resolver.AddUser(ctx, input)
}

// CreateInviteLink is the resolver for the createInviteLink field.
func (r *mutationResolver) CreateInviteLink(ctx context.Context, input model.CreateInviteLinkInput) (*model.CreateInviteLinkPayload, error) {
	return r.Resolver.CreateInviteLink(ctx, input)
}

// RemoveUser is the resolver for the removeUser field.
func (r *mutationResolver) RemoveUser(ctx context.Context, input model.RemoveUserInput) (*model.RemoveUserPayload, error) {
	return r.Resolver.RemoveUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.UpdateUserPayload, error) {
	return r.Resolver.UpdateUser(ctx, input)
}

// CreatePlaidCredential is the resolver for the createPlaidCredential field.
func (r *mutationResolver) CreatePlaidCredential(ctx context.Context, input model.CreatePlaidCredentialInput) (*model.CreatePlaidCredentialPayload, error) {
	return r.Resolver.CreatePlaidCredential(ctx, input)
}

// UpdatePlaidCredential is the resolver for the updatePlaidCredential field.
func (r *mutationResolver) UpdatePlaidCredential(ctx context.Context, input model.UpdatePlaidCredentialInput) (*model.UpdatePlaidCredentialPayload, error) {
	return r.Resolver.UpdatePlaidCredential(ctx, input)
}

// DeletePlaidCredential is the resolver for the deletePlaidCredential field.
func (r *mutationResolver) DeletePlaidCredential(ctx context.Context, input model.DeletePlaidCredentialInput) (*model.DeletePlaidCredentialPayload, error) {
	return r.Resolver.DeletePlaidCredential(ctx, input)
}

// UpdateConfiguration is the resolver for the updateConfiguration field.
func (r *mutationResolver) UpdateConfiguration(ctx context.Context, input model.UpdateConfigurationInput) (*model.UpdateConfigurationPayload, error) {
	return r.Resolver.UpdateConfiguration(ctx, input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) (*model.UserList, error) {
	return r.Resolver.GetUsers(ctx)
}

// PlaidCredentials is the resolver for the plaidCredentials field.
func (r *queryResolver) PlaidCredentials(ctx context.Context) (*model.PlaidCredentialList, error) {
	return r.Resolver.PlaidCredentials(ctx)
}

// Configuration is the resolver for the configuration field.
func (r *queryResolver) Configuration(ctx context.Context) (*model.Configuration, error) {
	return r.Resolver.Configuration(), nil
}

// GeneralConfiguration is the resolver for the generalConfiguration field.
func (r *queryResolver) GeneralConfiguration(ctx context.Context) (*model.GeneralConfiguration, error) {
	return r.Resolver.GeneralConfiguration(), nil
}

// InstanceTimezone is the resolver for the instanceTimezone field.
func (r *queryResolver) InstanceTimezone(ctx context.Context) (string, error) {
	return r.Resolver.InstanceTimezone(), nil
}
