package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"tallyo/internal/graph/model"
)

// Analysis is the resolver for the analysis field.
func (r *queryResolver) Analysis(ctx context.Context, input model.AnalysisInput) (*model.AnalysisReport, error) {
	return r.Resolver.Analysis(ctx, input)
}
