package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"tallyo/internal/graph/model"
)

// LatestSnapshot is the resolver for the latestSnapshot field.
func (r *accountResolver) LatestSnapshot(ctx context.Context, obj *model.Account) (*model.AccountSnapshot, error) {
	return r.Resolver.AccountLatestSnapshot(ctx, obj)
}

// AccountWealthProperty is the resolver for the accountWealthProperty field.
func (r *accountResolver) AccountWealthProperty(ctx context.Context, obj *model.Account) (model.AccountWealthProperty, error) {
	return r.Resolver.AccountWealthProperty(ctx, obj)
}

// Details is the resolver for the details field.
func (r *assetResolver) Details(ctx context.Context, obj *model.Asset) (model.AssetDetails, error) {
	if obj.AssetType != model.AssetTypeRealEstate {
		return nil, nil
	}
	asset := obj
	if obj.Address == nil {
		assetID := obj.ID.Int64()
		fetched, err := loadersFrom(ctx).Asset.Load(ctx, assetID)()
		if err != nil {
			return nil, err
		}
		if fetched != nil {
			asset = fetched
		}
	}

	if asset.Address == nil {
		return nil, nil
	}
	return &model.RealEstateAssetDetails{Address: asset.Address}, nil
}

// AdapterSources is the resolver for the adapterSources field.
func (r *assetResolver) AdapterSources(ctx context.Context, obj *model.Asset) ([]*model.AssetAdapterSource, error) {
	return r.Resolver.AssetAdapterSources(ctx, obj)
}

// LatestSnapshot is the resolver for the latestSnapshot field.
func (r *assetResolver) LatestSnapshot(ctx context.Context, obj *model.Asset) (*model.AssetSnapshot, error) {
	return r.Resolver.AssetLatestSnapshot(ctx, obj)
}

// Account is the resolver for the account field.
func (r *holdingResolver) Account(ctx context.Context, obj *model.Holding) (*model.Account, error) {
	return r.Resolver.HoldingAccount(ctx, obj)
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input model.CreateAssetInput) (*model.CreateAssetPayload, error) {
	return r.Resolver.CreateAsset(ctx, input)
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, input model.UpdateAssetInput) (*model.UpdateAssetPayload, error) {
	return r.Resolver.UpdateAsset(ctx, input)
}

// MergeAsset is the resolver for the mergeAsset field.
func (r *mutationResolver) MergeAsset(ctx context.Context, input model.MergeAssetInput) (*model.MergeAssetPayload, error) {
	return r.Resolver.MergeAsset(ctx, input)
}

// LinkRealEstate is the resolver for the linkRealEstate field.
func (r *mutationResolver) LinkRealEstate(ctx context.Context, input model.LinkRealEstateInput) (*model.LinkRealEstatePayload, error) {
	return r.Resolver.LinkRealEstate(ctx, input)
}

// UpdateRealEstate is the resolver for the updateRealEstate field.
func (r *mutationResolver) UpdateRealEstate(ctx context.Context, input model.UpdateRealEstateInput) (*model.UpdateRealEstatePayload, error) {
	return r.Resolver.UpdateRealEstate(ctx, input)
}

// UnlinkRealEstate is the resolver for the unlinkRealEstate field.
func (r *mutationResolver) UnlinkRealEstate(ctx context.Context, id model.GlobalID) (bool, error) {
	return r.Resolver.UnlinkRealEstate(ctx, id)
}

// ResolveBalanceReview is the resolver for the resolveBalanceReview field.
func (r *mutationResolver) ResolveBalanceReview(ctx context.Context, input model.ResolveBalanceReviewInput) (*model.ResolveBalanceReviewPayload, error) {
	return r.Resolver.ResolveBalanceReview(ctx, input)
}

// ChangeAccountSnapshot is the resolver for the changeAccountSnapshot field.
func (r *mutationResolver) ChangeAccountSnapshot(ctx context.Context, input model.ChangeAccountSnapshotInput) (*model.ChangeAccountSnapshotPayload, error) {
	return r.Resolver.ChangeAccountSnapshot(ctx, input)
}

// NetWorth is the resolver for the netWorth field.
func (r *queryResolver) NetWorth(ctx context.Context, input model.NetWorthInput) (*model.NetWorthReport, error) {
	return r.Resolver.NetWorth(ctx, input)
}

// HistoricalNetWorth is the resolver for the historicalNetWorth field.
func (r *queryResolver) HistoricalNetWorth(ctx context.Context, input model.HistoricalNetWorthInput) (*model.HistoricalNetWorthReport, error) {
	return r.Resolver.HistoricalNetWorth(ctx, input)
}

// AssetQuote is the resolver for the assetQuote field.
func (r *queryResolver) AssetQuote(ctx context.Context, ticker string) (*model.AssetQuote, error) {
	return r.Resolver.QueryAssetQuote(ctx, ticker)
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, input *model.AssetsInput) (*model.AssetList, error) {
	return r.Resolver.Assets(ctx, input)
}

// BalanceSnapshotReviews is the resolver for the balanceSnapshotReviews field.
func (r *queryResolver) BalanceSnapshotReviews(ctx context.Context) (*model.BalanceSnapshotReviewList, error) {
	return r.Resolver.BalanceSnapshotReviews(ctx)
}

// AccountSnapshot is the resolver for the accountSnapshot field.
func (r *queryResolver) AccountSnapshot(ctx context.Context, input model.AccountSnapshotInput) (*model.AccountSnapshot, error) {
	return r.Resolver.AccountSnapshot(ctx, input)
}

// AccountSnapshots is the resolver for the accountSnapshots field.
func (r *queryResolver) AccountSnapshots(ctx context.Context, input model.AccountSnapshotsInput) (*model.AccountSnapshotConnection, error) {
	return r.Resolver.AccountSnapshots(ctx, input)
}

// Asset returns AssetResolver implementation.
func (r *Resolver) Asset() AssetResolver { return &assetResolver{r} }

// Holding returns HoldingResolver implementation.
func (r *Resolver) Holding() HoldingResolver { return &holdingResolver{r} }

type (
	assetResolver   struct{ *Resolver }
	holdingResolver struct{ *Resolver }
)
