use std::fmt::Write as _;

use anyhow::{Context, Result, bail, ensure};
use apollo_compiler::{
    Schema,
    ast::{DirectiveList, Type, Value},
    schema::{ExtendedType, FieldDefinition, InputValueDefinition},
};
use heck::{ToSnakeCase, ToUpperCamelCase};

pub(crate) const HEADER: &str = "// Code generated by tools/graphql-gen from schema/*.graphql. DO NOT EDIT.\n\
#![allow(dead_code)]\n";

struct Scalar {
    graphql: &'static str,
    rust: &'static str,
    // The type whose JsonSchema impl describes the scalar on the MCP wire (`ID` travels as a global id).
    json_schema: &'static str,
}

const fn scalar(graphql: &'static str, rust: &'static str) -> Scalar {
    Scalar {
        graphql,
        rust,
        json_schema: rust,
    }
}

const SCALARS: &[Scalar] = &[
    Scalar {
        graphql: "ID",
        rust: "async_graphql::ID",
        json_schema: "crate::ids::GlobalId",
    },
    scalar("String", "String"),
    scalar("Int", "i32"),
    scalar("Float", "f64"),
    scalar("Boolean", "bool"),
    scalar("Date", "crate::ids::Date"),
    scalar("DateTime", "chrono::DateTime<chrono::Utc>"),
    scalar("Money", "crate::money::Cents"),
];

pub(crate) fn write_docs(output: &mut String, description: Option<&str>, indent: &str) {
    if let Some(description) = description {
        for line in description.lines() {
            writeln!(output, "{indent}/// {line}").unwrap();
        }
    }
}

pub(crate) fn rust_identifier(name: &str) -> String {
    let name = name.to_snake_case();
    if matches!(
        name.as_str(),
        "abstract"
            | "as"
            | "async"
            | "await"
            | "become"
            | "box"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "do"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "final"
            | "fn"
            | "for"
            | "gen"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "macro"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "override"
            | "priv"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "typeof"
            | "union"
            | "unsafe"
            | "unsized"
            | "use"
            | "virtual"
            | "where"
            | "while"
            | "yield"
    ) {
        format!("r#{name}")
    } else {
        name
    }
}

pub(crate) fn rust_type(ty: &Type, schema: &Schema) -> Result<String> {
    map_type(ty, schema, |scalar| scalar.rust)
}

pub(crate) fn json_schema_type(ty: &Type, schema: &Schema) -> Result<String> {
    map_type(ty, schema, |scalar| scalar.json_schema)
}

fn map_type(ty: &Type, schema: &Schema, scalar_type: fn(&Scalar) -> &'static str) -> Result<String> {
    let base = match ty {
        Type::Named(name) | Type::NonNullNamed(name)
            if matches!(schema.types.get(name), Some(ExtendedType::Scalar(_))) =>
        {
            SCALARS
                .iter()
                .find(|scalar| scalar.graphql == name.as_str())
                .map(scalar_type)
                .with_context(|| format!("no Rust mapping for scalar {name}"))?
                .to_owned()
        }
        Type::Named(name) | Type::NonNullNamed(name) => name.to_upper_camel_case(),
        Type::List(item) | Type::NonNullList(item) => format!("Vec<{}>", map_type(item, schema, scalar_type)?),
    };
    Ok(if ty.is_non_null() { base } else { format!("Option<{base}>") })
}

pub(crate) fn write_trait_method(
    output: &mut String,
    owner: &str,
    field: &FieldDefinition,
    schema: &Schema,
) -> Result<()> {
    let return_type = rust_type(&field.ty, schema)?;
    writeln!(output, "    fn {}(", rust_identifier(&field.name)).unwrap();
    writeln!(output, "        &self,").unwrap();
    writeln!(output, "        ctx: &async_graphql::Context<'_>,").unwrap();
    for argument in &field.arguments {
        ensure!(
            argument.default_value.is_none(),
            "unsupported default value for argument {owner}.{}.{}",
            field.name,
            argument.name
        );
        writeln!(
            output,
            "        {}: {},",
            rust_identifier(&argument.name),
            rust_type(&argument.ty, schema)?
        )
        .unwrap();
    }
    writeln!(
        output,
        "    ) -> impl std::future::Future<Output = async_graphql::Result<{return_type}>> + Send;"
    )
    .unwrap();
    Ok(())
}

pub(crate) fn write_delegating_method(
    output: &mut String,
    owner: &str,
    field: &FieldDefinition,
    schema: &Schema,
    complexity: Option<&str>,
) -> Result<FieldAttributes> {
    let arguments = field
        .arguments
        .iter()
        .map(|argument| format!(", {}", rust_identifier(&argument.name)))
        .collect::<String>();
    let call = format!(
        "{}Resolvers::{}(self, ctx{arguments}).await",
        owner.to_upper_camel_case(),
        rust_identifier(&field.name)
    );
    write_method(output, field, schema, &call, complexity)
}

pub(crate) fn write_guarded_accessor(output: &mut String, field: &FieldDefinition, schema: &Schema) -> Result<()> {
    write_method(
        output,
        field,
        schema,
        &format!("Ok(self.{}.clone())", rust_identifier(&field.name)),
        None,
    )
    .map(drop)
}

// Guards run inside the method body rather than via #[graphql(guard)] so that, together with the
// resolver call, a failure on a nullable field is recorded as a pathed error and resolves to null;
// async-graphql otherwise omits the field from the response entirely.
fn write_method(
    output: &mut String,
    field: &FieldDefinition,
    schema: &Schema,
    body: &str,
    complexity: Option<&str>,
) -> Result<FieldAttributes> {
    write_docs(output, field.description.as_deref(), "    ");
    let attributes = field_metadata(&field.name, &field.directives)?;
    write_graphql_attribute(output, "    ", &field.name, &attributes, complexity);
    let return_type = rust_type(&field.ty, schema)?;
    writeln!(output, "    async fn {}(", rust_identifier(&field.name)).unwrap();
    writeln!(output, "        &self,").unwrap();
    writeln!(output, "        ctx: &async_graphql::Context<'_>,").unwrap();
    for argument in &field.arguments {
        argument_attributes(output, argument)?;
        writeln!(
            output,
            "        {}: {},",
            rust_identifier(&argument.name),
            rust_type(&argument.ty, schema)?
        )
        .unwrap();
    }
    writeln!(output, "    ) -> async_graphql::Result<{return_type}> {{").unwrap();
    let guard = attributes
        .guard()
        .map(|guard| format!("async_graphql::Guard::check(&{guard}, ctx).await?;\n"))
        .unwrap_or_default();
    if field.ty.is_non_null() {
        writeln!(output, "        {guard}{body}").unwrap();
    } else {
        writeln!(output, "        nullable(ctx, async {{ {guard}{body} }}).await").unwrap();
    }
    writeln!(output, "    }}\n").unwrap();
    Ok(attributes)
}

fn argument_attributes(output: &mut String, argument: &InputValueDefinition) -> Result<()> {
    let mut graphql = vec![format!("name = {:?}", argument.name)];
    if let Some(description) = argument.description.as_deref() {
        graphql.push(format!("desc = {description:?}"));
    }
    if let Some(reason) = directive_reason(&argument.directives)? {
        graphql.push(format!("deprecation = {reason:?}"));
    }
    writeln!(output, "        #[graphql({})]", graphql.join(", ")).unwrap();
    Ok(())
}

pub(crate) struct FieldAttributes {
    pub(crate) scope: Option<String>,
    deprecation: Option<String>,
    pub(crate) dynamic_scope: bool,
}

impl FieldAttributes {
    pub(crate) fn guard(&self) -> Option<String> {
        self.scope
            .as_ref()
            .map(|scope| format!("crate::graph::ScopeGuard::new({scope:?})"))
            .or_else(|| self.dynamic_scope.then(|| "crate::graph::DynamicScopeGuard".to_owned()))
    }
}

pub(crate) fn field_attributes(
    output: &mut String,
    name: &str,
    directives: &DirectiveList,
    indent: &str,
) -> Result<FieldAttributes> {
    let attributes = field_metadata(name, directives)?;
    write_graphql_attribute(output, indent, name, &attributes, None);
    Ok(attributes)
}

fn write_graphql_attribute(
    output: &mut String,
    indent: &str,
    name: &str,
    attributes: &FieldAttributes,
    complexity: Option<&str>,
) {
    let mut graphql = vec![format!("name = {name:?}")];
    if let Some(reason) = &attributes.deprecation {
        graphql.push(format!("deprecation = {reason:?}"));
    }
    if let Some(complexity) = complexity {
        graphql.push(format!("complexity = {complexity:?}"));
    }
    writeln!(output, "{indent}#[graphql({})]", graphql.join(", ")).unwrap();
}

pub(crate) fn field_metadata(name: &str, directives: &DirectiveList) -> Result<FieldAttributes> {
    let scope = directive_scope(directives)?;
    let dynamic_scope = directives.has("requiresDynamicScope");
    ensure!(
        !(scope.is_some() && dynamic_scope),
        "field {name} cannot require static and dynamic scopes"
    );
    Ok(FieldAttributes {
        scope,
        deprecation: directive_reason(directives)?,
        dynamic_scope,
    })
}

fn directive_reason(directives: &DirectiveList) -> Result<Option<String>> {
    directives
        .get("deprecated")
        .map(|directive| {
            directive
                .arguments
                .iter()
                .find(|argument| argument.name == "reason")
                .map(|argument| match &*argument.value {
                    Value::String(value) => Ok(value.clone()),
                    value => bail!("deprecated reason must be a string, got {value}"),
                })
                .unwrap_or_else(|| Ok("No longer supported".to_owned()))
        })
        .transpose()
}

fn directive_scope(directives: &DirectiveList) -> Result<Option<String>> {
    directives
        .get("requiresScope")
        .map(|directive| {
            let Some(argument) = directive.arguments.iter().find(|argument| argument.name == "scope") else {
                bail!("requiresScope is missing scope");
            };
            match &*argument.value {
                Value::String(scope) => Ok(scope.clone()),
                value => bail!("requiresScope scope must be a string, got {value}"),
            }
        })
        .transpose()
}
