// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"strings"
)

const accountRecords = `-- name: AccountRecords :many
SELECT
  a.connection_id, a.created_at, a.external_id, a.id, a.is_closed, a.is_hidden, a.manual, a.mask, a.name, a.needs_review, a.notes, a.owner_id, a.review_reason, a.subtype, a.type, a.updated_at,
  o.name AS owner_name
FROM accounts a
JOIN owners o ON o.id = a.owner_id
WHERE TRUE
  AND a.id = ?1 -- :if $1
  AND EXISTS (SELECT 1 FROM connections c WHERE c.id = a.connection_id AND c.source_id = ?2 AND c.source_table = 'plaid_items') -- :if $2
  AND a.id IN (/*SLICE:ids*/?3) -- :if $3
  AND a.external_id IN (/*SLICE:external_ids*/?4) -- :if $4
ORDER BY o.name, a.name
`

var _accountRecordsDynQ = dynCompile(accountRecords)

type AccountRecordsParams struct {
	ID          *int64
	ItemID      *int64
	Ids         []int64
	ExternalIds []string
}

type AccountRecordsRow struct {
	Account   Account
	OwnerName string
}

// Used by GraphQL query accounts (accounts.graphql) via accounts/db.Store, filterable by id, Plaid item, or an id list (for the Account dataloader).
func (q *Queries) AccountRecords(ctx context.Context, arg AccountRecordsParams) ([]AccountRecordsRow, error) {

	dynQuery, dynArgs := _accountRecordsDynQ.Build([]any{arg.ID, arg.ItemID, arg.Ids, arg.ExternalIds})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountRecordsRow{}
	for rows.Next() {
		var i AccountRecordsRow
		if err := rows.Scan(
			&i.Account.ConnectionID,
			&i.Account.CreatedAt,
			&i.Account.ExternalID,
			&i.Account.ID,
			&i.Account.IsClosed,
			&i.Account.IsHidden,
			&i.Account.Manual,
			&i.Account.Mask,
			&i.Account.Name,
			&i.Account.NeedsReview,
			&i.Account.Notes,
			&i.Account.OwnerID,
			&i.Account.ReviewReason,
			&i.Account.Subtype,
			&i.Account.Type,
			&i.Account.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountsByConnectionSources = `-- name: AccountsByConnectionSources :many
SELECT
  c.source_id,
  a.connection_id, a.created_at, a.external_id, a.id, a.is_closed, a.is_hidden, a.manual, a.mask, a.name, a.needs_review, a.notes, a.owner_id, a.review_reason, a.subtype, a.type, a.updated_at,
  o.name AS owner_name
FROM accounts a
JOIN owners o ON o.id = a.owner_id
JOIN connections c ON c.id = a.connection_id
WHERE c.source_table = ?1
  AND c.source_id IN (/*SLICE:source_ids*/?)
ORDER BY c.source_id, o.name, a.name
`

type AccountsByConnectionSourcesParams struct {
	SourceTable string
	SourceIds   []int64
}

type AccountsByConnectionSourcesRow struct {
	SourceID  int64
	Account   Account
	OwnerName string
}

// Used by source-backed GraphQL dataloaders to batch-load accounts per connection source.
func (q *Queries) AccountsByConnectionSources(ctx context.Context, arg AccountsByConnectionSourcesParams) ([]AccountsByConnectionSourcesRow, error) {
	query := accountsByConnectionSources
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SourceTable)
	if len(arg.SourceIds) > 0 {
		for _, v := range arg.SourceIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:source_ids*/?", strings.Repeat(",?", len(arg.SourceIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:source_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountsByConnectionSourcesRow{}
	for rows.Next() {
		var i AccountsByConnectionSourcesRow
		if err := rows.Scan(
			&i.SourceID,
			&i.Account.ConnectionID,
			&i.Account.CreatedAt,
			&i.Account.ExternalID,
			&i.Account.ID,
			&i.Account.IsClosed,
			&i.Account.IsHidden,
			&i.Account.Manual,
			&i.Account.Mask,
			&i.Account.Name,
			&i.Account.NeedsReview,
			&i.Account.Notes,
			&i.Account.OwnerID,
			&i.Account.ReviewReason,
			&i.Account.Subtype,
			&i.Account.Type,
			&i.Account.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteManualAccountByID = `-- name: DeleteManualAccountByID :execrows
DELETE FROM accounts
WHERE id = ?1
  AND manual = 1
`

type DeleteManualAccountByIDParams struct {
	ID int64
}

// Used by GraphQL mutation removeManualAccount via accounts/db.Store.
func (q *Queries) DeleteManualAccountByID(ctx context.Context, arg DeleteManualAccountByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteManualAccountByID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const hiddenAccountIDsByConnection = `-- name: HiddenAccountIDsByConnection :many
SELECT external_id
FROM accounts
WHERE connection_id = ?1
  AND is_hidden = 1
`

type HiddenAccountIDsByConnectionParams struct {
	ConnectionID *int64
}

// Used by accounts/db.Store.DeleteConnection to preserve which accounts were user-hidden before removing them.
func (q *Queries) HiddenAccountIDsByConnection(ctx context.Context, arg HiddenAccountIDsByConnectionParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, hiddenAccountIDsByConnection, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLinkedAccount = `-- name: InsertLinkedAccount :one
INSERT INTO accounts (external_id, connection_id, owner_id, name, type, is_closed, is_hidden, manual)
VALUES (?1, ?2, ?3, ?4, ?5, 0, 0, 0)
RETURNING id
`

type InsertLinkedAccountParams struct {
	ExternalID   string
	ConnectionID *int64
	OwnerID      int64
	Name         string
	Type         string
}

// Used by EVM wallet and real estate link flows to create their generated account rows.
func (q *Queries) InsertLinkedAccount(ctx context.Context, arg InsertLinkedAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertLinkedAccount,
		arg.ExternalID,
		arg.ConnectionID,
		arg.OwnerID,
		arg.Name,
		arg.Type,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertManualAccount = `-- name: InsertManualAccount :one
INSERT INTO accounts (external_id, connection_id, owner_id, name, type, subtype, mask, notes, is_closed, is_hidden, manual)
VALUES (?1, ?2, ?3, ?4, ?5, NULL, NULL, ?6, ?7, ?8, 1)
ON CONFLICT(external_id) DO NOTHING
RETURNING id
`

type InsertManualAccountParams struct {
	ExternalID   string
	ConnectionID *int64
	OwnerID      int64
	Name         string
	Type         string
	Notes        *string
	IsClosed     bool
	IsHidden     bool
}

// Used by GraphQL mutation createManualAccount via accounts/db.Store.
func (q *Queries) InsertManualAccount(ctx context.Context, arg InsertManualAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertManualAccount,
		arg.ExternalID,
		arg.ConnectionID,
		arg.OwnerID,
		arg.Name,
		arg.Type,
		arg.Notes,
		arg.IsClosed,
		arg.IsHidden,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateAccountFields = `-- name: UpdateAccountFields :execrows
UPDATE accounts
SET name = CASE WHEN CAST(?1 AS BOOLEAN) = 1 THEN ?2 ELSE name END,
    owner_id = CASE WHEN CAST(?3 AS BOOLEAN) = 1 THEN ?4 ELSE owner_id END,
    type = CASE WHEN CAST(?5 AS BOOLEAN) = 1 THEN ?6 ELSE type END,
    subtype = CASE WHEN CAST(?7 AS BOOLEAN) = 1 THEN ?8 ELSE subtype END,
    notes = CASE WHEN CAST(?9 AS BOOLEAN) = 1 THEN ?10 ELSE notes END,
    is_closed = CASE WHEN CAST(?11 AS BOOLEAN) = 1 THEN ?12 ELSE is_closed END,
    is_hidden = CASE WHEN CAST(?13 AS BOOLEAN) = 1 THEN ?14 ELSE is_hidden END,
    needs_review = CASE WHEN CAST(?5 AS BOOLEAN) = 1 THEN 0 ELSE needs_review END,
    review_reason = CASE WHEN CAST(?5 AS BOOLEAN) = 1 THEN NULL ELSE review_reason END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?15
`

type UpdateAccountFieldsParams struct {
	SetName    bool
	Name       string
	SetOwner   bool
	OwnerID    *int64
	SetType    bool
	Type       string
	SetSubtype bool
	Subtype    *string
	SetNotes   bool
	Notes      *string
	SetClosed  bool
	IsClosed   bool
	SetHidden  bool
	IsHidden   bool
	ID         int64
}

// Used by GraphQL mutation updateAccount via accounts/db.Store.UpdateAccount.
func (q *Queries) UpdateAccountFields(ctx context.Context, arg UpdateAccountFieldsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAccountFields,
		arg.SetName,
		arg.Name,
		arg.SetOwner,
		arg.OwnerID,
		arg.SetType,
		arg.Type,
		arg.SetSubtype,
		arg.Subtype,
		arg.SetNotes,
		arg.Notes,
		arg.SetClosed,
		arg.IsClosed,
		arg.SetHidden,
		arg.IsHidden,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTransactionsHiddenByAccount = `-- name: UpdateTransactionsHiddenByAccount :exec
UPDATE transactions
SET is_hidden = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE account_id = ?2
  AND is_hidden <> ?1
`

type UpdateTransactionsHiddenByAccountParams struct {
	IsHidden  bool
	AccountID int64
}

// Used by accounts/db.Store.UpdateAccount when the hidden toggle flips, to retroactively set is_hidden on all of the account's existing transactions.
func (q *Queries) UpdateTransactionsHiddenByAccount(ctx context.Context, arg UpdateTransactionsHiddenByAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionsHiddenByAccount, arg.IsHidden, arg.AccountID)
	return err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (external_id, connection_id, owner_id, name, type, subtype, mask, notes, is_closed, is_hidden, needs_review, review_reason, manual)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, CASE WHEN ?11 = 1 THEN 'TYPE' ELSE NULL END, 0)
ON CONFLICT(external_id) DO UPDATE SET
  connection_id = excluded.connection_id,
  owner_id = excluded.owner_id,
  name = excluded.name,
  -- type is classified once on insert and preserved on conflict so provider
  -- re-syncs never clobber the stored (or user-corrected) account type.
  -- needs_review/review_reason follow the same insert-only semantics and are
  -- cleared only by updateAccount when the user confirms the type.
  subtype = COALESCE(accounts.subtype, excluded.subtype),
  mask = excluded.mask,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertAccountParams struct {
	ExternalID   string
	ConnectionID *int64
	OwnerID      int64
	Name         string
	Type         string
	Subtype      *string
	Mask         *string
	Notes        *string
	IsClosed     bool
	IsHidden     bool
	NeedsReview  bool
}

// Used by the Plaid and SimpleFIN sync adapters (via accounts/db.Store.UpsertAccountWithExternalID) to upsert an externally-discovered account, preserving the stored/user-corrected subtype on re-sync.
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertAccount,
		arg.ExternalID,
		arg.ConnectionID,
		arg.OwnerID,
		arg.Name,
		arg.Type,
		arg.Subtype,
		arg.Mask,
		arg.Notes,
		arg.IsClosed,
		arg.IsHidden,
		arg.NeedsReview,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
