// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_balance_snapshots.sql

package dbgen

import (
	"context"
	"strings"
	"time"

	"tallyo/internal/money"
)

const accountBalanceSnapshotDayCount = `-- name: AccountBalanceSnapshotDayCount :one
SELECT CAST(COUNT(*) AS INTEGER) AS count
FROM account_balance_daily_snapshots
WHERE account_id = ?1
`

type AccountBalanceSnapshotDayCountParams struct {
	AccountID int64
}

// Used by GraphQL query accountSnapshots (wealth.graphql) to compute the total day count for pagination.
func (q *Queries) AccountBalanceSnapshotDayCount(ctx context.Context, arg AccountBalanceSnapshotDayCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountBalanceSnapshotDayCount, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const accountBalanceSnapshotTimestampRange = `-- name: AccountBalanceSnapshotTimestampRange :one
SELECT
  CAST(COALESCE(MIN(s.synced_at), '') AS TEXT) AS earliest_synced_at,
  CAST(COALESCE(MAX(CASE WHEN a.is_closed = 0 THEN s.synced_at END), '') AS TEXT) AS latest_synced_at
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE TRUE
  AND a.owner_id IN (/*SLICE:owner_ids*/?1) -- :if $1
  AND a.id IN (/*SLICE:account_ids*/?2) -- :if $2
  AND a.is_hidden = 0
`

var _accountBalanceSnapshotTimestampRangeDynQ = dynCompile(accountBalanceSnapshotTimestampRange)

type AccountBalanceSnapshotTimestampRangeParams struct {
	OwnerIds   []int64
	AccountIds []int64
}

type AccountBalanceSnapshotTimestampRangeRow struct {
	EarliestSyncedAt string
	LatestSyncedAt   string
}

// Used by GraphQL net-worth queries to determine historical range start and current report as-of date.
func (q *Queries) AccountBalanceSnapshotTimestampRange(ctx context.Context, arg AccountBalanceSnapshotTimestampRangeParams) (AccountBalanceSnapshotTimestampRangeRow, error) {

	dynQuery, dynArgs := _accountBalanceSnapshotTimestampRangeDynQ.Build([]any{arg.OwnerIds, arg.AccountIds})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var i AccountBalanceSnapshotTimestampRangeRow
	err := row.Scan(&i.EarliestSyncedAt, &i.LatestSyncedAt)
	return i, err
}

const accountBalanceSnapshotValues = `-- name: AccountBalanceSnapshotValues :many
SELECT
  s.account_id,
  a.type AS account_type,
  a.manual AS account_manual,
  a.subtype AS account_subtype,
  a.is_closed AS account_is_closed,
  s.synced_at,
  s.balance_usd_cents
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE TRUE
  AND a.owner_id IN (/*SLICE:owner_ids*/?1) -- :if $1
  AND a.id IN (/*SLICE:account_ids*/?2) -- :if $2
  AND s.synced_at >= ?3
  AND s.synced_at < ?4
  AND a.is_hidden = 0
ORDER BY s.account_id, s.synced_at
`

var _accountBalanceSnapshotValuesDynQ = dynCompile(accountBalanceSnapshotValues)

type AccountBalanceSnapshotValuesParams struct {
	OwnerIds   []int64
	AccountIds []int64
	StartTime  time.Time
	EndTime    time.Time
}

type AccountBalanceSnapshotValuesRow struct {
	AccountID       int64
	AccountType     string
	AccountManual   bool
	AccountSubtype  *string
	AccountIsClosed bool
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
}

// Used by internal/wealth's historical net-worth series to aggregate account balance values across a time range.
func (q *Queries) AccountBalanceSnapshotValues(ctx context.Context, arg AccountBalanceSnapshotValuesParams) ([]AccountBalanceSnapshotValuesRow, error) {

	dynQuery, dynArgs := _accountBalanceSnapshotValuesDynQ.Build([]any{arg.OwnerIds, arg.AccountIds, arg.StartTime, arg.EndTime})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceSnapshotValuesRow{}
	for rows.Next() {
		var i AccountBalanceSnapshotValuesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountType,
			&i.AccountManual,
			&i.AccountSubtype,
			&i.AccountIsClosed,
			&i.SyncedAt,
			&i.BalanceUsdCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountBalanceSnapshotsPage = `-- name: AccountBalanceSnapshotsPage :many
SELECT s.id, s.account_id, s.source, s.date, s.synced_at, s.balance_usd_cents, s.flagged, a.type AS account_type
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE TRUE
  AND s.date < ?1 -- :if $1
  AND s.account_id = ?2
ORDER BY s.date DESC
LIMIT ?3
`

var _accountBalanceSnapshotsPageDynQ = dynCompile(accountBalanceSnapshotsPage)

type AccountBalanceSnapshotsPageParams struct {
	AfterDate *string
	AccountID int64
	RowLimit  int64
}

type AccountBalanceSnapshotsPageRow struct {
	ID              int64
	AccountID       int64
	Source          string
	Date            string
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
	Flagged         bool
	AccountType     string
}

// Used by GraphQL query accountSnapshots (wealth.graphql) via internal/wealth's snapshot editor for cursor-paginated snapshot history.
func (q *Queries) AccountBalanceSnapshotsPage(ctx context.Context, arg AccountBalanceSnapshotsPageParams) ([]AccountBalanceSnapshotsPageRow, error) {

	dynQuery, dynArgs := _accountBalanceSnapshotsPageDynQ.Build([]any{arg.AfterDate, arg.AccountID, arg.RowLimit})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountBalanceSnapshotsPageRow{}
	for rows.Next() {
		var i AccountBalanceSnapshotsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Source,
			&i.Date,
			&i.SyncedAt,
			&i.BalanceUsdCents,
			&i.Flagged,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountIsClosed = `-- name: AccountIsClosed :one
SELECT is_closed
FROM accounts
WHERE id = ?1
`

type AccountIsClosedParams struct {
	ID int64
}

// Used by internal/wealth's shared snapshot sink to skip snapshot writes for closed accounts.
func (q *Queries) AccountIsClosed(ctx context.Context, arg AccountIsClosedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountIsClosed, arg.ID)
	var is_closed bool
	err := row.Scan(&is_closed)
	return is_closed, err
}

const classifierSnapshotValues = `-- name: ClassifierSnapshotValues :many
SELECT
  h.account_id,
  a.is_closed AS account_is_closed,
  s.synced_at,
  assets.classifier,
  CAST(SUM(h.value_usd_cents) AS INTEGER) AS value_usd_cents
FROM asset_daily_holdings h
JOIN account_balance_daily_snapshots s ON s.id = h.snapshot_id
JOIN accounts a ON a.id = h.account_id
JOIN assets ON assets.id = h.asset_id
WHERE TRUE
  AND a.owner_id IN (/*SLICE:owner_ids*/?1) -- :if $1
  AND a.id IN (/*SLICE:account_ids*/?2) -- :if $2
  AND s.synced_at >= ?3
  AND s.synced_at < ?4
  AND h.counts_toward_value = 1
  AND a.is_hidden = 0
GROUP BY h.account_id, a.is_closed, s.synced_at, assets.classifier
ORDER BY h.account_id, s.synced_at, assets.classifier
`

var _classifierSnapshotValuesDynQ = dynCompile(classifierSnapshotValues)

type ClassifierSnapshotValuesParams struct {
	OwnerIds   []int64
	AccountIds []int64
	StartTime  time.Time
	EndTime    time.Time
}

type ClassifierSnapshotValuesRow struct {
	AccountID       int64
	AccountIsClosed bool
	SyncedAt        time.Time
	Classifier      string
	ValueUsdCents   int64
}

// Used by GraphQL query historicalNetWorth (wealth.graphql) via internal/wealth's service to compute the asset classifier breakdown over time.
func (q *Queries) ClassifierSnapshotValues(ctx context.Context, arg ClassifierSnapshotValuesParams) ([]ClassifierSnapshotValuesRow, error) {

	dynQuery, dynArgs := _classifierSnapshotValuesDynQ.Build([]any{arg.OwnerIds, arg.AccountIds, arg.StartTime, arg.EndTime})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassifierSnapshotValuesRow{}
	for rows.Next() {
		var i ClassifierSnapshotValuesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountIsClosed,
			&i.SyncedAt,
			&i.Classifier,
			&i.ValueUsdCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAssetDailyHoldingsBySnapshotID = `-- name: DeleteAssetDailyHoldingsBySnapshotID :exec
DELETE FROM asset_daily_holdings
WHERE snapshot_id = ?1
`

type DeleteAssetDailyHoldingsBySnapshotIDParams struct {
	SnapshotID int64
}

// Used by internal/wealth to clean up holdings during balance-review approval and manual snapshot edits.
func (q *Queries) DeleteAssetDailyHoldingsBySnapshotID(ctx context.Context, arg DeleteAssetDailyHoldingsBySnapshotIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteAssetDailyHoldingsBySnapshotID, arg.SnapshotID)
	return err
}

const getAccountBalanceSnapshotByID = `-- name: GetAccountBalanceSnapshotByID :one
SELECT s.id, s.account_id, s.source, s.date, s.synced_at, s.balance_usd_cents, s.flagged, a.type AS account_type
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE s.id = ?1
`

type GetAccountBalanceSnapshotByIDParams struct {
	ID int64
}

type GetAccountBalanceSnapshotByIDRow struct {
	ID              int64
	AccountID       int64
	Source          string
	Date            string
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
	Flagged         bool
	AccountType     string
}

// Used by internal/wealth's manual snapshot editor (GraphQL mutation changeAccountSnapshot) to fetch a snapshot before editing it.
func (q *Queries) GetAccountBalanceSnapshotByID(ctx context.Context, arg GetAccountBalanceSnapshotByIDParams) (GetAccountBalanceSnapshotByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalanceSnapshotByID, arg.ID)
	var i GetAccountBalanceSnapshotByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.Date,
		&i.SyncedAt,
		&i.BalanceUsdCents,
		&i.Flagged,
		&i.AccountType,
	)
	return i, err
}

const hasFlaggedSnapshotForAccountBetweenDates = `-- name: HasFlaggedSnapshotForAccountBetweenDates :one
SELECT CAST(EXISTS(
  SELECT 1
  FROM account_balance_daily_snapshots
  WHERE account_id = ?1
    AND flagged = 1
    AND date >= ?2
    AND date <= ?3
) AS INTEGER) AS has_flagged_snapshot
`

type HasFlaggedSnapshotForAccountBetweenDatesParams struct {
	AccountID int64
	StartDate string
	EndDate   string
}

// Used by internal/wealth's balance-review approval flow to verify the review still has flagged snapshots.
func (q *Queries) HasFlaggedSnapshotForAccountBetweenDates(ctx context.Context, arg HasFlaggedSnapshotForAccountBetweenDatesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasFlaggedSnapshotForAccountBetweenDates, arg.AccountID, arg.StartDate, arg.EndDate)
	var has_flagged_snapshot int64
	err := row.Scan(&has_flagged_snapshot)
	return has_flagged_snapshot, err
}

const insertAccountBalanceSnapshot = `-- name: InsertAccountBalanceSnapshot :one
INSERT OR REPLACE INTO account_balance_daily_snapshots (account_id, source, date, synced_at, balance_usd_cents, raw_payload, flagged, flag_reason)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id
`

type InsertAccountBalanceSnapshotParams struct {
	AccountID       int64
	Source          string
	Date            string
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
	RawPayload      *string
	Flagged         bool
	FlagReason      *string
}

// Used by internal/wealth's shared snapshot sink (ReplaceAccountBalanceSnapshot) to replace a daily balance row for any adapter (Plaid, SimpleFIN, DeBank, Yahoo Finance, real estate, manual).
func (q *Queries) InsertAccountBalanceSnapshot(ctx context.Context, arg InsertAccountBalanceSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAccountBalanceSnapshot,
		arg.AccountID,
		arg.Source,
		arg.Date,
		arg.SyncedAt,
		arg.BalanceUsdCents,
		arg.RawPayload,
		arg.Flagged,
		arg.FlagReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAssetDailyHolding = `-- name: InsertAssetDailyHolding :exec
INSERT INTO asset_daily_holdings (snapshot_id, account_id, date, asset_id, quantity, price, value_usd_cents, counts_toward_value, manual)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
ON CONFLICT(account_id, date, asset_id) DO UPDATE SET
  value_usd_cents = asset_daily_holdings.value_usd_cents + excluded.value_usd_cents,
  quantity = CASE
    WHEN asset_daily_holdings.quantity IS NULL OR excluded.quantity IS NULL THEN NULL
    ELSE asset_daily_holdings.quantity + excluded.quantity
  END,
  price = COALESCE(excluded.price, asset_daily_holdings.price),
  counts_toward_value = asset_daily_holdings.counts_toward_value OR excluded.counts_toward_value,
  manual = asset_daily_holdings.manual OR excluded.manual
`

type InsertAssetDailyHoldingParams struct {
	SnapshotID        int64
	AccountID         int64
	Date              string
	AssetID           int64
	Quantity          *float64
	Price             *float64
	ValueUsdCents     money.Cents
	CountsTowardValue bool
	Manual            bool
}

// Used by internal/wealth's shared snapshot sink (ReplaceAccountBalanceSnapshot) to insert each asset holding row for a balance snapshot.
// Multiple provider holdings can resolve to the same asset within one snapshot
// (e.g. a wallet balance and a DeFi-project position on the same token). Fold
// duplicates into a single row by summing value/quantity so the holding total
// stays consistent with the snapshot balance, instead of failing the whole
// transaction on the (account_id, date, asset_id) unique index.
func (q *Queries) InsertAssetDailyHolding(ctx context.Context, arg InsertAssetDailyHoldingParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetDailyHolding,
		arg.SnapshotID,
		arg.AccountID,
		arg.Date,
		arg.AssetID,
		arg.Quantity,
		arg.Price,
		arg.ValueUsdCents,
		arg.CountsTowardValue,
		arg.Manual,
	)
	return err
}

const latestAccountBalanceSnapshotInWindow = `-- name: LatestAccountBalanceSnapshotInWindow :one
SELECT s.id, s.account_id, s.source, s.date, s.synced_at, s.balance_usd_cents, s.flagged, a.type AS account_type
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE TRUE
  AND (s.synced_at >= ?1 AND s.synced_at < ?2) -- :if $1 -- :if $2
  AND s.account_id = ?3
ORDER BY s.date DESC, s.id DESC
LIMIT 1
`

var _latestAccountBalanceSnapshotInWindowDynQ = dynCompile(latestAccountBalanceSnapshotInWindow)

type LatestAccountBalanceSnapshotInWindowParams struct {
	StartTime *time.Time
	EndTime   *time.Time
	AccountID int64
}

type LatestAccountBalanceSnapshotInWindowRow struct {
	ID              int64
	AccountID       int64
	Source          string
	Date            string
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
	Flagged         bool
	AccountType     string
}

// Used by internal/wealth's snapshot editor and the manual/real-estate adapters to fetch the latest snapshot, optionally scoped to a sync-time window.
func (q *Queries) LatestAccountBalanceSnapshotInWindow(ctx context.Context, arg LatestAccountBalanceSnapshotInWindowParams) (LatestAccountBalanceSnapshotInWindowRow, error) {

	dynQuery, dynArgs := _latestAccountBalanceSnapshotInWindowDynQ.Build([]any{arg.StartTime, arg.EndTime, arg.AccountID})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var i LatestAccountBalanceSnapshotInWindowRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.Date,
		&i.SyncedAt,
		&i.BalanceUsdCents,
		&i.Flagged,
		&i.AccountType,
	)
	return i, err
}

const latestAccountBalanceSnapshotsForAccounts = `-- name: LatestAccountBalanceSnapshotsForAccounts :many
SELECT
  s.id,
  s.account_id,
  s.source,
  s.date,
  s.synced_at,
  s.balance_usd_cents,
  s.flagged,
  a.type AS account_type
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE s.account_id IN (/*SLICE:account_ids*/?)
  AND s.date = (
    SELECT MAX(s2.date)
    FROM account_balance_daily_snapshots s2
    WHERE s2.account_id = s.account_id
  )
`

type LatestAccountBalanceSnapshotsForAccountsParams struct {
	AccountIds []int64
}

type LatestAccountBalanceSnapshotsForAccountsRow struct {
	ID              int64
	AccountID       int64
	Source          string
	Date            string
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
	Flagged         bool
	AccountType     string
}

// Used by internal/wealth to batch-load each account's latest snapshot for the Account.latestSnapshot GraphQL field.
func (q *Queries) LatestAccountBalanceSnapshotsForAccounts(ctx context.Context, arg LatestAccountBalanceSnapshotsForAccountsParams) ([]LatestAccountBalanceSnapshotsForAccountsRow, error) {
	query := latestAccountBalanceSnapshotsForAccounts
	var queryParams []interface{}
	if len(arg.AccountIds) > 0 {
		for _, v := range arg.AccountIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:account_ids*/?", strings.Repeat(",?", len(arg.AccountIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:account_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestAccountBalanceSnapshotsForAccountsRow{}
	for rows.Next() {
		var i LatestAccountBalanceSnapshotsForAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Source,
			&i.Date,
			&i.SyncedAt,
			&i.BalanceUsdCents,
			&i.Flagged,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestUnflaggedSnapshotHoldings = `-- name: LatestUnflaggedSnapshotHoldings :many
WITH latest AS (
  SELECT s0.id, s0.source, s0.date, s0.balance_usd_cents
  FROM account_balance_daily_snapshots s0
  WHERE s0.account_id = ?1
    AND s0.date < ?2
    AND s0.flagged = 0
  ORDER BY s0.date DESC
  LIMIT 1
)
SELECT latest.date,
       latest.balance_usd_cents,
       h.asset_id AS asset_id,
       a.identifier,
       aas.source_adapter,
       aas.source_id,
       h.quantity, h.price,
       COALESCE(h.value_usd_cents, 0) AS value_usd_cents,
       COALESCE(h.counts_toward_value, 0) AS counts_toward_value,
       COALESCE(h.manual, 0) AS manual
FROM latest
LEFT JOIN asset_daily_holdings h ON h.snapshot_id = latest.id
LEFT JOIN assets a ON a.id = h.asset_id
LEFT JOIN asset_adapter_sources aas ON aas.asset_id = h.asset_id
  AND aas.source_adapter = latest.source
ORDER BY h.value_usd_cents DESC
`

type LatestUnflaggedSnapshotHoldingsParams struct {
	AccountID int64
	Date      string
}

type LatestUnflaggedSnapshotHoldingsRow struct {
	Date              string
	BalanceUsdCents   int64
	AssetID           *int64
	Identifier        *string
	SourceAdapter     *string
	SourceID          *string
	Quantity          *float64
	Price             *float64
	ValueUsdCents     money.Cents
	CountsTowardValue bool
	Manual            bool
}

// Used by internal/wealth's flagging flow to find the prior unflagged snapshot and holdings as a carry-forward anchor when a new snapshot looks anomalous.
func (q *Queries) LatestUnflaggedSnapshotHoldings(ctx context.Context, arg LatestUnflaggedSnapshotHoldingsParams) ([]LatestUnflaggedSnapshotHoldingsRow, error) {
	rows, err := q.db.QueryContext(ctx, latestUnflaggedSnapshotHoldings, arg.AccountID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestUnflaggedSnapshotHoldingsRow{}
	for rows.Next() {
		var i LatestUnflaggedSnapshotHoldingsRow
		if err := rows.Scan(
			&i.Date,
			&i.BalanceUsdCents,
			&i.AssetID,
			&i.Identifier,
			&i.SourceAdapter,
			&i.SourceID,
			&i.Quantity,
			&i.Price,
			&i.ValueUsdCents,
			&i.CountsTowardValue,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentAccountHoldings = `-- name: ListCurrentAccountHoldings :many
SELECT
  a.connection_id, a.created_at, a.external_id, a.id, a.is_closed, a.is_hidden, a.manual, a.mask, a.name, a.needs_review, a.notes, a.owner_id, a.review_reason, a.subtype, a.type, a.updated_at,
  o.name AS owner_name,
  assets.additional, assets.asset_type, assets.classifier, assets.created_at, assets.forced_usd_price, assets.id, assets.identifier, assets.investment_connectivity, assets.last_price, assets.last_price_at, assets.name, assets.price_connectivity, assets.tracking_multiplier, assets.tracking_ticker, assets.updated_at, assets.user_created, assets.user_edited,
  h.quantity,
  h.value_usd_cents,
  h.manual,
  s.date
FROM accounts a
JOIN owners o ON o.id = a.owner_id
JOIN account_balance_daily_snapshots s ON s.account_id = a.id
  AND s.date = (
    SELECT MAX(s2.date)
    FROM account_balance_daily_snapshots s2
    WHERE s2.account_id = a.id
  )
JOIN asset_daily_holdings h ON h.snapshot_id = s.id
JOIN assets ON assets.id = h.asset_id
LEFT JOIN asset_analysis_reports r ON r.asset_id = assets.id -- :if $6
WHERE TRUE
  AND a.type NOT IN ('CREDIT', 'LOAN') -- :if $7
  AND a.owner_id IN (/*SLICE:owner_ids*/?1) -- :if $1
  AND a.id IN (/*SLICE:account_ids*/?2) -- :if $2
  AND a.subtype IN (/*SLICE:account_subtypes*/?3) -- :if $3
  AND assets.classifier = ?4 -- :if $4
  AND r.asset_id IS NOT NULL -- :if $6
  AND assets.id IN (/*SLICE:asset_ids*/?5) -- :if $5
  AND a.is_hidden = 0
  AND a.is_closed = 0
  AND h.counts_toward_value = 1
ORDER BY a.name, h.value_usd_cents DESC
`

var _listCurrentAccountHoldingsDynQ = dynCompile(listCurrentAccountHoldings)

type ListCurrentAccountHoldingsParams struct {
	OwnerIds           []int64
	AccountIds         []int64
	AccountSubtypes    []*string
	Classifier         *string
	AssetIds           []int64
	ClassifiedOnly     bool
	ExcludeLiabilities bool
}

type ListCurrentAccountHoldingsRow struct {
	Account       Account
	OwnerName     string
	Asset         Asset
	Quantity      *float64
	ValueUsdCents money.Cents
	Manual        bool
	Date          string
}

// Closed accounts are filtered here because this current-holdings query has no date predicate; otherwise a closed account's last row would remain current forever.
func (q *Queries) ListCurrentAccountHoldings(ctx context.Context, arg ListCurrentAccountHoldingsParams) ([]ListCurrentAccountHoldingsRow, error) {

	dynQuery, dynArgs := _listCurrentAccountHoldingsDynQ.Build([]any{arg.OwnerIds, arg.AccountIds, arg.AccountSubtypes, arg.Classifier, arg.AssetIds, arg.ClassifiedOnly, arg.ExcludeLiabilities})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentAccountHoldingsRow{}
	for rows.Next() {
		var i ListCurrentAccountHoldingsRow
		if err := rows.Scan(
			&i.Account.ConnectionID,
			&i.Account.CreatedAt,
			&i.Account.ExternalID,
			&i.Account.ID,
			&i.Account.IsClosed,
			&i.Account.IsHidden,
			&i.Account.Manual,
			&i.Account.Mask,
			&i.Account.Name,
			&i.Account.NeedsReview,
			&i.Account.Notes,
			&i.Account.OwnerID,
			&i.Account.ReviewReason,
			&i.Account.Subtype,
			&i.Account.Type,
			&i.Account.UpdatedAt,
			&i.OwnerName,
			&i.Asset.Additional,
			&i.Asset.AssetType,
			&i.Asset.Classifier,
			&i.Asset.CreatedAt,
			&i.Asset.ForcedUsdPrice,
			&i.Asset.ID,
			&i.Asset.Identifier,
			&i.Asset.InvestmentConnectivity,
			&i.Asset.LastPrice,
			&i.Asset.LastPriceAt,
			&i.Asset.Name,
			&i.Asset.PriceConnectivity,
			&i.Asset.TrackingMultiplier,
			&i.Asset.TrackingTicker,
			&i.Asset.UpdatedAt,
			&i.Asset.UserCreated,
			&i.Asset.UserEdited,
			&i.Quantity,
			&i.ValueUsdCents,
			&i.Manual,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestLiabilityAccountBalances = `-- name: ListLatestLiabilityAccountBalances :many
SELECT
  a.connection_id, a.created_at, a.external_id, a.id, a.is_closed, a.is_hidden, a.manual, a.mask, a.name, a.needs_review, a.notes, a.owner_id, a.review_reason, a.subtype, a.type, a.updated_at,
  o.name AS owner_name,
  s.balance_usd_cents
FROM accounts a
JOIN owners o ON o.id = a.owner_id
JOIN account_balance_daily_snapshots s ON s.account_id = a.id
  AND s.date = (
    SELECT MAX(s2.date)
    FROM account_balance_daily_snapshots s2
    WHERE s2.account_id = a.id
  )
WHERE TRUE
  AND a.owner_id IN (/*SLICE:owner_ids*/?1) -- :if $1
  AND a.id IN (/*SLICE:account_ids*/?2) -- :if $2
  AND a.is_hidden = 0
  AND a.is_closed = 0
  AND a.type IN ('CREDIT', 'LOAN')
ORDER BY a.name
`

var _listLatestLiabilityAccountBalancesDynQ = dynCompile(listLatestLiabilityAccountBalances)

type ListLatestLiabilityAccountBalancesParams struct {
	OwnerIds   []int64
	AccountIds []int64
}

type ListLatestLiabilityAccountBalancesRow struct {
	Account         Account
	OwnerName       string
	BalanceUsdCents money.Cents
}

// Used by GraphQL query netWorth (wealth.graphql) via internal/wealth's service to fetch each open liability account's latest balance for the net-worth calculation.
// Closed accounts are filtered here because this current-net-worth query has no date predicate; otherwise a closed account's last row would remain current forever.
func (q *Queries) ListLatestLiabilityAccountBalances(ctx context.Context, arg ListLatestLiabilityAccountBalancesParams) ([]ListLatestLiabilityAccountBalancesRow, error) {

	dynQuery, dynArgs := _listLatestLiabilityAccountBalancesDynQ.Build([]any{arg.OwnerIds, arg.AccountIds})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestLiabilityAccountBalancesRow{}
	for rows.Next() {
		var i ListLatestLiabilityAccountBalancesRow
		if err := rows.Scan(
			&i.Account.ConnectionID,
			&i.Account.CreatedAt,
			&i.Account.ExternalID,
			&i.Account.ID,
			&i.Account.IsClosed,
			&i.Account.IsHidden,
			&i.Account.Manual,
			&i.Account.Mask,
			&i.Account.Name,
			&i.Account.NeedsReview,
			&i.Account.Notes,
			&i.Account.OwnerID,
			&i.Account.ReviewReason,
			&i.Account.Subtype,
			&i.Account.Type,
			&i.Account.UpdatedAt,
			&i.OwnerName,
			&i.BalanceUsdCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const manualSnapshotAccountIDs = `-- name: ManualSnapshotAccountIDs :many
SELECT id
FROM accounts
WHERE manual = 1
  AND is_closed = 0
ORDER BY id
`

// Used by internal/wealth/manual to discover open manual accounts for periodic carry-forward.
func (q *Queries) ManualSnapshotAccountIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, manualSnapshotAccountIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newerAccountBalanceSnapshotsForAccount = `-- name: NewerAccountBalanceSnapshotsForAccount :many
SELECT s.id, s.account_id, s.source, s.date, s.synced_at, s.balance_usd_cents, s.flagged, a.type AS account_type
FROM account_balance_daily_snapshots s
JOIN accounts a ON a.id = s.account_id
WHERE s.account_id = ?1
  AND s.date > ?2
ORDER BY s.date, s.id
`

type NewerAccountBalanceSnapshotsForAccountParams struct {
	AccountID int64
	Date      string
}

type NewerAccountBalanceSnapshotsForAccountRow struct {
	ID              int64
	AccountID       int64
	Source          string
	Date            string
	SyncedAt        time.Time
	BalanceUsdCents money.Cents
	Flagged         bool
	AccountType     string
}

// Used by internal/wealth's snapshot editor to find snapshots newer than an edited date, so later balances can be reconciled.
func (q *Queries) NewerAccountBalanceSnapshotsForAccount(ctx context.Context, arg NewerAccountBalanceSnapshotsForAccountParams) ([]NewerAccountBalanceSnapshotsForAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, newerAccountBalanceSnapshotsForAccount, arg.AccountID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewerAccountBalanceSnapshotsForAccountRow{}
	for rows.Next() {
		var i NewerAccountBalanceSnapshotsForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Source,
			&i.Date,
			&i.SyncedAt,
			&i.BalanceUsdCents,
			&i.Flagged,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotHoldingsBySnapshotIDs = `-- name: SnapshotHoldingsBySnapshotIDs :many
SELECT
  h.snapshot_id,
  assets.additional, assets.asset_type, assets.classifier, assets.created_at, assets.forced_usd_price, assets.id, assets.identifier, assets.investment_connectivity, assets.last_price, assets.last_price_at, assets.name, assets.price_connectivity, assets.tracking_multiplier, assets.tracking_ticker, assets.updated_at, assets.user_created, assets.user_edited,
  h.quantity,
  h.price,
  h.value_usd_cents,
  h.counts_toward_value,
  h.manual
FROM asset_daily_holdings h
JOIN assets ON assets.id = h.asset_id
WHERE h.snapshot_id IN (/*SLICE:snapshot_ids*/?)
ORDER BY h.snapshot_id, h.value_usd_cents DESC
`

type SnapshotHoldingsBySnapshotIDsParams struct {
	SnapshotIds []int64
}

type SnapshotHoldingsBySnapshotIDsRow struct {
	SnapshotID        int64
	Asset             Asset
	Quantity          *float64
	Price             *float64
	ValueUsdCents     money.Cents
	CountsTowardValue bool
	Manual            bool
}

// Used by internal/wealth to load holdings for one or more snapshots, including the AccountSnapshot.holdings GraphQL field's dataloader.
func (q *Queries) SnapshotHoldingsBySnapshotIDs(ctx context.Context, arg SnapshotHoldingsBySnapshotIDsParams) ([]SnapshotHoldingsBySnapshotIDsRow, error) {
	query := snapshotHoldingsBySnapshotIDs
	var queryParams []interface{}
	if len(arg.SnapshotIds) > 0 {
		for _, v := range arg.SnapshotIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:snapshot_ids*/?", strings.Repeat(",?", len(arg.SnapshotIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:snapshot_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SnapshotHoldingsBySnapshotIDsRow{}
	for rows.Next() {
		var i SnapshotHoldingsBySnapshotIDsRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.Asset.Additional,
			&i.Asset.AssetType,
			&i.Asset.Classifier,
			&i.Asset.CreatedAt,
			&i.Asset.ForcedUsdPrice,
			&i.Asset.ID,
			&i.Asset.Identifier,
			&i.Asset.InvestmentConnectivity,
			&i.Asset.LastPrice,
			&i.Asset.LastPriceAt,
			&i.Asset.Name,
			&i.Asset.PriceConnectivity,
			&i.Asset.TrackingMultiplier,
			&i.Asset.TrackingTicker,
			&i.Asset.UpdatedAt,
			&i.Asset.UserCreated,
			&i.Asset.UserEdited,
			&i.Quantity,
			&i.Price,
			&i.ValueUsdCents,
			&i.CountsTowardValue,
			&i.Manual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unflagSnapshotsBetweenDates = `-- name: UnflagSnapshotsBetweenDates :exec
UPDATE account_balance_daily_snapshots
SET flagged = 0, flag_reason = NULL
WHERE account_id = ?1
  AND date >= CASE WHEN CAST(?2 AS BOOLEAN) = 1 THEN ?3 ELSE date(?3, '+1 day') END
  AND date <= CASE WHEN CAST(?2 AS BOOLEAN) = 1 THEN ?4 ELSE date(?4, '-1 day') END
  AND flagged = 1
`

type UnflagSnapshotsBetweenDatesParams struct {
	AccountID  int64
	Inclusive  bool
	AfterDate  string
	BeforeDate string
}

// Used by internal/wealth's persister and review approval flow to unflag previously-flagged snapshots.
func (q *Queries) UnflagSnapshotsBetweenDates(ctx context.Context, arg UnflagSnapshotsBetweenDatesParams) error {
	_, err := q.db.ExecContext(ctx, unflagSnapshotsBetweenDates,
		arg.AccountID,
		arg.Inclusive,
		arg.AfterDate,
		arg.BeforeDate,
	)
	return err
}

const updateSnapshotBalanceAndUnflag = `-- name: UpdateSnapshotBalanceAndUnflag :exec
UPDATE account_balance_daily_snapshots
SET balance_usd_cents = ?1,
    flagged = 0,
    flag_reason = NULL
WHERE id = ?2
`

type UpdateSnapshotBalanceAndUnflagParams struct {
	BalanceUsdCents money.Cents
	ID              int64
}

// Used by internal/wealth's balance-review approval flow and manual snapshot editor to restore the provider-reported balance and clear the flag.
func (q *Queries) UpdateSnapshotBalanceAndUnflag(ctx context.Context, arg UpdateSnapshotBalanceAndUnflagParams) error {
	_, err := q.db.ExecContext(ctx, updateSnapshotBalanceAndUnflag, arg.BalanceUsdCents, arg.ID)
	return err
}
