// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"
	"strings"
	"time"
)

const assetAdapterSourceAssetID = `-- name: AssetAdapterSourceAssetID :one
SELECT asset_id
FROM asset_adapter_sources
WHERE source_adapter = ?1
  AND source_id = ?2
`

type AssetAdapterSourceAssetIDParams struct {
	SourceAdapter string
	SourceID      string
}

// Used by wealth/db.Store.UpsertAsset to identify an existing asset by its externally-discovered provider ID (asset_adapter_sources), and by MergeAsset to look up adapter sources during a merge.
func (q *Queries) AssetAdapterSourceAssetID(ctx context.Context, arg AssetAdapterSourceAssetIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, assetAdapterSourceAssetID, arg.SourceAdapter, arg.SourceID)
	var asset_id int64
	err := row.Scan(&asset_id)
	return asset_id, err
}

const assetAdapterSourcesByAssetIDs = `-- name: AssetAdapterSourcesByAssetIDs :many
SELECT asset_id, source_adapter, source_id
FROM asset_adapter_sources
WHERE asset_id IN (/*SLICE:asset_ids*/?)
ORDER BY source_adapter, source_id
`

type AssetAdapterSourcesByAssetIDsParams struct {
	AssetIds []int64
}

type AssetAdapterSourcesByAssetIDsRow struct {
	AssetID       int64
	SourceAdapter string
	SourceID      string
}

// Used by the Asset.adapterSources GraphQL field's dataloader (internal/graph/loaders.go) to batch-load provider sources per asset.
func (q *Queries) AssetAdapterSourcesByAssetIDs(ctx context.Context, arg AssetAdapterSourcesByAssetIDsParams) ([]AssetAdapterSourcesByAssetIDsRow, error) {
	query := assetAdapterSourcesByAssetIDs
	var queryParams []interface{}
	if len(arg.AssetIds) > 0 {
		for _, v := range arg.AssetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(arg.AssetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetAdapterSourcesByAssetIDsRow{}
	for rows.Next() {
		var i AssetAdapterSourcesByAssetIDsRow
		if err := rows.Scan(&i.AssetID, &i.SourceAdapter, &i.SourceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assetMergeCollisionExists = `-- name: AssetMergeCollisionExists :one
SELECT EXISTS(
  SELECT 1
  FROM asset_daily_holdings duplicate
  JOIN asset_daily_holdings target ON target.snapshot_id = duplicate.snapshot_id
  WHERE duplicate.asset_id = ?1
    AND target.asset_id = ?2
  UNION ALL
  SELECT 1
  FROM asset_daily_holdings duplicate
  JOIN asset_daily_holdings target ON target.account_id = duplicate.account_id
    AND target.date = duplicate.date
  WHERE duplicate.asset_id = ?1
    AND target.asset_id = ?2
) AS has_collision
`

type AssetMergeCollisionExistsParams struct {
	DuplicateAssetID int64
	TargetAssetID    int64
}

// Used by GraphQL mutation mergeAsset to detect a holding collision (same snapshot or same account+date) before merging two assets.
func (q *Queries) AssetMergeCollisionExists(ctx context.Context, arg AssetMergeCollisionExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, assetMergeCollisionExists, arg.DuplicateAssetID, arg.TargetAssetID)
	var has_collision bool
	err := row.Scan(&has_collision)
	return has_collision, err
}

const assetRecords = `-- name: AssetRecords :many
WITH latest_holdings AS (
  SELECT h.asset_id
  FROM asset_daily_holdings h
  JOIN account_balance_daily_snapshots s ON s.id = h.snapshot_id
  JOIN accounts ha ON ha.id = h.account_id
  WHERE ha.is_hidden = 0
    AND ha.is_closed = 0
    AND h.counts_toward_value = 1
    AND s.date = (SELECT MAX(s2.date) FROM account_balance_daily_snapshots s2 WHERE s2.account_id = s.account_id)
  GROUP BY h.asset_id
)
SELECT a.additional, a.asset_type, a.classifier, a.created_at, a.forced_usd_price, a.id, a.identifier, a.investment_connectivity, a.last_price, a.last_price_at, a.name, a.price_connectivity, a.tracking_multiplier, a.tracking_ticker, a.updated_at, a.user_created, a.user_edited
FROM assets a
LEFT JOIN latest_holdings lh ON lh.asset_id = a.id
JOIN assets_fts ON assets_fts.rowid = a.id AND assets_fts MATCH ?1 -- :if $1
WHERE TRUE
  AND (lh.asset_id IS NOT NULL OR a.user_created = 1) -- :if $7
  AND a.asset_type = ?2 -- :if $2
  AND a.price_connectivity = ?3 -- :if $3
  AND a.investment_connectivity = ?4 -- :if $4
  AND (instr(lower(coalesce(a.name, '')), ?5) > 0 OR instr(lower(a.identifier), ?6) > 0) -- :if $8
ORDER BY
  bm25(assets_fts) ASC, -- :if $9
  lower(coalesce(a.name, '')) ASC, -- :if $10
  a.identifier ASC, -- :if $10
  -- Trailing unconditional tiebreaker: the dynamic-filter plugin drops the
  -- ":if" annotation on a query's final physical ORDER BY/WHERE line, so a
  -- real (harmless, always-applied) clause has to be last. Also gives the
  -- name-ordered branch a stable sort.
  a.id ASC
`

var _assetRecordsDynQ = dynCompile(assetRecords)

type AssetRecordsParams struct {
	FtsMatch               *string
	AssetType              *string
	PriceConnectivity      *string
	InvestmentConnectivity *string
	LikeName               string
	LikeIdentifier         string
	ExcludeHistorical      bool
	LikeSearch             bool
	OrderFtsRank           bool
	OrderName              bool
}

type AssetRecordsRow struct {
	Asset Asset
}

// Used by GraphQL query assets (wealth/db.Store.AllAssets).
func (q *Queries) AssetRecords(ctx context.Context, arg AssetRecordsParams) ([]AssetRecordsRow, error) {

	dynQuery, dynArgs := _assetRecordsDynQ.Build([]any{arg.FtsMatch, arg.AssetType, arg.PriceConnectivity, arg.InvestmentConnectivity, arg.LikeName, arg.LikeIdentifier, arg.ExcludeHistorical, arg.LikeSearch, arg.OrderFtsRank, arg.OrderName})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetRecordsRow{}
	for rows.Next() {
		var i AssetRecordsRow
		if err := rows.Scan(
			&i.Asset.Additional,
			&i.Asset.AssetType,
			&i.Asset.Classifier,
			&i.Asset.CreatedAt,
			&i.Asset.ForcedUsdPrice,
			&i.Asset.ID,
			&i.Asset.Identifier,
			&i.Asset.InvestmentConnectivity,
			&i.Asset.LastPrice,
			&i.Asset.LastPriceAt,
			&i.Asset.Name,
			&i.Asset.PriceConnectivity,
			&i.Asset.TrackingMultiplier,
			&i.Asset.TrackingTicker,
			&i.Asset.UpdatedAt,
			&i.Asset.UserCreated,
			&i.Asset.UserEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assets = `-- name: Assets :many
SELECT a.additional, a.asset_type, a.classifier, a.created_at, a.forced_usd_price, a.id, a.identifier, a.investment_connectivity, a.last_price, a.last_price_at, a.name, a.price_connectivity, a.tracking_multiplier, a.tracking_ticker, a.updated_at, a.user_created, a.user_edited
FROM assets a
WHERE TRUE
  AND a.id = ?1 -- :if $1
  AND a.id IN (/*SLICE:ids*/?2) -- :if $2
  AND a.asset_type = ?3 -- :if $3
  AND a.identifier = ?4 -- :if $4
  AND TRUE
`

var _assetsDynQ = dynCompile(assets)

type AssetsParams struct {
	ID         *int64
	Ids        []int64
	AssetType  *string
	Identifier *string
}

type AssetsRow struct {
	Asset Asset
}

// Used by wealth/db.Store to fetch asset rows by ID, IDs, type+identifier, or filter for updateAsset and other asset lookups.
func (q *Queries) Assets(ctx context.Context, arg AssetsParams) ([]AssetsRow, error) {

	dynQuery, dynArgs := _assetsDynQ.Build([]any{arg.ID, arg.Ids, arg.AssetType, arg.Identifier})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetsRow{}
	for rows.Next() {
		var i AssetsRow
		if err := rows.Scan(
			&i.Asset.Additional,
			&i.Asset.AssetType,
			&i.Asset.Classifier,
			&i.Asset.CreatedAt,
			&i.Asset.ForcedUsdPrice,
			&i.Asset.ID,
			&i.Asset.Identifier,
			&i.Asset.InvestmentConnectivity,
			&i.Asset.LastPrice,
			&i.Asset.LastPriceAt,
			&i.Asset.Name,
			&i.Asset.PriceConnectivity,
			&i.Asset.TrackingMultiplier,
			&i.Asset.TrackingTicker,
			&i.Asset.UpdatedAt,
			&i.Asset.UserCreated,
			&i.Asset.UserEdited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAssetAnalysisReportByAssetID = `-- name: DeleteAssetAnalysisReportByAssetID :exec
DELETE FROM asset_analysis_reports
WHERE asset_id = ?1
`

type DeleteAssetAnalysisReportByAssetIDParams struct {
	AssetID int64
}

// Used by wealth/db.Store.UpdateAsset to invalidate a stale portfolio analysis report when a user edit changes the asset's effective portfolio ticker (identifier or tracking ticker).
func (q *Queries) DeleteAssetAnalysisReportByAssetID(ctx context.Context, arg DeleteAssetAnalysisReportByAssetIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteAssetAnalysisReportByAssetID, arg.AssetID)
	return err
}

const deleteAssetByID = `-- name: DeleteAssetByID :exec
DELETE FROM assets
WHERE id = ?1
`

type DeleteAssetByIDParams struct {
	ID int64
}

// Used by GraphQL mutation mergeAsset to delete the duplicate asset once its holdings and metadata have been moved to the target.
func (q *Queries) DeleteAssetByID(ctx context.Context, arg DeleteAssetByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteAssetByID, arg.ID)
	return err
}

const deleteUnreferencedAssets = `-- name: DeleteUnreferencedAssets :execrows
DELETE FROM assets
WHERE user_edited = 0
  AND asset_type <> 'CURRENCY'
  AND NOT EXISTS (
    SELECT 1
    FROM asset_daily_holdings h
    WHERE h.asset_id = assets.id
  )
  AND NOT EXISTS (
    SELECT 1
    FROM asset_analysis_reports r
    WHERE r.asset_id = assets.id
  )
`

// Used by wealth's SweepUnreferencedAssets (run after balance syncs) to garbage-collect provider-discovered asset rows with no holdings or analysis.
// Garbage-collect catalog rows that nothing references and the user never
// edited. Type-agnostic: any asset with no daily holding (current or
// historical) and no analysis report is junk left behind by a provider sync.
// Held, manually tracked, analyzed, and user-edited assets are preserved.
// CURRENCY assets (the seeded USD denomination every cash balance references)
// are reference data, not sync-discovered holdings, and are never swept even
// when unreferenced.
func (q *Queries) DeleteUnreferencedAssets(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUnreferencedAssets)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAssetAdapterSource = `-- name: InsertAssetAdapterSource :exec
INSERT INTO asset_adapter_sources (asset_id, source_adapter, source_id)
VALUES (?1, ?2, ?3)
ON CONFLICT(source_adapter, source_id) DO NOTHING
`

type InsertAssetAdapterSourceParams struct {
	AssetID       int64
	SourceAdapter string
	SourceID      string
}

// Used by wealth/db.Store.UpsertAsset to associate an externally-discovered provider ID (Plaid, SimpleFIN, DeBank) with an internal asset row.
func (q *Queries) InsertAssetAdapterSource(ctx context.Context, arg InsertAssetAdapterSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetAdapterSource, arg.AssetID, arg.SourceAdapter, arg.SourceID)
	return err
}

const latestSnapshotIDsForAsset = `-- name: LatestSnapshotIDsForAsset :many
SELECT h.snapshot_id
FROM asset_daily_holdings h
JOIN account_balance_daily_snapshots s ON s.id = h.snapshot_id
JOIN accounts a ON a.id = s.account_id
WHERE h.asset_id = CAST(?1 AS INTEGER)
  AND a.is_closed = 0
  AND s.date = (
    SELECT MAX(s2.date)
    FROM account_balance_daily_snapshots s2
    WHERE s2.account_id = s.account_id
  )
`

type LatestSnapshotIDsForAssetParams struct {
	AssetID int64
}

// Used by wealth/db.Store's asset price-update path to find the current snapshot rows affected by an asset price change.
func (q *Queries) LatestSnapshotIDsForAsset(ctx context.Context, arg LatestSnapshotIDsForAssetParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, latestSnapshotIDsForAsset, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var snapshot_id int64
		if err := rows.Scan(&snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveAssetAdapterSources = `-- name: MoveAssetAdapterSources :exec
UPDATE asset_adapter_sources
SET asset_id = ?1
WHERE asset_id = ?2
`

type MoveAssetAdapterSourcesParams struct {
	TargetAssetID    int64
	DuplicateAssetID int64
}

// Used by GraphQL mutation mergeAsset to reassign external provider associations from the duplicate asset to the target asset.
func (q *Queries) MoveAssetAdapterSources(ctx context.Context, arg MoveAssetAdapterSourcesParams) error {
	_, err := q.db.ExecContext(ctx, moveAssetAdapterSources, arg.TargetAssetID, arg.DuplicateAssetID)
	return err
}

const moveAssetAnalysisReport = `-- name: MoveAssetAnalysisReport :exec
UPDATE OR IGNORE asset_analysis_reports
SET asset_id = ?1
WHERE asset_id = ?2
`

type MoveAssetAnalysisReportParams struct {
	TargetAssetID    int64
	DuplicateAssetID int64
}

// Used by GraphQL mutation mergeAsset to reassign portfolio analysis classification from the duplicate asset to the target asset.
func (q *Queries) MoveAssetAnalysisReport(ctx context.Context, arg MoveAssetAnalysisReportParams) error {
	_, err := q.db.ExecContext(ctx, moveAssetAnalysisReport, arg.TargetAssetID, arg.DuplicateAssetID)
	return err
}

const recalculateSnapshotBalancesByIDs = `-- name: RecalculateSnapshotBalancesByIDs :exec
UPDATE account_balance_daily_snapshots
SET balance_usd_cents = (
  SELECT COALESCE(SUM(value_usd_cents), 0)
  FROM asset_daily_holdings
  WHERE snapshot_id = account_balance_daily_snapshots.id
    AND counts_toward_value = 1
)
WHERE account_balance_daily_snapshots.id IN (/*SLICE:snapshot_ids*/?)
`

type RecalculateSnapshotBalancesByIDsParams struct {
	SnapshotIds []int64
}

// Used after RevalueAssetHoldingsBySnapshotIDs to rebuild exactly the account-level balances affected by repricing.
func (q *Queries) RecalculateSnapshotBalancesByIDs(ctx context.Context, arg RecalculateSnapshotBalancesByIDsParams) error {
	query := recalculateSnapshotBalancesByIDs
	var queryParams []interface{}
	if len(arg.SnapshotIds) > 0 {
		for _, v := range arg.SnapshotIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:snapshot_ids*/?", strings.Repeat(",?", len(arg.SnapshotIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:snapshot_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const revalueAssetHoldingsBySnapshotIDs = `-- name: RevalueAssetHoldingsBySnapshotIDs :exec
UPDATE asset_daily_holdings
SET price = ?1,
    value_usd_cents = CASE
      WHEN quantity IS NULL THEN value_usd_cents
      ELSE CAST(ROUND(quantity * ?1 * 100) AS INTEGER)
    END
WHERE asset_id = CAST(?2 AS INTEGER)
  AND snapshot_id IN (/*SLICE:snapshot_ids*/?)
`

type RevalueAssetHoldingsBySnapshotIDsParams struct {
	Price       *float64
	AssetID     int64
	SnapshotIds []int64
}

// Used by wealth/db.Store's asset price-update path to reprice selected holdings when an asset price changes.
func (q *Queries) RevalueAssetHoldingsBySnapshotIDs(ctx context.Context, arg RevalueAssetHoldingsBySnapshotIDsParams) error {
	query := revalueAssetHoldingsBySnapshotIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Price)
	queryParams = append(queryParams, arg.AssetID)
	if len(arg.SnapshotIds) > 0 {
		for _, v := range arg.SnapshotIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:snapshot_ids*/?", strings.Repeat(",?", len(arg.SnapshotIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:snapshot_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateAssetAdditional = `-- name: UpdateAssetAdditional :exec
UPDATE assets
SET additional = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type UpdateAssetAdditionalParams struct {
	Additional *string
	ID         int64
}

// Used by wealth/db.Store.UpsertAsset and manual updateAsset handling to persist merged type-specific metadata.
func (q *Queries) UpdateAssetAdditional(ctx context.Context, arg UpdateAssetAdditionalParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetAdditional, arg.Additional, arg.ID)
	return err
}

const updateAssetBase = `-- name: UpdateAssetBase :exec
UPDATE assets
SET name = COALESCE(?1, name),
    identifier = COALESCE(?2, identifier),
    classifier = COALESCE(?3, classifier),
    forced_usd_price = CASE
      WHEN CAST(?4 AS BOOLEAN) = 1 THEN ?5
      WHEN CAST(?6 AS BOOLEAN) = 1 THEN NULL
      ELSE forced_usd_price
    END,
    tracking_ticker = CASE
      WHEN CAST(?7 AS TEXT) IS NOT NULL THEN NULLIF(CAST(?7 AS TEXT), '')
      ELSE tracking_ticker
    END,
    tracking_multiplier = COALESCE(?8, tracking_multiplier),
    user_edited = 1,
    last_price = CASE WHEN CAST(?9 AS BOOLEAN) = 1 OR CAST(?7 AS TEXT) IS NOT NULL OR ?8 IS NOT NULL THEN NULL ELSE last_price END,
    last_price_at = CASE WHEN CAST(?9 AS BOOLEAN) = 1 OR CAST(?7 AS TEXT) IS NOT NULL OR ?8 IS NOT NULL THEN NULL ELSE last_price_at END,
    price_connectivity = CASE
      WHEN ?2 IS NOT NULL OR CAST(?7 AS TEXT) IS NOT NULL THEN 'HEALTHY'
      ELSE COALESCE(?10, price_connectivity)
    END,
    investment_connectivity = CASE
      WHEN CAST(?11 AS BOOLEAN) = 1 THEN 'HEALTHY'
      ELSE COALESCE(?12, investment_connectivity)
    END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?13
`

type UpdateAssetBaseParams struct {
	Name                   *string
	Identifier             *string
	Classifier             *string
	ForcedPriceSet         bool
	ForcedPriceValue       *float64
	ForcedPriceClear       bool
	TrackingTicker         *string
	TrackingMultiplier     *float64
	ClearMarketPrice       bool
	PriceConnectivity      *string
	EffectiveTickerChanged bool
	InvestmentConnectivity *string
	ID                     int64
}

// Used by GraphQL mutation updateAsset via wealth/db.Store to update user-editable fields (name, identifier, classifier, forced price, tracking ticker).
func (q *Queries) UpdateAssetBase(ctx context.Context, arg UpdateAssetBaseParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetBase,
		arg.Name,
		arg.Identifier,
		arg.Classifier,
		arg.ForcedPriceSet,
		arg.ForcedPriceValue,
		arg.ForcedPriceClear,
		arg.TrackingTicker,
		arg.TrackingMultiplier,
		arg.ClearMarketPrice,
		arg.PriceConnectivity,
		arg.EffectiveTickerChanged,
		arg.InvestmentConnectivity,
		arg.ID,
	)
	return err
}

const updateAssetConnectivity = `-- name: UpdateAssetConnectivity :exec
UPDATE assets
SET price_connectivity = COALESCE(?1, price_connectivity),
    investment_connectivity = COALESCE(?2, investment_connectivity),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
`

type UpdateAssetConnectivityParams struct {
	PriceConnectivity      *string
	InvestmentConnectivity *string
	ID                     int64
}

// Used by Yahoo Finance price polling and portfolio analysis sync to record asset fetch health.
func (q *Queries) UpdateAssetConnectivity(ctx context.Context, arg UpdateAssetConnectivityParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetConnectivity, arg.PriceConnectivity, arg.InvestmentConnectivity, arg.ID)
	return err
}

const updateAssetDailyHoldingsAssetID = `-- name: UpdateAssetDailyHoldingsAssetID :exec
UPDATE asset_daily_holdings
SET asset_id = ?1
WHERE asset_id = ?2
`

type UpdateAssetDailyHoldingsAssetIDParams struct {
	TargetAssetID    int64
	DuplicateAssetID int64
}

// Used by GraphQL mutation mergeAsset to move all historical holdings from the duplicate asset onto the target asset.
func (q *Queries) UpdateAssetDailyHoldingsAssetID(ctx context.Context, arg UpdateAssetDailyHoldingsAssetIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetDailyHoldingsAssetID, arg.TargetAssetID, arg.DuplicateAssetID)
	return err
}

const updateAssetPrice = `-- name: UpdateAssetPrice :execrows
UPDATE assets
SET last_price = ?1,
    last_price_at = ?2,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
  AND ?1 IS NOT NULL
  AND (last_price_at IS NULL OR ?2 >= last_price_at)
`

type UpdateAssetPriceParams struct {
	LastPrice   *float64
	LastPriceAt *time.Time
	ID          int64
}

// Used by wealth adapters' persister (Plaid/SimpleFIN/DeBank balance syncs) and Yahoo Finance price polling to record an asset's latest price.
func (q *Queries) UpdateAssetPrice(ctx context.Context, arg UpdateAssetPriceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAssetPrice, arg.LastPrice, arg.LastPriceAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAssetTrackingMultiplier = `-- name: UpdateAssetTrackingMultiplier :exec
UPDATE assets
SET tracking_multiplier = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
  AND tracking_ticker IS NOT NULL
`

type UpdateAssetTrackingMultiplierParams struct {
	TrackingMultiplier float64
	ID                 int64
}

// Used by wealth adapters' persister and snapshot revaluation to sync a tracked asset's price multiplier from provider data.
func (q *Queries) UpdateAssetTrackingMultiplier(ctx context.Context, arg UpdateAssetTrackingMultiplierParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetTrackingMultiplier, arg.TrackingMultiplier, arg.ID)
	return err
}

const upsertAssetRow = `-- name: UpsertAssetRow :one
INSERT INTO assets (
  asset_type,
  identifier,
  name,
  classifier,
  forced_usd_price,
  tracking_ticker,
  tracking_multiplier,
  additional,
  user_edited,
  user_created,
  last_price,
  last_price_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12
)
ON CONFLICT(asset_type, identifier) DO UPDATE SET
  name = COALESCE(excluded.name, assets.name),
  classifier = CASE WHEN assets.user_edited = 1 THEN assets.classifier ELSE excluded.classifier END,
  forced_usd_price = COALESCE(excluded.forced_usd_price, assets.forced_usd_price),
  tracking_ticker = COALESCE(assets.tracking_ticker, excluded.tracking_ticker),
  tracking_multiplier = CASE
    WHEN assets.tracking_ticker IS NOT NULL THEN assets.tracking_multiplier
    WHEN excluded.last_price IS NOT NULL
     AND (assets.last_price_at IS NULL OR excluded.last_price_at >= assets.last_price_at)
    THEN excluded.tracking_multiplier
    ELSE assets.tracking_multiplier
  END,
  additional = COALESCE(assets.additional, excluded.additional),
  user_edited = assets.user_edited OR excluded.user_edited,
  user_created = assets.user_created OR excluded.user_created,
  last_price = CASE
    WHEN excluded.last_price IS NOT NULL
     AND (assets.last_price_at IS NULL OR excluded.last_price_at >= assets.last_price_at)
    THEN excluded.last_price
    ELSE assets.last_price
  END,
  last_price_at = CASE
    WHEN excluded.last_price IS NOT NULL
     AND (assets.last_price_at IS NULL OR excluded.last_price_at >= assets.last_price_at)
    THEN COALESCE(excluded.last_price_at, assets.last_price_at)
    ELSE assets.last_price_at
  END,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id, asset_type, identifier, name, classifier,
  additional, last_price, last_price_at, forced_usd_price,
  tracking_ticker, tracking_multiplier,
  price_connectivity, investment_connectivity
`

type UpsertAssetRowParams struct {
	AssetType          string
	Identifier         string
	Name               *string
	Classifier         string
	ForcedUsdPrice     *float64
	TrackingTicker     *string
	TrackingMultiplier float64
	Additional         *string
	UserEdited         bool
	UserCreated        bool
	LastPrice          *float64
	LastPriceAt        *time.Time
}

type UpsertAssetRowRow struct {
	ID                     int64
	AssetType              string
	Identifier             string
	Name                   *string
	Classifier             string
	Additional             *string
	LastPrice              *float64
	LastPriceAt            *time.Time
	ForcedUsdPrice         *float64
	TrackingTicker         *string
	TrackingMultiplier     float64
	PriceConnectivity      string
	InvestmentConnectivity string
}

// Used by wealth/db.Store.UpsertAsset (Plaid/SimpleFIN/DeBank adapter syncs, and GraphQL mutations createAsset/updateAsset) to insert or update an asset while preserving user-edited fields.
func (q *Queries) UpsertAssetRow(ctx context.Context, arg UpsertAssetRowParams) (UpsertAssetRowRow, error) {
	row := q.db.QueryRowContext(ctx, upsertAssetRow,
		arg.AssetType,
		arg.Identifier,
		arg.Name,
		arg.Classifier,
		arg.ForcedUsdPrice,
		arg.TrackingTicker,
		arg.TrackingMultiplier,
		arg.Additional,
		arg.UserEdited,
		arg.UserCreated,
		arg.LastPrice,
		arg.LastPriceAt,
	)
	var i UpsertAssetRowRow
	err := row.Scan(
		&i.ID,
		&i.AssetType,
		&i.Identifier,
		&i.Name,
		&i.Classifier,
		&i.Additional,
		&i.LastPrice,
		&i.LastPriceAt,
		&i.ForcedUsdPrice,
		&i.TrackingTicker,
		&i.TrackingMultiplier,
		&i.PriceConnectivity,
		&i.InvestmentConnectivity,
	)
	return i, err
}
