// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"time"
)

const accessToken = `-- name: AccessToken :one
SELECT
  client_id,
  subject,
  COALESCE(scopes, '') AS scopes,
  expires_at,
  COALESCE(request_id, '') AS request_id,
  CAST(1 AS BOOLEAN) AS active
FROM oauth_access_tokens
WHERE signature = ?1
  AND expires_at > ?2
`

type AccessTokenParams struct {
	Signature string
	Now       time.Time
}

type AccessTokenRow struct {
	ClientID  string
	Subject   string
	Scopes    string
	ExpiresAt time.Time
	RequestID string
	Active    bool
}

// Used by internal/auth's Fosite access-token store and the API auth middleware to validate a bearer token on every authenticated request.
func (q *Queries) AccessToken(ctx context.Context, arg AccessTokenParams) (AccessTokenRow, error) {
	row := q.db.QueryRowContext(ctx, accessToken, arg.Signature, arg.Now)
	var i AccessTokenRow
	err := row.Scan(
		&i.ClientID,
		&i.Subject,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RequestID,
		&i.Active,
	)
	return i, err
}

const authCode = `-- name: AuthCode :one
SELECT
  client_id,
  subject,
  COALESCE(scopes, '') AS scopes,
  redirect_uri,
  COALESCE(code_challenge, '') AS code_challenge,
  COALESCE(code_challenge_method, '') AS code_challenge_method,
  expires_at,
  active
FROM oauth_authorization_codes
WHERE TRUE
  AND active = 1 -- :if $3
  AND signature = ?1
  AND expires_at > ?2
`

var _authCodeDynQ = dynCompile(authCode)

type AuthCodeParams struct {
	Signature  string
	Now        time.Time
	ActiveOnly bool
}

type AuthCodeRow struct {
	ClientID            string
	Subject             string
	Scopes              string
	RedirectUri         string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           time.Time
	Active              bool
}

// Used by internal/auth's Fosite authorization-code store to look up a code, optionally requiring it to still be active.
func (q *Queries) AuthCode(ctx context.Context, arg AuthCodeParams) (AuthCodeRow, error) {

	dynQuery, dynArgs := _authCodeDynQ.Build([]any{arg.Signature, arg.Now, arg.ActiveOnly})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var i AuthCodeRow
	err := row.Scan(
		&i.ClientID,
		&i.Subject,
		&i.Scopes,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.Active,
	)
	return i, err
}

const claimAuthenticatedLoginSession = `-- name: ClaimAuthenticatedLoginSession :execrows
DELETE FROM login_sessions
WHERE id = ?1
  AND authenticated = 1
  AND expires_at > ?2
`

type ClaimAuthenticatedLoginSessionParams struct {
	ID  string
	Now time.Time
}

// Used by internal/auth's authorize endpoint to atomically consume one authenticated login session immediately before issuing a code.
func (q *Queries) ClaimAuthenticatedLoginSession(ctx context.Context, arg ClaimAuthenticatedLoginSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimAuthenticatedLoginSession, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cleanupExpiredAccessTokens = `-- name: CleanupExpiredAccessTokens :exec
DELETE FROM oauth_access_tokens
WHERE expires_at < ?1
`

type CleanupExpiredAccessTokensParams struct {
	Now time.Time
}

// Used by internal/auth's periodic background cleanup goroutine to delete expired access tokens.
func (q *Queries) CleanupExpiredAccessTokens(ctx context.Context, arg CleanupExpiredAccessTokensParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredAccessTokens, arg.Now)
	return err
}

const cleanupExpiredAuthCodes = `-- name: CleanupExpiredAuthCodes :exec
DELETE FROM oauth_authorization_codes
WHERE expires_at < ?1
`

type CleanupExpiredAuthCodesParams struct {
	Now time.Time
}

// Used by internal/auth's periodic background cleanup goroutine to delete expired authorization codes.
func (q *Queries) CleanupExpiredAuthCodes(ctx context.Context, arg CleanupExpiredAuthCodesParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredAuthCodes, arg.Now)
	return err
}

const cleanupExpiredLoginSessions = `-- name: CleanupExpiredLoginSessions :exec
DELETE FROM login_sessions
WHERE expires_at < ?1
`

type CleanupExpiredLoginSessionsParams struct {
	Now time.Time
}

// Used by internal/auth's periodic background cleanup goroutine to delete expired login sessions.
func (q *Queries) CleanupExpiredLoginSessions(ctx context.Context, arg CleanupExpiredLoginSessionsParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredLoginSessions, arg.Now)
	return err
}

const cleanupExpiredRefreshTokens = `-- name: CleanupExpiredRefreshTokens :exec
DELETE FROM oauth_refresh_tokens
WHERE expires_at < ?1
`

type CleanupExpiredRefreshTokensParams struct {
	Now time.Time
}

// Used by internal/auth's periodic background cleanup goroutine to delete expired refresh tokens.
func (q *Queries) CleanupExpiredRefreshTokens(ctx context.Context, arg CleanupExpiredRefreshTokensParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredRefreshTokens, arg.Now)
	return err
}

const cleanupExpiredWebAuthnRegistrations = `-- name: CleanupExpiredWebAuthnRegistrations :exec
DELETE FROM webauthn_registrations
WHERE expires_at < ?1
`

type CleanupExpiredWebAuthnRegistrationsParams struct {
	Now time.Time
}

// Used by internal/auth's periodic background cleanup goroutine to delete expired (abandoned) WebAuthn registration ceremonies.
func (q *Queries) CleanupExpiredWebAuthnRegistrations(ctx context.Context, arg CleanupExpiredWebAuthnRegistrationsParams) error {
	_, err := q.db.ExecContext(ctx, cleanupExpiredWebAuthnRegistrations, arg.Now)
	return err
}

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO oauth_access_tokens (signature, client_id, subject, scopes, expires_at, request_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateAccessTokenParams struct {
	Signature string
	ClientID  string
	Subject   string
	Scopes    *string
	ExpiresAt time.Time
	RequestID *string
}

// Used by internal/auth's Fosite access-token store to persist a new access token at the token endpoint.
func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, createAccessToken,
		arg.Signature,
		arg.ClientID,
		arg.Subject,
		arg.Scopes,
		arg.ExpiresAt,
		arg.RequestID,
	)
	return err
}

const createAuthCode = `-- name: CreateAuthCode :exec
INSERT INTO oauth_authorization_codes (
  signature, client_id, subject, scopes, redirect_uri, code_challenge, code_challenge_method, expires_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8
)
`

type CreateAuthCodeParams struct {
	Signature           string
	ClientID            string
	Subject             string
	Scopes              *string
	RedirectUri         string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           time.Time
}

// Used by internal/auth's Fosite authorization-code store to persist a new code during the authorize step.
func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, createAuthCode,
		arg.Signature,
		arg.ClientID,
		arg.Subject,
		arg.Scopes,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}

const createLoginSession = `-- name: CreateLoginSession :exec
INSERT INTO login_sessions (
  id, client_id, redirect_uri, state, code_challenge, code_challenge_method, scopes, callback_state, expires_at, purpose
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10
)
`

type CreateLoginSessionParams struct {
	ID                  string
	ClientID            string
	RedirectUri         string
	State               *string
	CodeChallenge       string
	CodeChallengeMethod string
	Scopes              *string
	CallbackState       string
	ExpiresAt           time.Time
	Purpose             *string
}

// Used by internal/auth's authorize endpoint to create a login session at the start of every OAuth/OIDC login (Google, email OTP/magic link, WebAuthn).
func (q *Queries) CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) error {
	_, err := q.db.ExecContext(ctx, createLoginSession,
		arg.ID,
		arg.ClientID,
		arg.RedirectUri,
		arg.State,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Scopes,
		arg.CallbackState,
		arg.ExpiresAt,
		arg.Purpose,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO oauth_refresh_tokens (signature, client_id, subject, scopes, expires_at, request_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateRefreshTokenParams struct {
	Signature string
	ClientID  string
	Subject   string
	Scopes    *string
	ExpiresAt time.Time
	RequestID *string
}

// Used by internal/auth's Fosite refresh-token store to persist a new refresh token at the token endpoint.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.Signature,
		arg.ClientID,
		arg.Subject,
		arg.Scopes,
		arg.ExpiresAt,
		arg.RequestID,
	)
	return err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM oauth_access_tokens
WHERE signature = ?1
`

type DeleteAccessTokenParams struct {
	Signature string
}

// Used by internal/auth's Fosite access-token store to revoke a single access token.
func (q *Queries) DeleteAccessToken(ctx context.Context, arg DeleteAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccessToken, arg.Signature)
	return err
}

const deleteAccessTokensByRequestID = `-- name: DeleteAccessTokensByRequestID :exec
DELETE FROM oauth_access_tokens
WHERE request_id = ?1
`

type DeleteAccessTokensByRequestIDParams struct {
	RequestID *string
}

// Used by internal/auth's Fosite token store to revoke every access token issued under the same OAuth request (e.g. on refresh-token replay detection).
func (q *Queries) DeleteAccessTokensByRequestID(ctx context.Context, arg DeleteAccessTokensByRequestIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensByRequestID, arg.RequestID)
	return err
}

const deleteAccessTokensBySubject = `-- name: DeleteAccessTokensBySubject :exec
DELETE FROM oauth_access_tokens
WHERE subject = ?1
`

type DeleteAccessTokensBySubjectParams struct {
	Subject string
}

// Used by internal/auth's RevokeUserTokens (called on user removal) to revoke all of a user's outstanding access tokens.
func (q *Queries) DeleteAccessTokensBySubject(ctx context.Context, arg DeleteAccessTokensBySubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccessTokensBySubject, arg.Subject)
	return err
}

const deleteLoginSession = `-- name: DeleteLoginSession :exec
DELETE FROM login_sessions
WHERE id = ?1
`

type DeleteLoginSessionParams struct {
	ID string
}

// Used by internal/auth's consent and token-exchange handlers to delete a login session once it has been consumed.
func (q *Queries) DeleteLoginSession(ctx context.Context, arg DeleteLoginSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteLoginSession, arg.ID)
	return err
}

const deleteRefreshTokensBySubject = `-- name: DeleteRefreshTokensBySubject :exec
DELETE FROM oauth_refresh_tokens
WHERE subject = ?1
`

type DeleteRefreshTokensBySubjectParams struct {
	Subject string
}

// Used by internal/auth's RevokeUserTokens (called on user removal) to revoke all of a user's outstanding refresh tokens.
func (q *Queries) DeleteRefreshTokensBySubject(ctx context.Context, arg DeleteRefreshTokensBySubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensBySubject, arg.Subject)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?1
`

type DeleteUserParams struct {
	ID int64
}

// Used by GraphQL mutation removeUser (admin.graphql) via admin/service.go; removal is by stable id, not email, so a re-invited user with the same email isn't accidentally removed.
func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.ID)
	return err
}

const incrementEmailOTPAttempts = `-- name: IncrementEmailOTPAttempts :exec
UPDATE login_sessions
SET email_otp_attempts = email_otp_attempts + 1
WHERE id = ?1
`

type IncrementEmailOTPAttemptsParams struct {
	ID string
}

// Used by internal/auth's VerifyEmailOTP to track failed attempts and enforce the OTP retry limit.
func (q *Queries) IncrementEmailOTPAttempts(ctx context.Context, arg IncrementEmailOTPAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, incrementEmailOTPAttempts, arg.ID)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, role, invited_by)
VALUES (?1, ?2, ?3)
RETURNING id
`

type InsertUserParams struct {
	Email     string
	Role      string
	InvitedBy *int64
}

// Used by GraphQL mutation addUser (admin.graphql) via admin/service.go to create and invite a new user (invitation reuses the email magic-link flow per server/AGENTS.md).
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Email, arg.Role, arg.InvitedBy)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const invalidateAuthCode = `-- name: InvalidateAuthCode :execrows
UPDATE oauth_authorization_codes
SET active = 0
WHERE signature = ?1
  AND active = 1
`

type InvalidateAuthCodeParams struct {
	Signature string
}

// Used by internal/auth's Fosite authorization-code store to mark a code inactive immediately after it is exchanged for tokens.
func (q *Queries) InvalidateAuthCode(ctx context.Context, arg InvalidateAuthCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, invalidateAuthCode, arg.Signature)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const loadSigningKeyPEM = `-- name: LoadSigningKeyPEM :one
SELECT private_key_pem, public_key_pem
FROM signing_keys
WHERE id = 'primary'
`

type LoadSigningKeyPEMRow struct {
	PrivateKeyPem string
	PublicKeyPem  string
}

// Used by internal/auth at startup to load the persisted ECDSA P-256 JWT signing key.
func (q *Queries) LoadSigningKeyPEM(ctx context.Context) (LoadSigningKeyPEMRow, error) {
	row := q.db.QueryRowContext(ctx, loadSigningKeyPEM)
	var i LoadSigningKeyPEMRow
	err := row.Scan(&i.PrivateKeyPem, &i.PublicKeyPem)
	return i, err
}

const loginSessions = `-- name: LoginSessions :many
SELECT
  id,
  client_id,
  redirect_uri,
  COALESCE(state, '') AS state,
  code_challenge,
  code_challenge_method,
  COALESCE(scopes, '') AS scopes,
  callback_state,
  COALESCE(subject, '') AS subject,
  authenticated,
  expires_at,
  COALESCE(email, '') AS email,
  COALESCE(email_otp, '') AS email_otp,
  email_otp_expires_at,
  email_otp_attempts,
  COALESCE(email_magic_token, '') AS email_magic_token,
  COALESCE(pkce_verifier, '') AS pkce_verifier,
  COALESCE(webauthn_session, '') AS webauthn_session,
  COALESCE(purpose, '') AS purpose
FROM login_sessions
WHERE TRUE
  AND id = ?1 -- :if $1
  AND callback_state = ?2 -- :if $2
ORDER BY id
`

var _loginSessionsDynQ = dynCompile(loginSessions)

type LoginSessionsParams struct {
	ID            *string
	CallbackState *string
}

type LoginSessionsRow struct {
	ID                  string
	ClientID            string
	RedirectUri         string
	State               string
	CodeChallenge       string
	CodeChallengeMethod string
	Scopes              string
	CallbackState       string
	Subject             string
	Authenticated       bool
	ExpiresAt           time.Time
	Email               string
	EmailOtp            string
	EmailOtpExpiresAt   *time.Time
	EmailOtpAttempts    int64
	EmailMagicToken     string
	PkceVerifier        string
	WebauthnSession     string
	Purpose             string
}

// Used throughout internal/auth's login handlers to look up a login session by ID or callback state.
func (q *Queries) LoginSessions(ctx context.Context, arg LoginSessionsParams) ([]LoginSessionsRow, error) {

	dynQuery, dynArgs := _loginSessionsDynQ.Build([]any{arg.ID, arg.CallbackState})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginSessionsRow{}
	for rows.Next() {
		var i LoginSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.RedirectUri,
			&i.State,
			&i.CodeChallenge,
			&i.CodeChallengeMethod,
			&i.Scopes,
			&i.CallbackState,
			&i.Subject,
			&i.Authenticated,
			&i.ExpiresAt,
			&i.Email,
			&i.EmailOtp,
			&i.EmailOtpExpiresAt,
			&i.EmailOtpAttempts,
			&i.EmailMagicToken,
			&i.PkceVerifier,
			&i.WebauthnSession,
			&i.Purpose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLoginSessionAuthenticated = `-- name: MarkLoginSessionAuthenticated :execrows
UPDATE login_sessions
SET subject = ?1,
    authenticated = 1
WHERE id = ?2
  AND authenticated = 0
  AND expires_at > ?3
`

type MarkLoginSessionAuthenticatedParams struct {
	Subject *string
	ID      string
	Now     time.Time
}

// Used by internal/auth's Google, email OTP/magic-link, and WebAuthn handlers to mark a login session authenticated once the user's identity is verified.
func (q *Queries) MarkLoginSessionAuthenticated(ctx context.Context, arg MarkLoginSessionAuthenticatedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markLoginSessionAuthenticated, arg.Subject, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const oAuthClient = `-- name: OAuthClient :one
SELECT
  id,
  redirect_uris,
  grant_types,
  response_types,
  scopes,
  application_type,
  COALESCE(client_name, '') AS client_name,
  is_public,
  is_preseeded
FROM oauth_clients
WHERE id = ?1
`

type OAuthClientParams struct {
	ID string
}

type OAuthClientRow struct {
	ID              string
	RedirectUris    string
	GrantTypes      string
	ResponseTypes   string
	Scopes          string
	ApplicationType string
	ClientName      string
	IsPublic        bool
	IsPreseeded     bool
}

// Used by internal/auth's Fosite client store (GetClient) on every OAuth request to look up a registered client.
func (q *Queries) OAuthClient(ctx context.Context, arg OAuthClientParams) (OAuthClientRow, error) {
	row := q.db.QueryRowContext(ctx, oAuthClient, arg.ID)
	var i OAuthClientRow
	err := row.Scan(
		&i.ID,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scopes,
		&i.ApplicationType,
		&i.ClientName,
		&i.IsPublic,
		&i.IsPreseeded,
	)
	return i, err
}

const refreshToken = `-- name: RefreshToken :one
SELECT
  client_id,
  subject,
  COALESCE(scopes, '') AS scopes,
  expires_at,
  COALESCE(request_id, '') AS request_id,
  active
FROM oauth_refresh_tokens
WHERE TRUE
  AND active = 1 -- :if $3
  AND signature = ?1
  AND expires_at > ?2
`

var _refreshTokenDynQ = dynCompile(refreshToken)

type RefreshTokenParams struct {
	Signature  string
	Now        time.Time
	ActiveOnly bool
}

type RefreshTokenRow struct {
	ClientID  string
	Subject   string
	Scopes    string
	ExpiresAt time.Time
	RequestID string
	Active    bool
}

// Used by internal/auth's Store.RefreshToken for Fosite refresh-token lookups, optionally requiring the token to still be active.
func (q *Queries) RefreshToken(ctx context.Context, arg RefreshTokenParams) (RefreshTokenRow, error) {

	dynQuery, dynArgs := _refreshTokenDynQ.Build([]any{arg.Signature, arg.Now, arg.ActiveOnly})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var i RefreshTokenRow
	err := row.Scan(
		&i.ClientID,
		&i.Subject,
		&i.Scopes,
		&i.ExpiresAt,
		&i.RequestID,
		&i.Active,
	)
	return i, err
}

const revokeLiveRefreshToken = `-- name: RevokeLiveRefreshToken :execrows
UPDATE oauth_refresh_tokens
SET active = 0
WHERE signature = ?1
  AND active = 1
  AND expires_at > ?2
`

type RevokeLiveRefreshTokenParams struct {
	Signature string
	Now       time.Time
}

// Used by internal/auth's RotateRefreshToken to atomically revoke the old (still-live) refresh token as part of rotation; execrows lets the caller detect an already-revoked token (replay).
func (q *Queries) RevokeLiveRefreshToken(ctx context.Context, arg RevokeLiveRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeLiveRefreshToken, arg.Signature, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE oauth_refresh_tokens
SET active = 0
WHERE signature = ?1
`

type RevokeRefreshTokenParams struct {
	Signature string
}

// Used by internal/auth's Fosite refresh-token store to revoke a single refresh token (e.g. explicit logout).
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.Signature)
	return err
}

const revokeRefreshTokensByRequestID = `-- name: RevokeRefreshTokensByRequestID :exec
UPDATE oauth_refresh_tokens
SET active = 0
WHERE request_id = ?1
`

type RevokeRefreshTokensByRequestIDParams struct {
	RequestID *string
}

// Used by internal/auth's Fosite token store to revoke every refresh token issued under the same OAuth request (replay/rotation-chain revocation).
func (q *Queries) RevokeRefreshTokensByRequestID(ctx context.Context, arg RevokeRefreshTokensByRequestIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshTokensByRequestID, arg.RequestID)
	return err
}

const saveEmailOTP = `-- name: SaveEmailOTP :exec
UPDATE login_sessions
SET email = ?1,
    email_otp = ?2,
    email_otp_expires_at = ?3,
    email_otp_attempts = 0,
    email_magic_token = ?4,
    pkce_verifier = ?5
WHERE id = ?6
`

type SaveEmailOTPParams struct {
	Email             *string
	EmailOtp          *string
	EmailOtpExpiresAt *time.Time
	EmailMagicToken   *string
	PkceVerifier      *string
	ID                string
}

// Used by internal/auth's email OTP/magic-link handler to store a freshly issued OTP code and magic-link token hash on the login session.
func (q *Queries) SaveEmailOTP(ctx context.Context, arg SaveEmailOTPParams) error {
	_, err := q.db.ExecContext(ctx, saveEmailOTP,
		arg.Email,
		arg.EmailOtp,
		arg.EmailOtpExpiresAt,
		arg.EmailMagicToken,
		arg.PkceVerifier,
		arg.ID,
	)
	return err
}

const saveLoginSessionWebAuthn = `-- name: SaveLoginSessionWebAuthn :exec
UPDATE login_sessions
SET webauthn_session = ?1
WHERE id = ?2
`

type SaveLoginSessionWebAuthnParams struct {
	WebauthnSession *string
	ID              string
}

// Used by internal/auth's WebAuthn login-begin handler to persist the ceremony challenge/session JSON on the login session.
func (q *Queries) SaveLoginSessionWebAuthn(ctx context.Context, arg SaveLoginSessionWebAuthnParams) error {
	_, err := q.db.ExecContext(ctx, saveLoginSessionWebAuthn, arg.WebauthnSession, arg.ID)
	return err
}

const saveOAuthClient = `-- name: SaveOAuthClient :exec
INSERT INTO oauth_clients (
  id, redirect_uris, grant_types, response_types, scopes, application_type, client_name, is_public, is_preseeded
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9
)
ON CONFLICT(id) DO UPDATE SET
  redirect_uris = excluded.redirect_uris,
  grant_types = excluded.grant_types,
  response_types = excluded.response_types,
  scopes = excluded.scopes,
  application_type = excluded.application_type,
  client_name = excluded.client_name,
  is_public = excluded.is_public,
  is_preseeded = excluded.is_preseeded
`

type SaveOAuthClientParams struct {
	ID              string
	RedirectUris    string
	GrantTypes      string
	ResponseTypes   string
	Scopes          string
	ApplicationType string
	ClientName      *string
	IsPublic        bool
	IsPreseeded     bool
}

// Used by internal/auth's Fosite client store to upsert an OAuth client (static config load and dynamic client registration via POST /register).
func (q *Queries) SaveOAuthClient(ctx context.Context, arg SaveOAuthClientParams) error {
	_, err := q.db.ExecContext(ctx, saveOAuthClient,
		arg.ID,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Scopes,
		arg.ApplicationType,
		arg.ClientName,
		arg.IsPublic,
		arg.IsPreseeded,
	)
	return err
}

const saveSigningKeyPEM = `-- name: SaveSigningKeyPEM :exec
INSERT INTO signing_keys (id, algorithm, private_key_pem, public_key_pem)
VALUES ('primary', 'ES256', ?1, ?2)
`

type SaveSigningKeyPEMParams struct {
	PrivatePem string
	PublicPem  string
}

// Used by internal/auth at first-run startup to persist a newly generated ECDSA P-256 JWT signing key.
func (q *Queries) SaveSigningKeyPEM(ctx context.Context, arg SaveSigningKeyPEMParams) error {
	_, err := q.db.ExecContext(ctx, saveSigningKeyPEM, arg.PrivatePem, arg.PublicPem)
	return err
}

const updateAuthCodePKCE = `-- name: UpdateAuthCodePKCE :exec
UPDATE oauth_authorization_codes
SET code_challenge = ?1,
    code_challenge_method = ?2
WHERE signature = ?3
`

type UpdateAuthCodePKCEParams struct {
	CodeChallenge       string
	CodeChallengeMethod string
	Signature           string
}

// Used by internal/auth's Fosite PKCE session store to attach the code_challenge/method to an already-created authorization code.
func (q *Queries) UpdateAuthCodePKCE(ctx context.Context, arg UpdateAuthCodePKCEParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthCodePKCE, arg.CodeChallenge, arg.CodeChallengeMethod, arg.Signature)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = ?1
WHERE id = ?2
`

type UpdateUserRoleParams struct {
	Role string
	ID   int64
}

// Used by GraphQL mutation updateUser (admin.graphql) via admin/service.go to change a user's role.
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const users = `-- name: Users :many
SELECT
  id,
  email,
  role,
  created_at
FROM users
WHERE TRUE
  AND id = ?1 -- :if $1
  AND email = ?2 -- :if $2
ORDER BY role = 'admin' DESC, email ASC
`

var _usersDynQ = dynCompile(users)

type UsersParams struct {
	ID    *int64
	Email *string
}

type UsersRow struct {
	ID        int64
	Email     string
	Role      string
	CreatedAt time.Time
}

// Used by GraphQL user queries and auth/admin user lookups.
func (q *Queries) Users(ctx context.Context, arg UsersParams) ([]UsersRow, error) {

	dynQuery, dynArgs := _usersDynQ.Build([]any{arg.ID, arg.Email})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersRow{}
	for rows.Next() {
		var i UsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
