// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance_review_provider_states.sql

package dbgen

import (
	"context"

	"tallyo/internal/money"
)

const deleteSnapshotProviderStatesBetweenDates = `-- name: DeleteSnapshotProviderStatesBetweenDates :exec
DELETE FROM account_balance_snapshot_provider_states
WHERE snapshot_id IN (
  SELECT id
  FROM account_balance_daily_snapshots
  WHERE TRUE
    AND date >= CASE WHEN CAST(?1 AS BOOLEAN) = 1 THEN ?2 ELSE date(?2, '+1 day') END -- :if $2
    AND date <= CASE WHEN CAST(?1 AS BOOLEAN) = 1 THEN ?3 ELSE date(?3, '-1 day') END -- :if $3
    AND account_id = ?4
)
`

var _deleteSnapshotProviderStatesBetweenDatesDynQ = dynCompile(deleteSnapshotProviderStatesBetweenDates)

type DeleteSnapshotProviderStatesBetweenDatesParams struct {
	Inclusive  bool
	AfterDate  *string
	BeforeDate *string
	AccountID  int64
}

// Used when a clean snapshot recovers a review range, a review resolution consumes provider restoration state, or (with no date bounds) clean snapshots or manual edits make all provider restoration state unreachable for an account.
func (q *Queries) DeleteSnapshotProviderStatesBetweenDates(ctx context.Context, arg DeleteSnapshotProviderStatesBetweenDatesParams) error {

	dynQuery, dynArgs := _deleteSnapshotProviderStatesBetweenDatesDynQ.Build([]any{arg.Inclusive, arg.AfterDate, arg.BeforeDate, arg.AccountID})
	_, err := q.db.ExecContext(ctx, dynQuery, dynArgs...)
	return err
}

const flaggedSnapshotsWithProviderStatesForReview = `-- name: FlaggedSnapshotsWithProviderStatesForReview :many
SELECT
  s.id,
  s.date,
  ps.snapshot_id IS NULL AS missing_provider_state,
  COALESCE(ps.provider_balance_usd_cents, 0) AS provider_balance_usd_cents,
  CAST(COALESCE(ps.provider_holdings_json, '') AS TEXT) AS provider_holdings_json
FROM account_balance_daily_snapshots s
LEFT JOIN account_balance_snapshot_provider_states ps ON ps.snapshot_id = s.id
WHERE s.account_id = ?1
  AND s.flagged = 1
  AND s.date >= ?2
  AND s.date <= ?3
ORDER BY s.date, s.id
`

type FlaggedSnapshotsWithProviderStatesForReviewParams struct {
	AccountID int64
	StartDate string
	EndDate   string
}

type FlaggedSnapshotsWithProviderStatesForReviewRow struct {
	ID                      int64
	Date                    string
	MissingProviderState    bool
	ProviderBalanceUsdCents money.Cents
	ProviderHoldingsJson    string
}

// Used by USE_PROVIDER to restore each flagged snapshot from that date's provider state.
func (q *Queries) FlaggedSnapshotsWithProviderStatesForReview(ctx context.Context, arg FlaggedSnapshotsWithProviderStatesForReviewParams) ([]FlaggedSnapshotsWithProviderStatesForReviewRow, error) {
	rows, err := q.db.QueryContext(ctx, flaggedSnapshotsWithProviderStatesForReview, arg.AccountID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlaggedSnapshotsWithProviderStatesForReviewRow{}
	for rows.Next() {
		var i FlaggedSnapshotsWithProviderStatesForReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.MissingProviderState,
			&i.ProviderBalanceUsdCents,
			&i.ProviderHoldingsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSnapshotProviderState = `-- name: InsertSnapshotProviderState :exec
INSERT OR REPLACE INTO account_balance_snapshot_provider_states (
  snapshot_id,
  provider_balance_usd_cents,
  provider_holdings_json
) VALUES (
  ?1,
  ?2,
  ?3
)
`

type InsertSnapshotProviderStateParams struct {
	SnapshotID              int64
	ProviderBalanceUsdCents money.Cents
	ProviderHoldingsJson    string
}

// Used by the shared wealth snapshot sink to persist the provider state for one flagged snapshot.
func (q *Queries) InsertSnapshotProviderState(ctx context.Context, arg InsertSnapshotProviderStateParams) error {
	_, err := q.db.ExecContext(ctx, insertSnapshotProviderState, arg.SnapshotID, arg.ProviderBalanceUsdCents, arg.ProviderHoldingsJson)
	return err
}

const recountBalanceReviewFlaggedSnapshots = `-- name: RecountBalanceReviewFlaggedSnapshots :exec
UPDATE account_balance_snapshot_reviews
SET flagged_snapshot_count = (
  SELECT COUNT(DISTINCT s.id)
  FROM account_balance_daily_snapshots s
  WHERE s.account_id = account_balance_snapshot_reviews.account_id
    AND s.date BETWEEN account_balance_snapshot_reviews.first_flagged_date
                   AND account_balance_snapshot_reviews.latest_flagged_date
    AND s.flagged = 1
),
updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE account_balance_snapshot_reviews.id = ?1
`

type RecountBalanceReviewFlaggedSnapshotsParams struct {
	ID int64
}

// Used after snapshot replacement to keep the review's displayed count distinct by persisted row.
func (q *Queries) RecountBalanceReviewFlaggedSnapshots(ctx context.Context, arg RecountBalanceReviewFlaggedSnapshotsParams) error {
	_, err := q.db.ExecContext(ctx, recountBalanceReviewFlaggedSnapshots, arg.ID)
	return err
}
