// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance_sync_schedules.sql

package dbgen

import (
	"context"
	"time"
)

const balanceSyncScheduleDue = `-- name: BalanceSyncScheduleDue :one
SELECT balance_sync_cron
FROM balance_sync_schedules
WHERE TRUE
  AND (next_balance_sync_at IS NULL OR next_balance_sync_at <= ?1) -- :if $3
  AND id = ?2
`

var _balanceSyncScheduleDueDynQ = dynCompile(balanceSyncScheduleDue)

type BalanceSyncScheduleDueParams struct {
	Now     *time.Time
	ID      string
	DueOnly bool
}

// Used by wealth adapters (Plaid, SimpleFIN, DeBank, real estate, manual) to check whether an account's balance sync schedule is due.
func (q *Queries) BalanceSyncScheduleDue(ctx context.Context, arg BalanceSyncScheduleDueParams) (string, error) {

	dynQuery, dynArgs := _balanceSyncScheduleDueDynQ.Build([]any{arg.Now, arg.ID, arg.DueOnly})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var balance_sync_cron string
	err := row.Scan(&balance_sync_cron)
	return balance_sync_cron, err
}

const setBalanceSyncScheduleSynced = `-- name: SetBalanceSyncScheduleSynced :exec
UPDATE balance_sync_schedules
SET next_balance_sync_at = ?1
WHERE id = ?2
`

type SetBalanceSyncScheduleSyncedParams struct {
	NextBalanceSyncAt *time.Time
	ID                string
}

// Used by wealth adapters to record a completed balance sync and schedule the next one.
func (q *Queries) SetBalanceSyncScheduleSynced(ctx context.Context, arg SetBalanceSyncScheduleSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setBalanceSyncScheduleSynced, arg.NextBalanceSyncAt, arg.ID)
	return err
}
