// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package dbgen

import (
	"context"

	"tallyo/internal/money"
)

const budgetByID = `-- name: BudgetByID :one
SELECT
  b.id,
  b.month,
  b.amount_cents,
  cr.cat_id, cr.cat_name, cr.cat_emoji, cr.group_name, cr.group_emoji, cr.group_kind, cr.sort_order, cr.group_id, cr.group_sort_order, cr.plaid_pfc2_codes
FROM budgets b
JOIN category_rows cr ON cr.cat_id = b.category_id
WHERE b.id = ?1
`

type BudgetByIDParams struct {
	ID int64
}

type BudgetByIDRow struct {
	ID          int64
	Month       string
	AmountCents money.Cents
	CategoryRow CategoryRow
}

// Used by the GraphQL node resolver and internally after setBudget to return the budget with its category details.
func (q *Queries) BudgetByID(ctx context.Context, arg BudgetByIDParams) (BudgetByIDRow, error) {
	row := q.db.QueryRowContext(ctx, budgetByID, arg.ID)
	var i BudgetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.AmountCents,
		&i.CategoryRow.CatID,
		&i.CategoryRow.CatName,
		&i.CategoryRow.CatEmoji,
		&i.CategoryRow.GroupName,
		&i.CategoryRow.GroupEmoji,
		&i.CategoryRow.GroupKind,
		&i.CategoryRow.SortOrder,
		&i.CategoryRow.GroupID,
		&i.CategoryRow.GroupSortOrder,
		&i.CategoryRow.PlaidPfc2Codes,
	)
	return i, err
}

const budgetsInRange = `-- name: BudgetsInRange :many
SELECT id, month, category_id, amount_cents
FROM budgets
WHERE TRUE
  AND month >= ?1 -- :if $1
  AND month < ?2 -- :if $2
LIMIT -1
`

var _budgetsInRangeDynQ = dynCompile(budgetsInRange)

type BudgetsInRangeParams struct {
	StartMonth *string
	EndMonth   *string
}

type BudgetsInRangeRow struct {
	ID          int64
	Month       string
	CategoryID  int64
	AmountCents money.Cents
}

// Used by budgetReport and budgetReportHistory to load budgeted lines across
// a half-open month range; callers group by month and category in Go.
func (q *Queries) BudgetsInRange(ctx context.Context, arg BudgetsInRangeParams) ([]BudgetsInRangeRow, error) {

	dynQuery, dynArgs := _budgetsInRangeDynQ.Build([]any{arg.StartMonth, arg.EndMonth})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetsInRangeRow{}
	for rows.Next() {
		var i BudgetsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.CategoryID,
			&i.AmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const copyBudgets = `-- name: CopyBudgets :execrows
INSERT INTO budgets (month, category_id, amount_cents)
SELECT ?1, b.category_id, b.amount_cents
FROM budgets b
WHERE b.month = ?2
ON CONFLICT(category_id, month) DO NOTHING
`

type CopyBudgetsParams struct {
	ToMonth   string
	FromMonth string
}

// Used by GraphQL mutation copyBudgets via budgets/db.Store to duplicate a month's budgets onto another month.
func (q *Queries) CopyBudgets(ctx context.Context, arg CopyBudgetsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, copyBudgets, arg.ToMonth, arg.FromMonth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budgets
WHERE id = ?1
`

type DeleteBudgetParams struct {
	ID int64
}

// Used by GraphQL mutation deleteBudget via budgets/db.Store.
func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBudget, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (month, category_id, amount_cents)
VALUES (?1, ?2, ?3)
ON CONFLICT(category_id, month) DO UPDATE SET
  amount_cents = excluded.amount_cents,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertBudgetParams struct {
	Month       string
	CategoryID  int64
	AmountCents money.Cents
}

// Used by GraphQL mutation setBudget via budgets/db.Store.
func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertBudget, arg.Month, arg.CategoryID, arg.AmountCents)
	var id int64
	err := row.Scan(&id)
	return id, err
}
