// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categorization.sql

package dbgen

import (
	"context"

	"tallyo/internal/money"
)

const autoRuleResult = `-- name: AutoRuleResult :one
SELECT
  r.category_id,
  r.merchant_name,
  r.should_hide,
  r.should_be_recurring,
  CAST(COALESCE((
    SELECT group_concat(rt.tag_id, ',')
    FROM rule_tags rt
    WHERE rt.rule_id = r.id
  ), '') AS TEXT) AS tag_ids
FROM rules r
LEFT JOIN rule_accounts ra ON ra.rule_id = r.id
WHERE (
    (r.merchant_pattern != '' AND instr(lower(?1), lower(r.merchant_pattern)) > 0)
    OR (r.original_pattern != '' AND instr(lower(?2), lower(r.original_pattern)) > 0)
  )
  AND (r.amount_min_cents IS NULL OR ?3 >= r.amount_min_cents)
  AND (r.amount_max_cents IS NULL OR ?3 <= r.amount_max_cents)
  AND (ra.account_id IS NULL OR ra.account_id = ?4)
ORDER BY r.priority DESC, r.id DESC
LIMIT 1
`

type AutoRuleResultParams struct {
	Merchant     string
	OriginalName string
	AmountCents  *money.Cents
	AccountID    int64
}

type AutoRuleResultRow struct {
	CategoryID        *int64
	MerchantName      *string
	ShouldHide        *bool
	ShouldBeRecurring *bool
	TagIds            string
}

// Used by internal/transactions/categorizer during sync to find the highest-priority rule matching a transaction's merchant/original name, amount, and account.
func (q *Queries) AutoRuleResult(ctx context.Context, arg AutoRuleResultParams) (AutoRuleResultRow, error) {
	row := q.db.QueryRowContext(ctx, autoRuleResult,
		arg.Merchant,
		arg.OriginalName,
		arg.AmountCents,
		arg.AccountID,
	)
	var i AutoRuleResultRow
	err := row.Scan(
		&i.CategoryID,
		&i.MerchantName,
		&i.ShouldHide,
		&i.ShouldBeRecurring,
		&i.TagIds,
	)
	return i, err
}

const plaidCategoryIDByDetailed = `-- name: PlaidCategoryIDByDetailed :one
SELECT category_id
FROM plaid_category_mappings
WHERE plaid_detailed = ?1
`

type PlaidCategoryIDByDetailedParams struct {
	PlaidDetailed string
}

// Used by internal/transactions/categorizer as the fallback tier after rules: maps a Plaid personal_finance_category to an internal category.
func (q *Queries) PlaidCategoryIDByDetailed(ctx context.Context, arg PlaidCategoryIDByDetailedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, plaidCategoryIDByDetailed, arg.PlaidDetailed)
	var category_id int64
	err := row.Scan(&category_id)
	return category_id, err
}
