// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbgen

import (
	"context"
)

const categoryGroupByID = `-- name: CategoryGroupByID :one
SELECT id, name, emoji, kind
FROM category_groups
WHERE id = ?1
`

type CategoryGroupByIDParams struct {
	ID int64
}

type CategoryGroupByIDRow struct {
	ID    int64
	Name  string
	Emoji string
	Kind  string
}

// Used by the GraphQL node resolver to resolve a CategoryGroup, and internally after createCategoryGroup/updateCategoryGroup.
func (q *Queries) CategoryGroupByID(ctx context.Context, arg CategoryGroupByIDParams) (CategoryGroupByIDRow, error) {
	row := q.db.QueryRowContext(ctx, categoryGroupByID, arg.ID)
	var i CategoryGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Emoji,
		&i.Kind,
	)
	return i, err
}

const categoryInfo = `-- name: CategoryInfo :one
SELECT c.id, CAST(COUNT(t.id) AS INTEGER) AS transaction_count
FROM categories c
LEFT JOIN transactions t ON t.category_id = c.id
WHERE c.id = ?1
GROUP BY c.id
`

type CategoryInfoParams struct {
	ID int64
}

type CategoryInfoRow struct {
	ID               int64
	TransactionCount int64
}

// Used by createTransaction and deleteCategory to validate a category and count its references.
func (q *Queries) CategoryInfo(ctx context.Context, arg CategoryInfoParams) (CategoryInfoRow, error) {
	row := q.db.QueryRowContext(ctx, categoryInfo, arg.ID)
	var i CategoryInfoRow
	err := row.Scan(&i.ID, &i.TransactionCount)
	return i, err
}

const countCategoriesByGroup = `-- name: CountCategoriesByGroup :one
SELECT COUNT(*)
FROM categories
WHERE group_id = ?1
`

type CountCategoriesByGroupParams struct {
	GroupID int64
}

// Used by GraphQL mutation deleteCategoryGroup via transactions/db.Store to check the group is empty before deleting it.
func (q *Queries) CountCategoriesByGroup(ctx context.Context, arg CountCategoriesByGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoriesByGroup, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonSentinelCategories = `-- name: CountNonSentinelCategories :one
SELECT COUNT(*)
FROM categories
WHERE id != 0
`

// Used by internal/database's startup category seeding to check whether user categories already exist.
func (q *Queries) CountNonSentinelCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNonSentinelCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSentinelCategories = `-- name: CountSentinelCategories :one
SELECT COUNT(*)
FROM categories c
JOIN category_groups cg ON cg.id = c.group_id
WHERE c.id = 0
  AND cg.id = 0
`

// Used by internal/database's startup category seeding to check whether the uncategorized sentinel category/group already exist.
func (q *Queries) CountSentinelCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSentinelCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, emoji, group_id, sort_order)
VALUES (?1, ?2, ?3, COALESCE((SELECT MAX(sort_order) + 1 FROM categories WHERE group_id = ?3), 1))
RETURNING id
`

type CreateCategoryParams struct {
	Name    string
	Emoji   string
	GroupID int64
}

// Used by GraphQL mutation createCategory via transactions/db.Store.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Emoji, arg.GroupID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCategoryGroup = `-- name: CreateCategoryGroup :one
INSERT INTO category_groups (name, emoji, kind, sort_order)
VALUES (?1, ?2, ?3, COALESCE(NULLIF(CAST(?4 AS INTEGER), 0), (SELECT MAX(sort_order) + 1 FROM category_groups), 1))
RETURNING id
`

type CreateCategoryGroupParams struct {
	Name      string
	Emoji     string
	Kind      string
	SortOrder int64
}

// Used by GraphQL mutation createCategoryGroup and startup category seeding.
func (q *Queries) CreateCategoryGroup(ctx context.Context, arg CreateCategoryGroupParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategoryGroup,
		arg.Name,
		arg.Emoji,
		arg.Kind,
		arg.SortOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createSeedCategory = `-- name: CreateSeedCategory :one
INSERT INTO categories (name, emoji, group_id, sort_order)
VALUES (?1, ?2, ?3, ?4)
RETURNING id
`

type CreateSeedCategoryParams struct {
	Name      string
	Emoji     string
	GroupID   int64
	SortOrder int64
}

// Used by internal/database's startup category seeding to create built-in categories with fixed sort order.
func (q *Queries) CreateSeedCategory(ctx context.Context, arg CreateSeedCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createSeedCategory,
		arg.Name,
		arg.Emoji,
		arg.GroupID,
		arg.SortOrder,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?1
`

type DeleteCategoryParams struct {
	ID int64
}

// Used by GraphQL mutation deleteCategory via transactions/db.Store.
func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, arg.ID)
	return err
}

const deleteCategoryGroup = `-- name: DeleteCategoryGroup :execrows
DELETE FROM category_groups
WHERE id = ?1
`

type DeleteCategoryGroupParams struct {
	ID int64
}

// Used by GraphQL mutation deleteCategoryGroup via transactions/db.Store.
func (q *Queries) DeleteCategoryGroup(ctx context.Context, arg DeleteCategoryGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategoryGroup, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCategoryPlaidMappings = `-- name: DeleteCategoryPlaidMappings :exec
DELETE FROM plaid_category_mappings
WHERE category_id = ?1
`

type DeleteCategoryPlaidMappingsParams struct {
	CategoryID int64
}

// Used by GraphQL mutation updateCategory via transactions/db.Store to clear a category's existing Plaid mappings before re-inserting the updated set.
func (q *Queries) DeleteCategoryPlaidMappings(ctx context.Context, arg DeleteCategoryPlaidMappingsParams) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryPlaidMappings, arg.CategoryID)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT cr.cat_id, cr.cat_name, cr.cat_emoji, cr.group_name, cr.group_emoji, cr.group_kind, cr.sort_order, cr.group_id, cr.group_sort_order, cr.plaid_pfc2_codes
FROM category_rows cr
WHERE TRUE
  AND cr.group_kind = 'EXPENSE' -- :if $3
  AND cr.cat_id IN (/*SLICE:category_ids*/?1) -- :if $1
  AND cr.group_id = ?2 -- :if $2
ORDER BY
  cr.group_sort_order, -- :if $4
  cr.sort_order
`

var _listCategoriesDynQ = dynCompile(listCategories)

type ListCategoriesParams struct {
	CategoryIds []int64
	GroupID     *int64
	ExpenseOnly bool
	GroupOrder  bool
}

// Used by category list, lookup, spending report, and category-group display paths with optional filters and ordering.
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]CategoryRow, error) {

	dynQuery, dynArgs := _listCategoriesDynQ.Build([]any{arg.CategoryIds, arg.GroupID, arg.ExpenseOnly, arg.GroupOrder})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryRow{}
	for rows.Next() {
		var i CategoryRow
		if err := rows.Scan(
			&i.CatID,
			&i.CatName,
			&i.CatEmoji,
			&i.GroupName,
			&i.GroupEmoji,
			&i.GroupKind,
			&i.SortOrder,
			&i.GroupID,
			&i.GroupSortOrder,
			&i.PlaidPfc2Codes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pFC2MappedCategoryName = `-- name: PFC2MappedCategoryName :one
SELECT c.name
FROM plaid_category_mappings pcm
JOIN categories c ON c.id = pcm.category_id
WHERE pcm.plaid_detailed = ?1
  AND pcm.category_id != ?2
`

type PFC2MappedCategoryNameParams struct {
	PlaidDetailed string
	CategoryID    int64
}

// Used by GraphQL mutation createCategory/updateCategory via transactions/db.Store to check for a conflicting Plaid category mapping before saving.
func (q *Queries) PFC2MappedCategoryName(ctx context.Context, arg PFC2MappedCategoryNameParams) (string, error) {
	row := q.db.QueryRowContext(ctx, pFC2MappedCategoryName, arg.PlaidDetailed, arg.CategoryID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateCategoryFields = `-- name: UpdateCategoryFields :execrows
UPDATE categories
SET name = ?1,
    emoji = ?2,
    group_id = ?3
WHERE id = ?4
`

type UpdateCategoryFieldsParams struct {
	Name    string
	Emoji   string
	GroupID int64
	ID      int64
}

// Used by GraphQL mutation updateCategory via transactions/db.Store.
func (q *Queries) UpdateCategoryFields(ctx context.Context, arg UpdateCategoryFieldsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategoryFields,
		arg.Name,
		arg.Emoji,
		arg.GroupID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCategoryGroup = `-- name: UpdateCategoryGroup :execrows
UPDATE category_groups
SET name = ?1,
    emoji = ?2
WHERE id = ?3
`

type UpdateCategoryGroupParams struct {
	Name  string
	Emoji string
	ID    int64
}

// Used by GraphQL mutation updateCategoryGroup via transactions/db.Store.
func (q *Queries) UpdateCategoryGroup(ctx context.Context, arg UpdateCategoryGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategoryGroup, arg.Name, arg.Emoji, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCategorySortOrder = `-- name: UpdateCategorySortOrder :exec
UPDATE categories
SET sort_order = ?1
WHERE id = ?2
  AND group_id = ?3
`

type UpdateCategorySortOrderParams struct {
	SortOrder int64
	ID        int64
	GroupID   int64
}

// Used by GraphQL mutation reorderCategories via transactions/db.Store, guarded by group_id to block cross-group moves.
func (q *Queries) UpdateCategorySortOrder(ctx context.Context, arg UpdateCategorySortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCategorySortOrder, arg.SortOrder, arg.ID, arg.GroupID)
	return err
}

const upsertCategoryPlaidMapping = `-- name: UpsertCategoryPlaidMapping :exec
INSERT INTO plaid_category_mappings (plaid_detailed, category_id)
VALUES (?1, ?2)
ON CONFLICT(plaid_detailed) DO UPDATE SET category_id = excluded.category_id
`

type UpsertCategoryPlaidMappingParams struct {
	PlaidDetailed string
	CategoryID    int64
}

// Used by category mutations and startup seeding to upsert a Plaid detailed-category mapping by category ID.
func (q *Queries) UpsertCategoryPlaidMapping(ctx context.Context, arg UpsertCategoryPlaidMappingParams) error {
	_, err := q.db.ExecContext(ctx, upsertCategoryPlaidMapping, arg.PlaidDetailed, arg.CategoryID)
	return err
}

const upsertCategoryPlaidMappingByCategoryName = `-- name: UpsertCategoryPlaidMappingByCategoryName :exec
INSERT INTO plaid_category_mappings (plaid_detailed, category_id)
SELECT ?1, id
FROM categories
WHERE name = ?2
ON CONFLICT(plaid_detailed) DO UPDATE SET category_id = excluded.category_id
`

type UpsertCategoryPlaidMappingByCategoryNameParams struct {
	PlaidDetailed string
	CategoryName  string
}

// Used by internal/database's startup Plaid mapping seeding to upsert a Plaid detailed-category mapping by category name.
func (q *Queries) UpsertCategoryPlaidMappingByCategoryName(ctx context.Context, arg UpsertCategoryPlaidMappingByCategoryNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertCategoryPlaidMappingByCategoryName, arg.PlaidDetailed, arg.CategoryName)
	return err
}

const upsertSentinelCategory = `-- name: UpsertSentinelCategory :exec
INSERT INTO categories (id, name, emoji, sort_order, group_id)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  emoji = excluded.emoji,
  sort_order = excluded.sort_order,
  group_id = excluded.group_id
`

type UpsertSentinelCategoryParams struct {
	ID        int64
	Name      string
	Emoji     string
	SortOrder int64
	GroupID   int64
}

// Used by internal/database's startup category seeding to upsert the uncategorized sentinel category.
func (q *Queries) UpsertSentinelCategory(ctx context.Context, arg UpsertSentinelCategoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertSentinelCategory,
		arg.ID,
		arg.Name,
		arg.Emoji,
		arg.SortOrder,
		arg.GroupID,
	)
	return err
}

const upsertSentinelCategoryGroup = `-- name: UpsertSentinelCategoryGroup :exec
INSERT INTO category_groups (id, name, emoji, kind, sort_order)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  emoji = excluded.emoji,
  kind = excluded.kind,
  sort_order = excluded.sort_order
`

type UpsertSentinelCategoryGroupParams struct {
	ID        int64
	Name      string
	Emoji     string
	Kind      string
	SortOrder int64
}

// Used by internal/database's startup category seeding to upsert the uncategorized sentinel category group.
func (q *Queries) UpsertSentinelCategoryGroup(ctx context.Context, arg UpsertSentinelCategoryGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertSentinelCategoryGroup,
		arg.ID,
		arg.Name,
		arg.Emoji,
		arg.Kind,
		arg.SortOrder,
	)
	return err
}
