// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: configurations.sql

package dbgen

import (
	"context"
)

const listConfigurationSections = `-- name: ListConfigurationSections :many
SELECT section, enabled, fields
FROM configurations
ORDER BY section
`

type ListConfigurationSectionsRow struct {
	Section string
	Enabled bool
	Fields  string
}

// Used by GraphQL query configuration via admin/db.Store, and by startup config resolution to load all runtime settings sections.
func (q *Queries) ListConfigurationSections(ctx context.Context) ([]ListConfigurationSectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfigurationSections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigurationSectionsRow{}
	for rows.Next() {
		var i ListConfigurationSectionsRow
		if err := rows.Scan(&i.Section, &i.Enabled, &i.Fields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigurationSection = `-- name: UpsertConfigurationSection :exec
INSERT INTO configurations (section, enabled, fields, updated_at)
VALUES (?1, ?2, ?3, strftime('%Y-%m-%dT%H:%M:%SZ','now'))
ON CONFLICT(section) DO UPDATE SET
    enabled = excluded.enabled,
    fields = excluded.fields,
    updated_at = excluded.updated_at
`

type UpsertConfigurationSectionParams struct {
	Section string
	Enabled bool
	Fields  string
}

// Used by GraphQL mutation updateConfiguration via admin/db.Store to persist a runtime configuration section.
func (q *Queries) UpsertConfigurationSection(ctx context.Context, arg UpsertConfigurationSectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfigurationSection, arg.Section, arg.Enabled, arg.Fields)
	return err
}
