// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connections.sql

package dbgen

import (
	"context"
	"time"
)

const connections = `-- name: Connections :many
SELECT c.id, c.source_table, c.source_id, c.name, c.owner_id, o.name AS owner_name, c.is_active
FROM connections c
JOIN owners o ON o.id = c.owner_id
WHERE TRUE
  AND c.source_table IN ('plaid_items', 'evm_wallets', 'simplefin_connections') -- :if $4
  AND c.is_active = 1 -- :if $5
  AND c.id IN (/*SLICE:ids*/?1) -- :if $1
  AND c.source_table = ?2 -- :if $6
  AND c.source_id = ?3 -- :if $6
ORDER BY c.id
`

var _connectionsDynQ = dynCompile(connections)

type ConnectionsParams struct {
	Ids                    []int64
	SourceTable            string
	SourceID               int64
	SupportedProvidersOnly bool
	ActiveOnly             bool
	SourceLookup           bool
}

type ConnectionsRow struct {
	ID          int64
	SourceTable string
	SourceID    int64
	Name        *string
	OwnerID     int64
	OwnerName   string
	IsActive    bool
}

// Used by GraphQL connection queries and provider source lookups.
func (q *Queries) Connections(ctx context.Context, arg ConnectionsParams) ([]ConnectionsRow, error) {

	dynQuery, dynArgs := _connectionsDynQ.Build([]any{arg.Ids, arg.SourceTable, arg.SourceID, arg.SupportedProvidersOnly, arg.ActiveOnly, arg.SourceLookup})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectionsRow{}
	for rows.Next() {
		var i ConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceTable,
			&i.SourceID,
			&i.Name,
			&i.OwnerID,
			&i.OwnerName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAccountsByConnection = `-- name: DeleteAccountsByConnection :exec
DELETE FROM accounts
WHERE connection_id = ?1
`

type DeleteAccountsByConnectionParams struct {
	ConnectionID *int64
}

// Used by accounts/db.Store.DeleteConnection to remove all accounts owned by a connection.
func (q *Queries) DeleteAccountsByConnection(ctx context.Context, arg DeleteAccountsByConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteAccountsByConnection, arg.ConnectionID)
	return err
}

const deleteConnectionByID = `-- name: DeleteConnectionByID :exec
DELETE FROM connections
WHERE id = ?1
`

type DeleteConnectionByIDParams struct {
	ID int64
}

// Used by GraphQL mutation deleteConnection via accounts/db.Store.DeleteConnection.
func (q *Queries) DeleteConnectionByID(ctx context.Context, arg DeleteConnectionByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnectionByID, arg.ID)
	return err
}

const deleteEVMWallet = `-- name: DeleteEVMWallet :exec
DELETE FROM evm_wallets
WHERE id = ?1
`

type DeleteEVMWalletParams struct {
	ID int64
}

// Used by accounts/db.Store.DeleteConnection to remove the underlying evm_wallets row.
func (q *Queries) DeleteEVMWallet(ctx context.Context, arg DeleteEVMWalletParams) error {
	_, err := q.db.ExecContext(ctx, deleteEVMWallet, arg.ID)
	return err
}

const deletePlaidItem = `-- name: DeletePlaidItem :exec
DELETE FROM plaid_items
WHERE id = ?1
`

type DeletePlaidItemParams struct {
	ID int64
}

// Used by accounts/db.Store.DeleteConnection to remove the underlying plaid_items row.
func (q *Queries) DeletePlaidItem(ctx context.Context, arg DeletePlaidItemParams) error {
	_, err := q.db.ExecContext(ctx, deletePlaidItem, arg.ID)
	return err
}

const updateConnectionActive = `-- name: UpdateConnectionActive :exec
UPDATE connections
SET is_active = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type UpdateConnectionActiveParams struct {
	IsActive bool
	ID       int64
}

// Used by GraphQL mutation updateConnection via accounts/db.Store to toggle a connection's active state.
func (q *Queries) UpdateConnectionActive(ctx context.Context, arg UpdateConnectionActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateConnectionActive, arg.IsActive, arg.ID)
	return err
}

const updatePlaidConnectionSyncSettings = `-- name: UpdatePlaidConnectionSyncSettings :exec
UPDATE plaid_items
SET sync_cron = ?1,
    recurring_sync_cron = ?2,
    next_sync_at = ?3,
    next_recurring_sync_at = ?4,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?5
`

type UpdatePlaidConnectionSyncSettingsParams struct {
	SyncCron            string
	RecurringSyncCron   string
	NextSyncAt          *time.Time
	NextRecurringSyncAt *time.Time
	ID                  int64
}

// Used by GraphQL mutation updateConnection via accounts/db.Store to update a Plaid item's sync/recurring-sync cron schedule.
func (q *Queries) UpdatePlaidConnectionSyncSettings(ctx context.Context, arg UpdatePlaidConnectionSyncSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updatePlaidConnectionSyncSettings,
		arg.SyncCron,
		arg.RecurringSyncCron,
		arg.NextSyncAt,
		arg.NextRecurringSyncAt,
		arg.ID,
	)
	return err
}

const upsertConnection = `-- name: UpsertConnection :one
INSERT INTO connections (source_table, source_id, name, owner_id, is_active)
VALUES (?1, ?2, ?3, ?4, 1)
ON CONFLICT(source_table, source_id) DO UPDATE SET
  is_active = 1,
  name = COALESCE(excluded.name, connections.name),
  owner_id = excluded.owner_id,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertConnectionParams struct {
	SourceTable string
	SourceID    int64
	Name        *string
	OwnerID     int64
}

// Used by Plaid, SimpleFIN, EVM wallet, and real estate link flows to create or reactivate a polymorphic connection row.
func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertConnection,
		arg.SourceTable,
		arg.SourceID,
		arg.Name,
		arg.OwnerID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
