// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evm_wallets.sql

package dbgen

import (
	"context"
	"time"
)

const eVMWalletAccountID = `-- name: EVMWalletAccountID :one
SELECT a.id
FROM accounts a
JOIN connections c ON c.id = a.connection_id
WHERE c.source_table = 'evm_wallets'
  AND c.source_id = ?1
  AND a.manual = 0
  AND a.type = 'CRYPTO_WALLET'
`

type EVMWalletAccountIDParams struct {
	WalletID int64
}

// Used by accounts/db.Store.DeleteEVMWallet to find the wallet's account before deleting it.
func (q *Queries) EVMWalletAccountID(ctx context.Context, arg EVMWalletAccountIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, eVMWalletAccountID, arg.WalletID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const eVMWallets = `-- name: EVMWallets :many
SELECT c.id AS connection_id, w.id, w.address, w.chain_ids, c.owner_id, w.label, w.created_at,
       w.next_balance_sync_at
FROM evm_wallets w
JOIN connections c ON c.source_table = 'evm_wallets' AND c.source_id = w.id
WHERE TRUE
  AND c.id IN (/*SLICE:connection_ids*/?1) -- :if $1
  AND c.is_active = 1 -- :if $3
  AND (w.next_balance_sync_at IS NULL OR w.next_balance_sync_at <= ?2) -- :if $3
  AND EXISTS (SELECT 1 FROM accounts a WHERE a.connection_id = c.id AND a.manual = 0 AND a.type = 'CRYPTO_WALLET' AND a.is_closed = 0) -- :if $3
ORDER BY
  w.created_at, -- :if $3
  c.id
`

var _eVMWalletsDynQ = dynCompile(eVMWallets)

type EVMWalletsParams struct {
	ConnectionIds []int64
	Now           *time.Time
	DueOnly       bool
}

type EVMWalletsRow struct {
	ConnectionID      int64
	ID                int64
	Address           string
	ChainIds          string
	OwnerID           int64
	Label             string
	CreatedAt         time.Time
	NextBalanceSyncAt *time.Time
}

// Used by the EVM wallet dataloader and DeBank background sync loop.
func (q *Queries) EVMWallets(ctx context.Context, arg EVMWalletsParams) ([]EVMWalletsRow, error) {

	dynQuery, dynArgs := _eVMWalletsDynQ.Build([]any{arg.ConnectionIds, arg.Now, arg.DueOnly})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EVMWalletsRow{}
	for rows.Next() {
		var i EVMWalletsRow
		if err := rows.Scan(
			&i.ConnectionID,
			&i.ID,
			&i.Address,
			&i.ChainIds,
			&i.OwnerID,
			&i.Label,
			&i.CreatedAt,
			&i.NextBalanceSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEVMWallet = `-- name: InsertEVMWallet :one
INSERT INTO evm_wallets (address, label, chain_ids)
VALUES (?1, ?2, ?3)
RETURNING id
`

type InsertEVMWalletParams struct {
	Address  string
	Label    string
	ChainIds string
}

// Used by accounts/db.Store.CreateEVMWallet (EVM wallet link flow) to create the wallet row.
func (q *Queries) InsertEVMWallet(ctx context.Context, arg InsertEVMWalletParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEVMWallet, arg.Address, arg.Label, arg.ChainIds)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const setEVMWalletBalanceSynced = `-- name: SetEVMWalletBalanceSynced :exec
UPDATE evm_wallets
SET next_balance_sync_at = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type SetEVMWalletBalanceSyncedParams struct {
	NextBalanceSyncAt *time.Time
	ID                int64
}

// Used by internal/wealth's DeBank sync loop to record a completed balance sync and schedule the next one.
func (q *Queries) SetEVMWalletBalanceSynced(ctx context.Context, arg SetEVMWalletBalanceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setEVMWalletBalanceSynced, arg.NextBalanceSyncAt, arg.ID)
	return err
}

const updateEVMWalletChainIDs = `-- name: UpdateEVMWalletChainIDs :exec
UPDATE evm_wallets
SET chain_ids = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = (
    SELECT source_id
    FROM connections
    WHERE connections.id = ?2
      AND connections.source_table = 'evm_wallets'
)
`

type UpdateEVMWalletChainIDsParams struct {
	ChainIds     string
	ConnectionID int64
}

// Used by GraphQL mutation updateConnection via accounts/db.Store to change a wallet's tracked chain list.
func (q *Queries) UpdateEVMWalletChainIDs(ctx context.Context, arg UpdateEVMWalletChainIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateEVMWalletChainIDs, arg.ChainIds, arg.ConnectionID)
	return err
}
