// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holdings.sql

package dbgen

import (
	"context"
	"strings"
	"time"
)

const accountLastBalanceSyncedAtForAccounts = `-- name: AccountLastBalanceSyncedAtForAccounts :many
SELECT account_id, last_balance_synced_at
FROM account_sync_state
WHERE account_id IN (/*SLICE:account_ids*/?)
`

type AccountLastBalanceSyncedAtForAccountsParams struct {
	AccountIds []int64
}

// Used by internal/wealth's service layer to batch-fetch last balance-sync timestamps for multiple accounts.
func (q *Queries) AccountLastBalanceSyncedAtForAccounts(ctx context.Context, arg AccountLastBalanceSyncedAtForAccountsParams) ([]AccountSyncState, error) {
	query := accountLastBalanceSyncedAtForAccounts
	var queryParams []interface{}
	if len(arg.AccountIds) > 0 {
		for _, v := range arg.AccountIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:account_ids*/?", strings.Repeat(",?", len(arg.AccountIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:account_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountSyncState{}
	for rows.Next() {
		var i AccountSyncState
		if err := rows.Scan(&i.AccountID, &i.LastBalanceSyncedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountBalanceSynced = `-- name: MarkAccountBalanceSynced :exec
INSERT INTO account_sync_state (account_id, last_balance_synced_at)
VALUES (?1, ?2)
ON CONFLICT(account_id) DO UPDATE SET
  last_balance_synced_at = excluded.last_balance_synced_at
`

type MarkAccountBalanceSyncedParams struct {
	AccountID           int64
	LastBalanceSyncedAt *time.Time
}

// Used by every wealth adapter's persister (Plaid, SimpleFIN, DeBank, real estate, manual) to record that an account's balance was just synced.
func (q *Queries) MarkAccountBalanceSynced(ctx context.Context, arg MarkAccountBalanceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, markAccountBalanceSynced, arg.AccountID, arg.LastBalanceSyncedAt)
	return err
}
