// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm.sql

package dbgen

import (
	"context"

	"tallyo/internal/money"
)

const applyLLMCategory = `-- name: ApplyLLMCategory :exec

UPDATE transactions
SET category_id = ?1,
    is_reviewed = 1,
    staged_for_llm = 0,
    pfc2_categorized = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
  AND (category_id = ?3 OR pfc2_categorized = 1)
`

type ApplyLLMCategoryParams struct {
	CategoryID              int64
	ID                      int64
	UncategorizedCategoryID int64
}

// SimilarCategorizedByMerchants lives in transactions/db/llm.go because sqlc
// cannot analyze SQLite filters on window-function aliases.
// Used by internal/transactions' background LLM categorizer to apply an accepted categorization result.
func (q *Queries) ApplyLLMCategory(ctx context.Context, arg ApplyLLMCategoryParams) error {
	_, err := q.db.ExecContext(ctx, applyLLMCategory, arg.CategoryID, arg.ID, arg.UncategorizedCategoryID)
	return err
}

const categoriesForLLM = `-- name: CategoriesForLLM :many
SELECT c.id, c.name, cg.name AS group_name
FROM categories c
JOIN category_groups cg ON cg.id = c.group_id
WHERE cg.kind = 'EXPENSE'
ORDER BY c.sort_order
`

type CategoriesForLLMRow struct {
	ID        int64
	Name      string
	GroupName string
}

// Used by internal/transactions' background LLM categorizer to list expense categories as prompt context.
func (q *Queries) CategoriesForLLM(ctx context.Context) ([]CategoriesForLLMRow, error) {
	rows, err := q.db.QueryContext(ctx, categoriesForLLM)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoriesForLLMRow{}
	for rows.Next() {
		var i CategoriesForLLMRow
		if err := rows.Scan(&i.ID, &i.Name, &i.GroupName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearStagedForLLM = `-- name: ClearStagedForLLM :exec
UPDATE transactions
SET staged_for_llm = 0
WHERE TRUE
  AND id IN (/*SLICE:ids*/?1) -- :if $1
  AND staged_for_llm = 1
`

var _clearStagedForLLMDynQ = dynCompile(clearStagedForLLM)

type ClearStagedForLLMParams struct {
	Ids []int64
}

// Used by internal/transactions' sync loop and LLM worker to clear all or selected staged-for-LLM flags.
func (q *Queries) ClearStagedForLLM(ctx context.Context, arg ClearStagedForLLMParams) error {

	dynQuery, dynArgs := _clearStagedForLLMDynQ.Build([]any{arg.Ids})
	_, err := q.db.ExecContext(ctx, dynQuery, dynArgs...)
	return err
}

const countStagedForLLM = `-- name: CountStagedForLLM :one
SELECT COUNT(*)
FROM transactions
WHERE staged_for_llm = 1
`

// Used by transactionsStagedForCategorization to report background categorization progress.
func (q *Queries) CountStagedForLLM(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStagedForLLM)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const stageUncategorizedForLLM = `-- name: StageUncategorizedForLLM :execrows
UPDATE transactions
SET staged_for_llm = 1
WHERE is_reviewed = 0
  AND staged_for_llm = 0
`

// Used by reprocessUncategorizedTransactions to stage the review queue for the background LLM categorizer.
func (q *Queries) StageUncategorizedForLLM(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, stageUncategorizedForLLM)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const topMerchantExamples = `-- name: TopMerchantExamples :many
SELECT
  CAST(MIN(t.merchant_name) AS TEXT) AS merchant_name,
  c.name AS category_name,
  c.id AS category_id
FROM transactions t
JOIN categories c ON t.category_id = c.id
JOIN category_groups cg ON cg.id = c.group_id
WHERE t.merchant_name IS NOT NULL
  AND t.is_reviewed = 1
  AND cg.kind = 'EXPENSE'
  AND t.datetime < strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days')
GROUP BY LOWER(t.merchant_name), c.id
ORDER BY COUNT(*) DESC
LIMIT ?1
`

type TopMerchantExamplesParams struct {
	RowLimit int64
}

type TopMerchantExamplesRow struct {
	MerchantName string
	CategoryName string
	CategoryID   int64
}

// Used by internal/transactions' background LLM categorizer to fetch already-reviewed examples per merchant as few-shot prompt context.
func (q *Queries) TopMerchantExamples(ctx context.Context, arg TopMerchantExamplesParams) ([]TopMerchantExamplesRow, error) {
	rows, err := q.db.QueryContext(ctx, topMerchantExamples, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopMerchantExamplesRow{}
	for rows.Next() {
		var i TopMerchantExamplesRow
		if err := rows.Scan(&i.MerchantName, &i.CategoryName, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncategorizedForLLM = `-- name: UncategorizedForLLM :many
SELECT id, merchant_name, original_name, amount_cents, plaid_category, pfc2_categorized
FROM transactions
WHERE staged_for_llm = 1
ORDER BY datetime DESC
LIMIT ?1
`

type UncategorizedForLLMParams struct {
	RowLimit int64
}

type UncategorizedForLLMRow struct {
	ID              int64
	MerchantName    *string
	OriginalName    *string
	AmountCents     money.Cents
	PlaidCategory   *string
	Pfc2Categorized bool
}

// Used by internal/transactions' background LLM categorizer to fetch transactions staged for categorization.
func (q *Queries) UncategorizedForLLM(ctx context.Context, arg UncategorizedForLLMParams) ([]UncategorizedForLLMRow, error) {
	rows, err := q.db.QueryContext(ctx, uncategorizedForLLM, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UncategorizedForLLMRow{}
	for rows.Next() {
		var i UncategorizedForLLMRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantName,
			&i.OriginalName,
			&i.AmountCents,
			&i.PlaidCategory,
			&i.Pfc2Categorized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
