// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"tallyo/internal/money"
)

type Account struct {
	ConnectionID *int64
	CreatedAt    time.Time
	ExternalID   string
	ID           int64
	IsClosed     bool
	IsHidden     bool
	Manual       bool
	Mask         *string
	Name         string
	NeedsReview  bool
	Notes        *string
	OwnerID      int64
	ReviewReason *string
	Subtype      *string
	Type         string
	UpdatedAt    time.Time
}

type AccountBalanceDailySnapshot struct {
	AccountID       int64
	BalanceUsdCents money.Cents
	CreatedAt       time.Time
	Date            string
	FlagReason      *string
	Flagged         bool
	ID              int64
	RawPayload      *string
	Source          string
	SyncedAt        time.Time
}

type AccountBalanceSnapshotProviderState struct {
	ProviderBalanceUsdCents money.Cents
	ProviderHoldingsJson    string
	SnapshotID              int64
}

type AccountBalanceSnapshotReview struct {
	AccountID                   int64
	CarryForwardBalanceUsdCents money.Cents
	CreatedAt                   time.Time
	Decision                    string
	FirstFlaggedDate            string
	FlagReason                  *string
	FlaggedSnapshotCount        int64
	ID                          int64
	LatestFlaggedDate           string
	ProviderBalanceUsdCents     money.Cents
	ProviderHoldingsJson        *string
	UpdatedAt                   time.Time
}

type AccountSyncState struct {
	AccountID           int64
	LastBalanceSyncedAt *time.Time
}

type Asset struct {
	Additional             *string
	AssetType              string
	Classifier             string
	CreatedAt              time.Time
	ForcedUsdPrice         *float64
	ID                     int64
	Identifier             string
	InvestmentConnectivity string
	LastPrice              *float64
	LastPriceAt            *time.Time
	Name                   *string
	PriceConnectivity      string
	TrackingMultiplier     float64
	TrackingTicker         *string
	UpdatedAt              time.Time
	UserCreated            bool
	UserEdited             bool
}

type AssetAdapterSource struct {
	AssetID       int64
	CreatedAt     time.Time
	ID            int64
	SourceAdapter string
	SourceID      string
}

type AssetAnalysisReport struct {
	AssetID                     int64
	BondPosition                float64
	CashPosition                float64
	Category                    string
	ConvertiblePosition         float64
	CreatedAt                   time.Time
	EquitySector                *string
	FetchedAt                   time.Time
	GroupName                   string
	OtherPosition               float64
	PreferredPosition           float64
	SectorBasicMaterials        float64
	SectorCommunicationServices float64
	SectorConsumerCyclical      float64
	SectorConsumerDefensive     float64
	SectorEnergy                float64
	SectorFinancialServices     float64
	SectorHealthcare            float64
	SectorIndustrials           float64
	SectorRealEstate            float64
	SectorTechnology            float64
	SectorUtilities             float64
	StockPosition               float64
}

type AssetDailyHolding struct {
	AccountID         int64
	AssetID           int64
	CountsTowardValue bool
	CreatedAt         time.Time
	Date              string
	ID                int64
	Manual            bool
	Price             *float64
	Quantity          *float64
	SnapshotID        int64
	ValueUsdCents     money.Cents
}

type AssetsFt struct {
	Identifier string
	Name       string
	AssetsFts  *string
}

type BalanceSyncSchedule struct {
	BalanceSyncCron   string
	ID                string
	NextBalanceSyncAt *time.Time
}

type Budget struct {
	AmountCents money.Cents
	CategoryID  int64
	CreatedAt   time.Time
	ID          int64
	Month       string
	UpdatedAt   time.Time
}

type Category struct {
	Emoji     string
	GroupID   int64
	ID        int64
	Name      string
	SortOrder int64
}

type CategoryGroup struct {
	Emoji     string
	ID        int64
	Kind      string
	Name      string
	SortOrder int64
}

type CategoryRow struct {
	CatID          int64
	CatName        string
	CatEmoji       string
	GroupName      string
	GroupEmoji     string
	GroupKind      string
	SortOrder      int64
	GroupID        int64
	GroupSortOrder int64
	PlaidPfc2Codes string
}

type Configuration struct {
	Enabled   bool
	Fields    string
	Section   string
	UpdatedAt time.Time
}

type Connection struct {
	CreatedAt   time.Time
	ID          int64
	IsActive    bool
	Name        *string
	OwnerID     int64
	SourceID    int64
	SourceTable string
	UpdatedAt   time.Time
}

type EvmWallet struct {
	Address           string
	ChainIds          string
	CreatedAt         time.Time
	ID                int64
	Label             string
	NextBalanceSyncAt *time.Time
	UpdatedAt         time.Time
}

type LoginSession struct {
	Authenticated       bool
	CallbackState       string
	ClientID            string
	CodeChallenge       string
	CodeChallengeMethod string
	CreatedAt           time.Time
	Email               *string
	EmailMagicToken     *string
	EmailOtp            *string
	EmailOtpAttempts    int64
	EmailOtpExpiresAt   *time.Time
	ExpiresAt           time.Time
	ID                  string
	PkceVerifier        *string
	Purpose             *string
	RedirectUri         string
	Scopes              *string
	State               *string
	Subject             *string
	WebauthnSession     *string
}

type OauthAccessToken struct {
	ClientID  string
	CreatedAt time.Time
	ExpiresAt time.Time
	RequestID *string
	Scopes    *string
	Signature string
	Subject   string
}

type OauthAuthorizationCode struct {
	Active              bool
	ClientID            string
	CodeChallenge       string
	CodeChallengeMethod string
	CreatedAt           time.Time
	ExpiresAt           time.Time
	RedirectUri         string
	Scopes              *string
	Signature           string
	Subject             string
}

type OauthClient struct {
	ApplicationType string
	ClientName      *string
	CreatedAt       time.Time
	GrantTypes      string
	ID              string
	IsPreseeded     bool
	IsPublic        bool
	RedirectUris    string
	ResponseTypes   string
	Scopes          string
}

type OauthRefreshToken struct {
	Active    bool
	ClientID  string
	CreatedAt time.Time
	ExpiresAt time.Time
	RequestID *string
	Scopes    *string
	Signature string
	Subject   string
}

type Owner struct {
	CreatedAt time.Time
	ID        int64
	Name      string
}

type PlaidCategoryMapping struct {
	CategoryID    int64
	PlaidDetailed string
}

type PlaidCredential struct {
	ClientID    string
	CreatedAt   time.Time
	Environment string
	ID          int64
	Label       *string
	Secret      string
}

type PlaidItem struct {
	AccessToken             string
	CreatedAt               time.Time
	CredentialID            int64
	Cursor                  *string
	ExternalID              string
	HealthErrorCode         *string
	HealthErrorMessage      *string
	HealthState             string
	HealthUpdatedAt         *time.Time
	ID                      int64
	InstitutionID           *string
	LastRecurringSyncedAt   *time.Time
	LastSyncedAt            *time.Time
	LogoUrl                 *string
	NextBalanceSyncAt       *time.Time
	NextRecurringSyncAt     *time.Time
	NextSyncAt              *time.Time
	PlaidInvestmentsEnabled bool
	PlaidLiabilitiesEnabled bool
	RecurringSyncCron       string
	SyncCron                string
	UpdatedAt               time.Time
}

type PlaidSyncLog struct {
	Added    string
	Api      string
	ID       int64
	ItemID   int64
	Modified string
	Removed  string
	SyncedAt time.Time
}

type RecurringCharge struct {
	AccountID          int64
	AverageAmountCents money.Cents
	Description        string
	ExternalID         string
	FirstDate          string
	Frequency          string
	ID                 int64
	IsActive           bool
	IsUserModified     bool
	LastAmountCents    money.Cents
	LastDate           string
	MerchantName       *string
	Status             string
	UpdatedAt          time.Time
}

type RecurringChargeTransaction struct {
	ChargeID      int64
	TransactionID int64
}

type RetentionSweep struct {
	ID           string
	LastSweepAt  *time.Time
	TriggerSweep bool
}

type Rule struct {
	AmountMaxCents    *money.Cents
	AmountMinCents    *money.Cents
	CategoryID        *int64
	CreatedAt         time.Time
	ID                int64
	MerchantName      *string
	MerchantPattern   string
	OriginalPattern   string
	Priority          int64
	ShouldBeRecurring *bool
	ShouldHide        *bool
}

type RuleAccount struct {
	AccountID int64
	RuleID    int64
}

type RuleTag struct {
	RuleID int64
	TagID  int64
}

type SigningKey struct {
	Algorithm     string
	CreatedAt     time.Time
	ID            string
	PrivateKeyPem string
	PublicKeyPem  string
}

type SimplefinAccessToken struct {
	AccessUrl         string
	CreatedAt         time.Time
	ID                int64
	Label             *string
	LastSyncedAt      *time.Time
	NextBalanceSyncAt *time.Time
	NextSyncAt        *time.Time
	OwnerID           int64
	SyncCron          string
	UpdatedAt         time.Time
}

type SimplefinConnection struct {
	AccessTokenID      int64
	CreatedAt          time.Time
	ExternalID         string
	HealthErrorMessage *string
	HealthState        string
	HealthUpdatedAt    *time.Time
	ID                 int64
	LastSyncedAt       *time.Time
	LogoUrl            *string
	OrgDomain          *string
	OrgID              *string
	OrgUrl             *string
	SfinUrl            *string
	UpdatedAt          time.Time
}

type SimplefinSyncLog struct {
	AccessTokenID  int64
	Added          string
	Error          *string
	ID             int64
	Modified       string
	PendingRemoved string
	StartDate      *string
	SyncedAt       time.Time
}

type Tag struct {
	Color            string
	CreatedAt        time.Time
	ID               int64
	Name             string
	TransactionCount int64
	UpdatedAt        time.Time
}

type Transaction struct {
	AccountID       int64
	AmountCents     money.Cents
	CategoryID      int64
	CreatedAt       time.Time
	Datetime        time.Time
	ExternalID      string
	ID              int64
	IsHidden        bool
	IsRecurring     bool
	IsReviewed      bool
	LogoUrl         *string
	MerchantName    *string
	Notes           *string
	OriginalName    *string
	Pending         bool
	Pfc2Categorized bool
	PlaidCategory   *string
	PostedDatetime  time.Time
	RawProviderJson *string
	Source          string
	StagedForLlm    bool
	UpdatedAt       time.Time
}

type TransactionTag struct {
	TagID         int64
	TransactionID int64
}

type TransactionsFt struct {
	MerchantName    string
	OriginalName    string
	Notes           string
	TransactionsFts *string
}

type User struct {
	CreatedAt time.Time
	Email     string
	ID        int64
	InvitedBy *int64
	Role      string
}

type WebauthnCredential struct {
	CreatedAt  time.Time
	Credential string
	ID         string
	LastUsedAt *time.Time
	Name       string
	UserID     int64
}

type WebauthnRegistration struct {
	ExpiresAt time.Time
	Name      string
	Session   string
	UserID    int64
}
