// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owners.sql

package dbgen

import (
	"context"
)

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (name)
VALUES (?1)
RETURNING created_at, id, name
`

type CreateOwnerParams struct {
	Name string
}

// Used by GraphQL mutation createOwner via accounts/db.Store.CreateOwner.
func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRowContext(ctx, createOwner, arg.Name)
	var i Owner
	err := row.Scan(&i.CreatedAt, &i.ID, &i.Name)
	return i, err
}

const deleteOwner = `-- name: DeleteOwner :execrows
DELETE FROM owners
WHERE id = ?1
`

type DeleteOwnerParams struct {
	ID int64
}

// Used by GraphQL mutation deleteOwner via accounts/db.Store.DeleteOwner.
func (q *Queries) DeleteOwner(ctx context.Context, arg DeleteOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOwner, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const owners = `-- name: Owners :many
SELECT o.created_at, o.id, o.name
FROM owners o
WHERE TRUE
  AND o.id = ?1 -- :if $1
ORDER BY o.name
`

var _ownersDynQ = dynCompile(owners)

type OwnersParams struct {
	ID *int64
}

// Used by GraphQL query owners and owner lookups in account/wealth linking flows.
func (q *Queries) Owners(ctx context.Context, arg OwnersParams) ([]Owner, error) {

	dynQuery, dynArgs := _ownersDynQ.Build([]any{arg.ID})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Owner{}
	for rows.Next() {
		var i Owner
		if err := rows.Scan(&i.CreatedAt, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
