// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plaid.sql

package dbgen

import (
	"context"
	"time"
)

const createPlaidCredential = `-- name: CreatePlaidCredential :one
INSERT INTO plaid_credentials (client_id, secret, environment, label)
VALUES (?1, ?2, ?3, ?4)
RETURNING id
`

type CreatePlaidCredentialParams struct {
	ClientID    string
	Secret      string
	Environment string
	Label       *string
}

// Used by GraphQL mutation createPlaidCredential (admin.graphql) via admin/db.Store.CreatePlaidCredential.
func (q *Queries) CreatePlaidCredential(ctx context.Context, arg CreatePlaidCredentialParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPlaidCredential,
		arg.ClientID,
		arg.Secret,
		arg.Environment,
		arg.Label,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePlaidCredential = `-- name: DeletePlaidCredential :execrows
DELETE FROM plaid_credentials
WHERE id = ?1
`

type DeletePlaidCredentialParams struct {
	ID int64
}

// Used by GraphQL mutation deletePlaidCredential (admin.graphql) via admin/db.Store.DeletePlaidCredential.
func (q *Queries) DeletePlaidCredential(ctx context.Context, arg DeletePlaidCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlaidCredential, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPlaidCredentials = `-- name: ListPlaidCredentials :many
SELECT pc.id, pc.client_id, pc.environment, pc.label, pc.created_at,
       CAST(COUNT(c.id) AS INTEGER) AS item_count
FROM plaid_credentials pc
LEFT JOIN plaid_items pi ON pi.credential_id = pc.id
LEFT JOIN connections c ON c.source_table = 'plaid_items' AND c.source_id = pi.id AND c.is_active = 1
WHERE TRUE
  AND pc.id IN (/*SLICE:ids*/?1) -- :if $1
GROUP BY pc.id
ORDER BY pc.id
`

var _listPlaidCredentialsDynQ = dynCompile(listPlaidCredentials)

type ListPlaidCredentialsParams struct {
	Ids []int64
}

type ListPlaidCredentialsRow struct {
	ID          int64
	ClientID    string
	Environment string
	Label       *string
	CreatedAt   time.Time
	ItemCount   int64
}

// Used by GraphQL query plaidCredentials and PlaidCredential dataloaders via
// admin/db.Store. Secret never leaves this projection; Plaid-client-only
// PlaidCredentialSecretByID carries the secret instead.
func (q *Queries) ListPlaidCredentials(ctx context.Context, arg ListPlaidCredentialsParams) ([]ListPlaidCredentialsRow, error) {

	dynQuery, dynArgs := _listPlaidCredentialsDynQ.Build([]any{arg.Ids})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaidCredentialsRow{}
	for rows.Next() {
		var i ListPlaidCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Environment,
			&i.Label,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaidItems = `-- name: ListPlaidItems :many
SELECT
  pi.id AS item_id,
  pi.credential_id,
  pi.institution_id,
  pi.last_synced_at,
  pi.health_state,
  pi.health_error_code,
  pi.health_error_message,
  pi.health_updated_at,
  pi.sync_cron,
  pi.recurring_sync_cron,
  pi.next_sync_at,
  pi.next_recurring_sync_at,
  c.is_active AS connection_is_active,
  pi.created_at,
  pi.updated_at
FROM plaid_items pi
JOIN connections c ON c.source_table = 'plaid_items' AND c.source_id = pi.id
JOIN owners o ON o.id = c.owner_id
WHERE TRUE
  AND c.is_active = 1 -- :if $2
  AND pi.id IN (/*SLICE:ids*/?1) -- :if $1
ORDER BY
  o.name,
  COALESCE(c.name, pi.external_id),
  pi.id
`

var _listPlaidItemsDynQ = dynCompile(listPlaidItems)

type ListPlaidItemsParams struct {
	Ids        []int64
	ActiveOnly bool
}

type ListPlaidItemsRow struct {
	ItemID              int64
	CredentialID        int64
	InstitutionID       *string
	LastSyncedAt        *time.Time
	HealthState         string
	HealthErrorCode     *string
	HealthErrorMessage  *string
	HealthUpdatedAt     *time.Time
	SyncCron            string
	RecurringSyncCron   string
	NextSyncAt          *time.Time
	NextRecurringSyncAt *time.Time
	ConnectionIsActive  bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Used by GraphQL query plaidItems and Plaid item dataloaders via accounts/db and transactions/db.
func (q *Queries) ListPlaidItems(ctx context.Context, arg ListPlaidItemsParams) ([]ListPlaidItemsRow, error) {

	dynQuery, dynArgs := _listPlaidItemsDynQ.Build([]any{arg.Ids, arg.ActiveOnly})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaidItemsRow{}
	for rows.Next() {
		var i ListPlaidItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.CredentialID,
			&i.InstitutionID,
			&i.LastSyncedAt,
			&i.HealthState,
			&i.HealthErrorCode,
			&i.HealthErrorMessage,
			&i.HealthUpdatedAt,
			&i.SyncCron,
			&i.RecurringSyncCron,
			&i.NextSyncAt,
			&i.NextRecurringSyncAt,
			&i.ConnectionIsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const plaidCredentialSecretByID = `-- name: PlaidCredentialSecretByID :one
SELECT id, client_id, secret, environment, label
FROM plaid_credentials
WHERE id = ?1
`

type PlaidCredentialSecretByIDParams struct {
	ID int64
}

type PlaidCredentialSecretByIDRow struct {
	ID          int64
	ClientID    string
	Secret      string
	Environment string
	Label       *string
}

// Used only by admin/db.Store.CredentialByID, the one place the secret is read back out for Plaid client construction.
func (q *Queries) PlaidCredentialSecretByID(ctx context.Context, arg PlaidCredentialSecretByIDParams) (PlaidCredentialSecretByIDRow, error) {
	row := q.db.QueryRowContext(ctx, plaidCredentialSecretByID, arg.ID)
	var i PlaidCredentialSecretByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Secret,
		&i.Environment,
		&i.Label,
	)
	return i, err
}

const plaidItemsDue = `-- name: PlaidItemsDue :many
SELECT
  pi.access_token, pi.created_at, pi.credential_id, pi.cursor, pi.external_id, pi.health_error_code, pi.health_error_message, pi.health_state, pi.health_updated_at, pi.id, pi.institution_id, pi.last_recurring_synced_at, pi.last_synced_at, pi.logo_url, pi.next_balance_sync_at, pi.next_recurring_sync_at, pi.next_sync_at, pi.plaid_investments_enabled, pi.plaid_liabilities_enabled, pi.recurring_sync_cron, pi.sync_cron, pi.updated_at,
  c.owner_id,
  o.name AS owner,
  c.name AS institution_name
FROM plaid_items pi
JOIN connections c ON c.source_id = pi.id AND c.source_table = 'plaid_items'
JOIN owners o ON o.id = c.owner_id
WHERE TRUE
  AND c.is_active = 1 -- :if $4
  AND pi.id = ?1 -- :if $1
  AND COALESCE(CASE CAST(?2 AS TEXT) WHEN 'sync' THEN pi.next_sync_at WHEN 'recurring' THEN pi.next_recurring_sync_at ELSE pi.next_balance_sync_at END, ?3) <= ?3 -- :if $4
  AND (
    CAST(?2 AS TEXT) != 'balance'
    OR NOT EXISTS (
      SELECT 1
      FROM accounts a
      WHERE a.connection_id = c.id
        AND a.manual = 0
    )
    OR EXISTS (
      SELECT 1
      FROM accounts a
      WHERE a.connection_id = c.id
        AND a.manual = 0
        AND a.is_closed = 0
    )
  )
ORDER BY pi.id
`

var _plaidItemsDueDynQ = dynCompile(plaidItemsDue)

type PlaidItemsDueParams struct {
	ID      *int64
	Kind    string
	Now     *time.Time
	DueOnly bool
}

type PlaidItemsDueRow struct {
	PlaidItem       PlaidItem
	OwnerID         int64
	Owner           string
	InstitutionName *string
}

// Used by Plaid sync loops to select due active items, and by one-off item sync to fetch a single item secret.
func (q *Queries) PlaidItemsDue(ctx context.Context, arg PlaidItemsDueParams) ([]PlaidItemsDueRow, error) {

	dynQuery, dynArgs := _plaidItemsDueDynQ.Build([]any{arg.ID, arg.Kind, arg.Now, arg.DueOnly})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaidItemsDueRow{}
	for rows.Next() {
		var i PlaidItemsDueRow
		if err := rows.Scan(
			&i.PlaidItem.AccessToken,
			&i.PlaidItem.CreatedAt,
			&i.PlaidItem.CredentialID,
			&i.PlaidItem.Cursor,
			&i.PlaidItem.ExternalID,
			&i.PlaidItem.HealthErrorCode,
			&i.PlaidItem.HealthErrorMessage,
			&i.PlaidItem.HealthState,
			&i.PlaidItem.HealthUpdatedAt,
			&i.PlaidItem.ID,
			&i.PlaidItem.InstitutionID,
			&i.PlaidItem.LastRecurringSyncedAt,
			&i.PlaidItem.LastSyncedAt,
			&i.PlaidItem.LogoUrl,
			&i.PlaidItem.NextBalanceSyncAt,
			&i.PlaidItem.NextRecurringSyncAt,
			&i.PlaidItem.NextSyncAt,
			&i.PlaidItem.PlaidInvestmentsEnabled,
			&i.PlaidItem.PlaidLiabilitiesEnabled,
			&i.PlaidItem.RecurringSyncCron,
			&i.PlaidItem.SyncCron,
			&i.PlaidItem.UpdatedAt,
			&i.OwnerID,
			&i.Owner,
			&i.InstitutionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const plaidItemsMissingLogoURL = `-- name: PlaidItemsMissingLogoURL :many
SELECT
  pi.id,
  pi.external_id,
  pi.credential_id,
  pi.institution_id
FROM plaid_items pi
WHERE pi.logo_url IS NULL
  AND pi.institution_id IS NOT NULL
  AND pi.institution_id <> ''
ORDER BY pi.id
`

type PlaidItemsMissingLogoURLRow struct {
	ID            int64
	ExternalID    string
	CredentialID  int64
	InstitutionID *string
}

// Used by a background maintenance loop that backfills missing Plaid institution logos.
func (q *Queries) PlaidItemsMissingLogoURL(ctx context.Context) ([]PlaidItemsMissingLogoURLRow, error) {
	rows, err := q.db.QueryContext(ctx, plaidItemsMissingLogoURL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaidItemsMissingLogoURLRow{}
	for rows.Next() {
		var i PlaidItemsMissingLogoURLRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.CredentialID,
			&i.InstitutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetItemSync = `-- name: ResetItemSync :exec
UPDATE plaid_items
SET cursor = NULL,
    last_synced_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?1
`

type ResetItemSyncParams struct {
	ID int64
}

// Used by ExchangePublicToken on item re-link to clear the stored cursor, forcing a full re-sync.
func (q *Queries) ResetItemSync(ctx context.Context, arg ResetItemSyncParams) error {
	_, err := q.db.ExecContext(ctx, resetItemSync, arg.ID)
	return err
}

const setItemBalanceSynced = `-- name: SetItemBalanceSynced :exec
UPDATE plaid_items
SET next_balance_sync_at = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type SetItemBalanceSyncedParams struct {
	NextBalanceSyncAt *time.Time
	ID                int64
}

// Used by internal/wealth's Plaid balance-sync adapter to schedule an item's next balance sync.
func (q *Queries) SetItemBalanceSynced(ctx context.Context, arg SetItemBalanceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setItemBalanceSynced, arg.NextBalanceSyncAt, arg.ID)
	return err
}

const setItemRecurringSynced = `-- name: SetItemRecurringSynced :exec
UPDATE plaid_items
SET last_recurring_synced_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
    next_recurring_sync_at = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type SetItemRecurringSyncedParams struct {
	NextRecurringSyncAt *time.Time
	ID                  int64
}

// Used by internal/transactions/plaid's background recurring-charge sync loop to record a completed pass and schedule the next one.
// last_recurring_synced_at is intentionally write-only audit metadata; scheduling uses next_recurring_sync_at.
func (q *Queries) SetItemRecurringSynced(ctx context.Context, arg SetItemRecurringSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setItemRecurringSynced, arg.NextRecurringSyncAt, arg.ID)
	return err
}

const setPlaidItemHealth = `-- name: SetPlaidItemHealth :exec
UPDATE plaid_items
SET health_state = ?1,
    health_error_code = ?2,
    health_error_message = ?3,
    health_updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?4
`

type SetPlaidItemHealthParams struct {
	HealthState        string
	HealthErrorCode    *string
	HealthErrorMessage *string
	ID                 int64
}

// Used by internal/transactions/plaid's health monitor to record Plaid API health/error state changes for an item.
func (q *Queries) SetPlaidItemHealth(ctx context.Context, arg SetPlaidItemHealthParams) error {
	_, err := q.db.ExecContext(ctx, setPlaidItemHealth,
		arg.HealthState,
		arg.HealthErrorCode,
		arg.HealthErrorMessage,
		arg.ID,
	)
	return err
}

const setPlaidItemLogoURL = `-- name: SetPlaidItemLogoURL :exec
UPDATE plaid_items
SET logo_url = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type SetPlaidItemLogoURLParams struct {
	LogoUrl *string
	ID      int64
}

// Used by the same institution-logo backfill loop to persist a fetched logo URL.
func (q *Queries) SetPlaidItemLogoURL(ctx context.Context, arg SetPlaidItemLogoURLParams) error {
	_, err := q.db.ExecContext(ctx, setPlaidItemLogoURL, arg.LogoUrl, arg.ID)
	return err
}

const setPlaidProductFlags = `-- name: SetPlaidProductFlags :exec
UPDATE plaid_items
SET plaid_investments_enabled = ?1,
    plaid_liabilities_enabled = ?2,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
`

type SetPlaidProductFlagsParams struct {
	PlaidInvestmentsEnabled bool
	PlaidLiabilitiesEnabled bool
	ID                      int64
}

// Used by the Plaid link/link-update flow to toggle product availability for an item.
func (q *Queries) SetPlaidProductFlags(ctx context.Context, arg SetPlaidProductFlagsParams) error {
	_, err := q.db.ExecContext(ctx, setPlaidProductFlags, arg.PlaidInvestmentsEnabled, arg.PlaidLiabilitiesEnabled, arg.ID)
	return err
}

const setSyncCursor = `-- name: SetSyncCursor :exec
UPDATE plaid_items
SET cursor = CASE WHEN CAST(?1 AS BOOLEAN) = 1 THEN ?2 ELSE cursor END,
    next_sync_at = ?3,
    last_synced_at = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?4
`

type SetSyncCursorParams struct {
	SetCursor  bool
	Cursor     *string
	NextSyncAt *time.Time
	ID         int64
}

// Used by internal/transactions/plaid's background /transactions/sync loop to persist the new cursor and schedule the next sync.
func (q *Queries) SetSyncCursor(ctx context.Context, arg SetSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, setSyncCursor,
		arg.SetCursor,
		arg.Cursor,
		arg.NextSyncAt,
		arg.ID,
	)
	return err
}

const syncCursor = `-- name: SyncCursor :one
SELECT cursor
FROM plaid_items
WHERE id = ?1
`

type SyncCursorParams struct {
	ID int64
}

// Used by internal/transactions/plaid's background /transactions/sync loop to read the stored cursor before polling.
func (q *Queries) SyncCursor(ctx context.Context, arg SyncCursorParams) (*string, error) {
	row := q.db.QueryRowContext(ctx, syncCursor, arg.ID)
	var cursor *string
	err := row.Scan(&cursor)
	return cursor, err
}

const updatePlaidCredential = `-- name: UpdatePlaidCredential :execrows
UPDATE plaid_credentials
SET secret = ?1,
    environment = ?2
WHERE id = ?3
`

type UpdatePlaidCredentialParams struct {
	Secret      string
	Environment string
	ID          int64
}

// Used by GraphQL mutation updatePlaidCredential (admin.graphql) via admin/db.Store.UpdatePlaidCredential.
func (q *Queries) UpdatePlaidCredential(ctx context.Context, arg UpdatePlaidCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlaidCredential, arg.Secret, arg.Environment, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPlaidItem = `-- name: UpsertPlaidItem :one
INSERT INTO plaid_items (
  external_id, credential_id, access_token, institution_id,
  logo_url,
  next_sync_at, next_recurring_sync_at, next_balance_sync_at,
  plaid_investments_enabled, plaid_liabilities_enabled, health_state, health_updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5,
  ?6, ?7, ?8,
  ?9, ?10, 'HEALTHY', strftime('%Y-%m-%dT%H:%M:%SZ','now')
)
ON CONFLICT(external_id) DO UPDATE SET
  credential_id = excluded.credential_id,
  access_token = excluded.access_token,
  institution_id = excluded.institution_id,
  logo_url = COALESCE(excluded.logo_url, plaid_items.logo_url),
  plaid_investments_enabled = excluded.plaid_investments_enabled,
  plaid_liabilities_enabled = excluded.plaid_liabilities_enabled,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertPlaidItemParams struct {
	ExternalID              string
	CredentialID            int64
	AccessToken             string
	InstitutionID           *string
	LogoUrl                 *string
	NextSyncAt              *time.Time
	NextRecurringSyncAt     *time.Time
	NextBalanceSyncAt       *time.Time
	PlaidInvestmentsEnabled bool
	PlaidLiabilitiesEnabled bool
}

// Used by accounts/db.Store.UpsertPlaidItem during the Plaid link flow (exchangePublicToken mutation) and link-update handling to upsert the plaid_items row.
func (q *Queries) UpsertPlaidItem(ctx context.Context, arg UpsertPlaidItemParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertPlaidItem,
		arg.ExternalID,
		arg.CredentialID,
		arg.AccessToken,
		arg.InstitutionID,
		arg.LogoUrl,
		arg.NextSyncAt,
		arg.NextRecurringSyncAt,
		arg.NextBalanceSyncAt,
		arg.PlaidInvestmentsEnabled,
		arg.PlaidLiabilitiesEnabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
