// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portfolio.sql

package dbgen

import (
	"context"
	"strings"
	"time"
)

const assetAnalysisReportsByAssetIDs = `-- name: AssetAnalysisReportsByAssetIDs :many
SELECT r.asset_id, r.bond_position, r.cash_position, r.category, r.convertible_position, r.created_at, r.equity_sector, r.fetched_at, r.group_name, r.other_position, r.preferred_position, r.sector_basic_materials, r.sector_communication_services, r.sector_consumer_cyclical, r.sector_consumer_defensive, r.sector_energy, r.sector_financial_services, r.sector_healthcare, r.sector_industrials, r.sector_real_estate, r.sector_technology, r.sector_utilities, r.stock_position
FROM asset_analysis_reports r
WHERE r.asset_id IN (/*SLICE:asset_ids*/?)
`

type AssetAnalysisReportsByAssetIDsParams struct {
	AssetIds []int64
}

type AssetAnalysisReportsByAssetIDsRow struct {
	AssetAnalysisReport AssetAnalysisReport
}

// Used by internal/portfolio to resolve analysis reports for a set of assets when building the GraphQL analysis (portfolio.graphql) response.
func (q *Queries) AssetAnalysisReportsByAssetIDs(ctx context.Context, arg AssetAnalysisReportsByAssetIDsParams) ([]AssetAnalysisReportsByAssetIDsRow, error) {
	query := assetAnalysisReportsByAssetIDs
	var queryParams []interface{}
	if len(arg.AssetIds) > 0 {
		for _, v := range arg.AssetIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", strings.Repeat(",?", len(arg.AssetIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:asset_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetAnalysisReportsByAssetIDsRow{}
	for rows.Next() {
		var i AssetAnalysisReportsByAssetIDsRow
		if err := rows.Scan(
			&i.AssetAnalysisReport.AssetID,
			&i.AssetAnalysisReport.BondPosition,
			&i.AssetAnalysisReport.CashPosition,
			&i.AssetAnalysisReport.Category,
			&i.AssetAnalysisReport.ConvertiblePosition,
			&i.AssetAnalysisReport.CreatedAt,
			&i.AssetAnalysisReport.EquitySector,
			&i.AssetAnalysisReport.FetchedAt,
			&i.AssetAnalysisReport.GroupName,
			&i.AssetAnalysisReport.OtherPosition,
			&i.AssetAnalysisReport.PreferredPosition,
			&i.AssetAnalysisReport.SectorBasicMaterials,
			&i.AssetAnalysisReport.SectorCommunicationServices,
			&i.AssetAnalysisReport.SectorConsumerCyclical,
			&i.AssetAnalysisReport.SectorConsumerDefensive,
			&i.AssetAnalysisReport.SectorEnergy,
			&i.AssetAnalysisReport.SectorFinancialServices,
			&i.AssetAnalysisReport.SectorHealthcare,
			&i.AssetAnalysisReport.SectorIndustrials,
			&i.AssetAnalysisReport.SectorRealEstate,
			&i.AssetAnalysisReport.SectorTechnology,
			&i.AssetAnalysisReport.SectorUtilities,
			&i.AssetAnalysisReport.StockPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicAssetsForAnalysisReport = `-- name: PublicAssetsForAnalysisReport :many
SELECT assets.id, assets.identifier, assets.tracking_ticker, assets.investment_connectivity
FROM assets
LEFT JOIN asset_analysis_reports r ON r.asset_id = assets.id
WHERE assets.asset_type = 'SECURITY'
  AND assets.classifier = 'PUBLIC'
  AND assets.investment_connectivity NOT IN ('IGNORE', 'NOT_FOUND')
  AND (r.asset_id IS NULL OR r.fetched_at < ?1)
ORDER BY assets.identifier
`

type PublicAssetsForAnalysisReportParams struct {
	OlderThan time.Time
}

type PublicAssetsForAnalysisReportRow struct {
	ID                     int64
	Identifier             string
	TrackingTicker         *string
	InvestmentConnectivity string
}

// Used by internal/portfolio's background sync job to find public securities that are missing an analysis report or whose report has gone stale.
func (q *Queries) PublicAssetsForAnalysisReport(ctx context.Context, arg PublicAssetsForAnalysisReportParams) ([]PublicAssetsForAnalysisReportRow, error) {
	rows, err := q.db.QueryContext(ctx, publicAssetsForAnalysisReport, arg.OlderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicAssetsForAnalysisReportRow{}
	for rows.Next() {
		var i PublicAssetsForAnalysisReportRow
		if err := rows.Scan(
			&i.ID,
			&i.Identifier,
			&i.TrackingTicker,
			&i.InvestmentConnectivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAssetAnalysisReport = `-- name: UpsertAssetAnalysisReport :exec
INSERT INTO asset_analysis_reports (
  asset_id,
  category,
  group_name,
  cash_position,
  stock_position,
  bond_position,
  preferred_position,
  convertible_position,
  other_position,
  sector_real_estate,
  sector_consumer_cyclical,
  sector_basic_materials,
  sector_consumer_defensive,
  sector_technology,
  sector_communication_services,
  sector_financial_services,
  sector_utilities,
  sector_industrials,
  sector_energy,
  sector_healthcare,
  equity_sector,
  fetched_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17,
  ?18,
  ?19,
  ?20,
  ?21,
  ?22
)
ON CONFLICT(asset_id) DO UPDATE SET
  category = excluded.category,
  group_name = excluded.group_name,
  cash_position = excluded.cash_position,
  stock_position = excluded.stock_position,
  bond_position = excluded.bond_position,
  preferred_position = excluded.preferred_position,
  convertible_position = excluded.convertible_position,
  other_position = excluded.other_position,
  sector_real_estate = excluded.sector_real_estate,
  sector_consumer_cyclical = excluded.sector_consumer_cyclical,
  sector_basic_materials = excluded.sector_basic_materials,
  sector_consumer_defensive = excluded.sector_consumer_defensive,
  sector_technology = excluded.sector_technology,
  sector_communication_services = excluded.sector_communication_services,
  sector_financial_services = excluded.sector_financial_services,
  sector_utilities = excluded.sector_utilities,
  sector_industrials = excluded.sector_industrials,
  sector_energy = excluded.sector_energy,
  sector_healthcare = excluded.sector_healthcare,
  equity_sector = excluded.equity_sector,
  fetched_at = excluded.fetched_at
`

type UpsertAssetAnalysisReportParams struct {
	AssetID                     int64
	Category                    string
	GroupName                   string
	CashPosition                float64
	StockPosition               float64
	BondPosition                float64
	PreferredPosition           float64
	ConvertiblePosition         float64
	OtherPosition               float64
	SectorRealEstate            float64
	SectorConsumerCyclical      float64
	SectorBasicMaterials        float64
	SectorConsumerDefensive     float64
	SectorTechnology            float64
	SectorCommunicationServices float64
	SectorFinancialServices     float64
	SectorUtilities             float64
	SectorIndustrials           float64
	SectorEnergy                float64
	SectorHealthcare            float64
	EquitySector                *string
	FetchedAt                   time.Time
}

// Used by internal/portfolio's background backfill/sync job (internal/portfolio/sync.go) to store fund/equity composition and sector data fetched from Morningstar.
func (q *Queries) UpsertAssetAnalysisReport(ctx context.Context, arg UpsertAssetAnalysisReportParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssetAnalysisReport,
		arg.AssetID,
		arg.Category,
		arg.GroupName,
		arg.CashPosition,
		arg.StockPosition,
		arg.BondPosition,
		arg.PreferredPosition,
		arg.ConvertiblePosition,
		arg.OtherPosition,
		arg.SectorRealEstate,
		arg.SectorConsumerCyclical,
		arg.SectorBasicMaterials,
		arg.SectorConsumerDefensive,
		arg.SectorTechnology,
		arg.SectorCommunicationServices,
		arg.SectorFinancialServices,
		arg.SectorUtilities,
		arg.SectorIndustrials,
		arg.SectorEnergy,
		arg.SectorHealthcare,
		arg.EquitySector,
		arg.FetchedAt,
	)
	return err
}
