// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: real_estate.sql

package dbgen

import (
	"context"
)

const activeRealEstate = `-- name: ActiveRealEstate :many
SELECT
  a.id AS asset_id,
  acc.id AS account_id,
  c.id AS connection_id,
  c.owner_id,
  COALESCE(c.name, acc.name) AS name,
  a.additional
FROM connections c
JOIN assets a ON a.asset_type = 'REAL_ESTATE' AND a.id = c.source_id
JOIN accounts acc ON acc.connection_id = c.id
WHERE TRUE
  AND acc.is_closed = 0 -- :if $2
  AND c.id = ?1 -- :if $1
  AND c.source_table = 'assets'
  AND c.is_active = 1
  AND acc.manual = 0
  AND acc.type = 'PROPERTY'
ORDER BY acc.created_at
`

var _activeRealEstateDynQ = dynCompile(activeRealEstate)

type ActiveRealEstateParams struct {
	ConnectionID *int64
	OpenOnly     bool
}

type ActiveRealEstateRow struct {
	AssetID      int64
	AccountID    int64
	ConnectionID int64
	OwnerID      int64
	Name         string
	Additional   *string
}

// Used by wealth/db.Store.RealEstateByConnectionID (lookup, edit, delete) and
// ActiveRealEstate (periodic manual-snapshot sync, which additionally excludes
// closed accounts: the shared snapshot sink rejects closed-account writes, so
// syncing one would only discard the result).
func (q *Queries) ActiveRealEstate(ctx context.Context, arg ActiveRealEstateParams) ([]ActiveRealEstateRow, error) {

	dynQuery, dynArgs := _activeRealEstateDynQ.Build([]any{arg.ConnectionID, arg.OpenOnly})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveRealEstateRow{}
	for rows.Next() {
		var i ActiveRealEstateRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AccountID,
			&i.ConnectionID,
			&i.OwnerID,
			&i.Name,
			&i.Additional,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRealEstateAsset = `-- name: InsertRealEstateAsset :one
INSERT INTO assets (asset_type, identifier, name, classifier, additional)
VALUES ('REAL_ESTATE', ?1, ?2, 'REAL_ESTATE', ?3)
RETURNING id
`

type InsertRealEstateAssetParams struct {
	Identifier string
	Name       *string
	Additional *string
}

// Used by wealth/db.Store.CreateRealEstate (GraphQL mutation linkRealEstate) to create the REAL_ESTATE asset row.
func (q *Queries) InsertRealEstateAsset(ctx context.Context, arg InsertRealEstateAssetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertRealEstateAsset, arg.Identifier, arg.Name, arg.Additional)
	var id int64
	err := row.Scan(&id)
	return id, err
}
