// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_charges.sql

package dbgen

import (
	"context"
	"strings"

	"tallyo/internal/money"
)

const deleteRecurringChargeTransactions = `-- name: DeleteRecurringChargeTransactions :exec
DELETE FROM recurring_charge_transactions
WHERE charge_id = ?1
`

type DeleteRecurringChargeTransactionsParams struct {
	ChargeID int64
}

// Used by transactions/db's recurring-charge sync to clear a charge's transaction associations before re-linking the current set.
func (q *Queries) DeleteRecurringChargeTransactions(ctx context.Context, arg DeleteRecurringChargeTransactionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecurringChargeTransactions, arg.ChargeID)
	return err
}

const insertRecurringChargeTransactions = `-- name: InsertRecurringChargeTransactions :exec
INSERT OR IGNORE INTO recurring_charge_transactions (charge_id, transaction_id)
SELECT ?1, id
FROM transactions
WHERE source = 'plaid'
  AND external_id IN (/*SLICE:plaid_txn_ids*/?)
`

type InsertRecurringChargeTransactionsParams struct {
	ChargeID    int64
	PlaidTxnIds []string
}

// Used by transactions/db's recurring-charge sync to associate Plaid transactions with a recurring charge.
func (q *Queries) InsertRecurringChargeTransactions(ctx context.Context, arg InsertRecurringChargeTransactionsParams) error {
	query := insertRecurringChargeTransactions
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ChargeID)
	if len(arg.PlaidTxnIds) > 0 {
		for _, v := range arg.PlaidTxnIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:plaid_txn_ids*/?", strings.Repeat(",?", len(arg.PlaidTxnIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:plaid_txn_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listRecurringCharges = `-- name: ListRecurringCharges :many
SELECT rc.account_id, rc.average_amount_cents, rc.description, rc.external_id, rc.first_date, rc.frequency, rc.id, rc.is_active, rc.is_user_modified, rc.last_amount_cents, rc.last_date, rc.merchant_name, rc.status, rc.updated_at
FROM recurring_charges rc
JOIN accounts ON accounts.id = rc.account_id
WHERE TRUE
  AND rc.id = ?1 -- :if $1
  AND rc.status != 'TOMBSTONED'
  AND accounts.is_hidden = 0
ORDER BY rc.last_date DESC
`

var _listRecurringChargesDynQ = dynCompile(listRecurringCharges)

type ListRecurringChargesParams struct {
	ID *int64
}

// Used by GraphQL query recurringCharges (transactions.graphql) via transactions/db.Store.
func (q *Queries) ListRecurringCharges(ctx context.Context, arg ListRecurringChargesParams) ([]RecurringCharge, error) {

	dynQuery, dynArgs := _listRecurringChargesDynQ.Build([]any{arg.ID})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringCharge{}
	for rows.Next() {
		var i RecurringCharge
		if err := rows.Scan(
			&i.AccountID,
			&i.AverageAmountCents,
			&i.Description,
			&i.ExternalID,
			&i.FirstDate,
			&i.Frequency,
			&i.ID,
			&i.IsActive,
			&i.IsUserModified,
			&i.LastAmountCents,
			&i.LastDate,
			&i.MerchantName,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const majorityCategoriesForRecurringCharges = `-- name: MajorityCategoriesForRecurringCharges :many
WITH ranked AS (
  SELECT
    rct.charge_id,
    cr.cat_id,
    ROW_NUMBER() OVER (
      PARTITION BY rct.charge_id
      ORDER BY COUNT(*) DESC, MAX(t.datetime) DESC
    ) AS rn
  FROM recurring_charge_transactions rct
  JOIN transactions t ON t.id = rct.transaction_id
  JOIN category_rows cr ON cr.cat_id = t.category_id
  WHERE rct.charge_id IN (/*SLICE:charge_ids*/?)
  GROUP BY rct.charge_id, cr.cat_id
)
SELECT ranked.charge_id, cr.cat_id, cr.cat_name, cr.cat_emoji, cr.group_name, cr.group_emoji, cr.group_kind, cr.sort_order, cr.group_id, cr.group_sort_order, cr.plaid_pfc2_codes
FROM ranked
JOIN category_rows cr ON cr.cat_id = ranked.cat_id
WHERE ranked.rn = 1
ORDER BY ranked.charge_id
`

type MajorityCategoriesForRecurringChargesParams struct {
	ChargeIds []int64
}

type MajorityCategoriesForRecurringChargesRow struct {
	ChargeID    int64
	CategoryRow CategoryRow
}

// Used by the RecurringCharge.category GraphQL field's dataloader (internal/graph/loaders.go) to compute each charge's most-common transaction category.
func (q *Queries) MajorityCategoriesForRecurringCharges(ctx context.Context, arg MajorityCategoriesForRecurringChargesParams) ([]MajorityCategoriesForRecurringChargesRow, error) {
	query := majorityCategoriesForRecurringCharges
	var queryParams []interface{}
	if len(arg.ChargeIds) > 0 {
		for _, v := range arg.ChargeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:charge_ids*/?", strings.Repeat(",?", len(arg.ChargeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:charge_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MajorityCategoriesForRecurringChargesRow{}
	for rows.Next() {
		var i MajorityCategoriesForRecurringChargesRow
		if err := rows.Scan(
			&i.ChargeID,
			&i.CategoryRow.CatID,
			&i.CategoryRow.CatName,
			&i.CategoryRow.CatEmoji,
			&i.CategoryRow.GroupName,
			&i.CategoryRow.GroupEmoji,
			&i.CategoryRow.GroupKind,
			&i.CategoryRow.SortOrder,
			&i.CategoryRow.GroupID,
			&i.CategoryRow.GroupSortOrder,
			&i.CategoryRow.PlaidPfc2Codes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recurringChargeTransactionIDsByChargeIDs = `-- name: RecurringChargeTransactionIDsByChargeIDs :many
SELECT rct.charge_id, rct.transaction_id
FROM recurring_charge_transactions rct
WHERE rct.charge_id IN (/*SLICE:charge_ids*/?)
ORDER BY rct.charge_id
`

type RecurringChargeTransactionIDsByChargeIDsParams struct {
	ChargeIds []int64
}

// Used by the RecurringCharge.transactions GraphQL field's dataloader (internal/graph/loaders.go) to batch-load associated transaction IDs.
func (q *Queries) RecurringChargeTransactionIDsByChargeIDs(ctx context.Context, arg RecurringChargeTransactionIDsByChargeIDsParams) ([]RecurringChargeTransaction, error) {
	query := recurringChargeTransactionIDsByChargeIDs
	var queryParams []interface{}
	if len(arg.ChargeIds) > 0 {
		for _, v := range arg.ChargeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:charge_ids*/?", strings.Repeat(",?", len(arg.ChargeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:charge_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringChargeTransaction{}
	for rows.Next() {
		var i RecurringChargeTransaction
		if err := rows.Scan(&i.ChargeID, &i.TransactionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecurringCharge = `-- name: UpsertRecurringCharge :one
INSERT INTO recurring_charges (
  external_id, account_id, description, merchant_name, frequency, status, is_active,
  average_amount_cents, last_amount_cents, first_date, last_date, is_user_modified, updated_at
) VALUES (
  ?1, ?2, ?3, ?4, ?5, ?6, ?7,
  ?8, ?9, ?10, ?11, ?12,
  strftime('%Y-%m-%dT%H:%M:%SZ','now')
)
ON CONFLICT(external_id) DO UPDATE SET
  account_id = excluded.account_id,
  description = excluded.description,
  merchant_name = excluded.merchant_name,
  frequency = excluded.frequency,
  status = excluded.status,
  is_active = excluded.is_active,
  average_amount_cents = excluded.average_amount_cents,
  last_amount_cents = excluded.last_amount_cents,
  first_date = excluded.first_date,
  last_date = excluded.last_date,
  is_user_modified = excluded.is_user_modified,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertRecurringChargeParams struct {
	ExternalID         string
	AccountID          int64
	Description        string
	MerchantName       *string
	Frequency          string
	Status             string
	IsActive           bool
	AverageAmountCents money.Cents
	LastAmountCents    money.Cents
	FirstDate          string
	LastDate           string
	IsUserModified     bool
}

// Used by internal/transactions/plaid's background recurring-charge sync loop to upsert detected recurring charges.
func (q *Queries) UpsertRecurringCharge(ctx context.Context, arg UpsertRecurringChargeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertRecurringCharge,
		arg.ExternalID,
		arg.AccountID,
		arg.Description,
		arg.MerchantName,
		arg.Frequency,
		arg.Status,
		arg.IsActive,
		arg.AverageAmountCents,
		arg.LastAmountCents,
		arg.FirstDate,
		arg.LastDate,
		arg.IsUserModified,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
