// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package dbgen

import (
	"context"
)

const triggerRetentionSweep = `-- name: TriggerRetentionSweep :exec
UPDATE retention_sweeps
SET trigger_sweep = 1
`

// Used by internal/database's retention sweep (background job and manual CLI trigger) to touch every retention_sweeps row.
// Intentionally touches every sweep row; each trigger self-selects on NEW.id.
func (q *Queries) TriggerRetentionSweep(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, triggerRetentionSweep)
	return err
}
