// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package dbgen

import (
	"context"
	"strings"

	"tallyo/internal/money"
)

const accountsByRuleIDs = `-- name: AccountsByRuleIDs :many
SELECT
  ra.rule_id,
  a.connection_id, a.created_at, a.external_id, a.id, a.is_closed, a.is_hidden, a.manual, a.mask, a.name, a.needs_review, a.notes, a.owner_id, a.review_reason, a.subtype, a.type, a.updated_at,
  o.name AS owner_name
FROM accounts a
JOIN owners o ON o.id = a.owner_id
JOIN rule_accounts ra ON ra.account_id = a.id
WHERE ra.rule_id IN (/*SLICE:rule_ids*/?)
ORDER BY ra.rule_id, o.name, a.name
`

type AccountsByRuleIDsParams struct {
	RuleIds []int64
}

type AccountsByRuleIDsRow struct {
	RuleID    int64
	Account   Account
	OwnerName string
}

// Used by the Rule.accounts GraphQL field's dataloader (internal/graph/loaders.go) to batch-load accounts scoped to each rule.
func (q *Queries) AccountsByRuleIDs(ctx context.Context, arg AccountsByRuleIDsParams) ([]AccountsByRuleIDsRow, error) {
	query := accountsByRuleIDs
	var queryParams []interface{}
	if len(arg.RuleIds) > 0 {
		for _, v := range arg.RuleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:rule_ids*/?", strings.Repeat(",?", len(arg.RuleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:rule_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountsByRuleIDsRow{}
	for rows.Next() {
		var i AccountsByRuleIDsRow
		if err := rows.Scan(
			&i.RuleID,
			&i.Account.ConnectionID,
			&i.Account.CreatedAt,
			&i.Account.ExternalID,
			&i.Account.ID,
			&i.Account.IsClosed,
			&i.Account.IsHidden,
			&i.Account.Manual,
			&i.Account.Mask,
			&i.Account.Name,
			&i.Account.NeedsReview,
			&i.Account.Notes,
			&i.Account.OwnerID,
			&i.Account.ReviewReason,
			&i.Account.Subtype,
			&i.Account.Type,
			&i.Account.UpdatedAt,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRule = `-- name: CreateRule :one
INSERT INTO rules (merchant_pattern, original_pattern, merchant_name, category_id, should_hide, should_be_recurring, amount_min_cents, amount_max_cents, priority)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
RETURNING id
`

type CreateRuleParams struct {
	MerchantPattern   string
	OriginalPattern   string
	MerchantName      *string
	CategoryID        *int64
	ShouldHide        *bool
	ShouldBeRecurring *bool
	AmountMinCents    *money.Cents
	AmountMaxCents    *money.Cents
	Priority          int64
}

// Used by GraphQL mutation createRule via transactions/db.Store.CreateRule.
func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.MerchantPattern,
		arg.OriginalPattern,
		arg.MerchantName,
		arg.CategoryID,
		arg.ShouldHide,
		arg.ShouldBeRecurring,
		arg.AmountMinCents,
		arg.AmountMaxCents,
		arg.Priority,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRule = `-- name: DeleteRule :execrows
DELETE FROM rules
WHERE id = ?1
`

type DeleteRuleParams struct {
	ID int64
}

// Used by GraphQL mutation deleteRule via transactions/db.Store.DeleteRule.
func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRule, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRuleAccounts = `-- name: DeleteRuleAccounts :exec
DELETE FROM rule_accounts
WHERE rule_id = ?1
`

type DeleteRuleAccountsParams struct {
	RuleID int64
}

// Used by transactions/db.Store.UpdateRule to clear a rule's account associations before re-inserting the updated set, in the same transaction as the rule UPDATE.
func (q *Queries) DeleteRuleAccounts(ctx context.Context, arg DeleteRuleAccountsParams) error {
	_, err := q.db.ExecContext(ctx, deleteRuleAccounts, arg.RuleID)
	return err
}

const deleteRuleTags = `-- name: DeleteRuleTags :exec
DELETE FROM rule_tags
WHERE rule_id = ?1
`

type DeleteRuleTagsParams struct {
	RuleID int64
}

// Used by transactions/db.Store.UpdateRule to clear a rule's tag associations before re-inserting the updated set.
func (q *Queries) DeleteRuleTags(ctx context.Context, arg DeleteRuleTagsParams) error {
	_, err := q.db.ExecContext(ctx, deleteRuleTags, arg.RuleID)
	return err
}

const insertRuleAccount = `-- name: InsertRuleAccount :exec
INSERT INTO rule_accounts (rule_id, account_id)
VALUES (?1, ?2)
`

type InsertRuleAccountParams struct {
	RuleID    int64
	AccountID int64
}

// Used by transactions/db.Store.CreateRule/UpdateRule to associate a rule with a specific account.
func (q *Queries) InsertRuleAccount(ctx context.Context, arg InsertRuleAccountParams) error {
	_, err := q.db.ExecContext(ctx, insertRuleAccount, arg.RuleID, arg.AccountID)
	return err
}

const insertRuleTag = `-- name: InsertRuleTag :exec
INSERT OR IGNORE INTO rule_tags (rule_id, tag_id)
VALUES (?1, ?2)
`

type InsertRuleTagParams struct {
	RuleID int64
	TagID  int64
}

// Used by transactions/db.Store.CreateRule/UpdateRule to associate a tag with a rule.
func (q *Queries) InsertRuleTag(ctx context.Context, arg InsertRuleTagParams) error {
	_, err := q.db.ExecContext(ctx, insertRuleTag, arg.RuleID, arg.TagID)
	return err
}

const listRules = `-- name: ListRules :many
SELECT
  r.amount_max_cents, r.amount_min_cents, r.category_id, r.created_at, r.id, r.merchant_name, r.merchant_pattern, r.original_pattern, r.priority, r.should_be_recurring, r.should_hide,
  cr.cat_id,
  cr.cat_name,
  cr.cat_emoji,
  cr.group_name,
  cr.group_emoji,
  cr.group_kind,
  cr.sort_order,
  cr.plaid_pfc2_codes
FROM rules r
LEFT JOIN category_rows cr ON cr.cat_id = r.category_id
WHERE TRUE
  AND r.id = ?1 -- :if $1
  AND instr(lower(r.merchant_pattern), ?2) > 0 -- :if $2
  AND instr(lower(r.original_pattern), ?3) > 0 -- :if $3
  AND (r.amount_max_cents IS NULL OR r.amount_max_cents >= ?4) -- :if $4
  AND (r.amount_min_cents IS NULL OR r.amount_min_cents <= ?5) -- :if $5
  AND EXISTS (SELECT 1 FROM rule_accounts filter_ra WHERE filter_ra.rule_id = r.id AND filter_ra.account_id IN (/*SLICE:account_ids*/?6)) -- :if $6
ORDER BY r.priority DESC, r.id DESC
`

var _listRulesDynQ = dynCompile(listRules)

type ListRulesParams struct {
	ID              *int64
	MerchantPattern *string
	OriginalPattern *string
	AmountMinCents  *money.Cents
	AmountMaxCents  *money.Cents
	AccountIds      []int64
}

type ListRulesRow struct {
	Rule           Rule
	CatID          *int64
	CatName        *string
	CatEmoji       *string
	GroupName      *string
	GroupEmoji     *string
	GroupKind      *string
	SortOrder      *int64
	PlaidPfc2Codes *string
}

// Used by GraphQL rule list/node resolvers and internally by transactions/db.Store.CreateRule/UpdateRule to return rules after mutations.
func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]ListRulesRow, error) {

	dynQuery, dynArgs := _listRulesDynQ.Build([]any{arg.ID, arg.MerchantPattern, arg.OriginalPattern, arg.AmountMinCents, arg.AmountMaxCents, arg.AccountIds})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesRow{}
	for rows.Next() {
		var i ListRulesRow
		if err := rows.Scan(
			&i.Rule.AmountMaxCents,
			&i.Rule.AmountMinCents,
			&i.Rule.CategoryID,
			&i.Rule.CreatedAt,
			&i.Rule.ID,
			&i.Rule.MerchantName,
			&i.Rule.MerchantPattern,
			&i.Rule.OriginalPattern,
			&i.Rule.Priority,
			&i.Rule.ShouldBeRecurring,
			&i.Rule.ShouldHide,
			&i.CatID,
			&i.CatName,
			&i.CatEmoji,
			&i.GroupName,
			&i.GroupEmoji,
			&i.GroupKind,
			&i.SortOrder,
			&i.PlaidPfc2Codes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retroactiveRuleTransactionIDs = `-- name: RetroactiveRuleTransactionIDs :many
SELECT t.id
FROM transactions t
WHERE TRUE
  AND (
        FALSE
        OR instr(lower(coalesce(t.merchant_name, t.original_name, '')), ?1) > 0 -- :if $1
        OR instr(lower(coalesce(t.original_name, '')), ?2) > 0 -- :if $2
      )
  AND t.amount_cents >= ?3 -- :if $3
  AND t.amount_cents <= ?4 -- :if $4
  AND t.account_id IN (/*SLICE:account_ids*/?5) -- :if $5
  -- Trailing unconditional guard: the dynamic-filter plugin drops the ":if"
  -- annotation on a query's final physical WHERE line, silently making that
  -- predicate unconditional (confirmed against the pinned sqlc-gen-go build).
  -- Keeping a real, always-true predicate last avoids that.
  AND TRUE
`

var _retroactiveRuleTransactionIDsDynQ = dynCompile(retroactiveRuleTransactionIDs)

type RetroactiveRuleTransactionIDsParams struct {
	MerchantPattern *string
	OriginalPattern *string
	AmountMin       *money.Cents
	AmountMax       *money.Cents
	AccountIds      []int64
}

// Used by transactions/db rule create/update to collect transaction ids for retroactive
// application; mirrors AutoRuleResult's instr()-based matching.
func (q *Queries) RetroactiveRuleTransactionIDs(ctx context.Context, arg RetroactiveRuleTransactionIDsParams) ([]int64, error) {

	dynQuery, dynArgs := _retroactiveRuleTransactionIDsDynQ.Build([]any{arg.MerchantPattern, arg.OriginalPattern, arg.AmountMin, arg.AmountMax, arg.AccountIds})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsByRuleIDs = `-- name: TagsByRuleIDs :many
SELECT
  rt.rule_id,
  t.color, t.created_at, t.id, t.name, t.transaction_count, t.updated_at
FROM tags t
JOIN rule_tags rt ON rt.tag_id = t.id
WHERE rt.rule_id IN (/*SLICE:rule_ids*/?)
ORDER BY rt.rule_id, t.name, t.id
`

type TagsByRuleIDsParams struct {
	RuleIds []int64
}

type TagsByRuleIDsRow struct {
	RuleID int64
	Tag    Tag
}

// Used by transactions/db.Store to batch-populate rule tags when returning rules via GraphQL.
func (q *Queries) TagsByRuleIDs(ctx context.Context, arg TagsByRuleIDsParams) ([]TagsByRuleIDsRow, error) {
	query := tagsByRuleIDs
	var queryParams []interface{}
	if len(arg.RuleIds) > 0 {
		for _, v := range arg.RuleIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:rule_ids*/?", strings.Repeat(",?", len(arg.RuleIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:rule_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagsByRuleIDsRow{}
	for rows.Next() {
		var i TagsByRuleIDsRow
		if err := rows.Scan(
			&i.RuleID,
			&i.Tag.Color,
			&i.Tag.CreatedAt,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.TransactionCount,
			&i.Tag.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :execrows
UPDATE rules
SET merchant_pattern = ?1,
    original_pattern = ?2,
    merchant_name = ?3,
    category_id = ?4,
    should_hide = ?5,
    should_be_recurring = ?6,
    amount_min_cents = ?7,
    amount_max_cents = ?8,
    priority = ?9
WHERE id = ?10
`

type UpdateRuleParams struct {
	MerchantPattern   string
	OriginalPattern   string
	MerchantName      *string
	CategoryID        *int64
	ShouldHide        *bool
	ShouldBeRecurring *bool
	AmountMinCents    *money.Cents
	AmountMaxCents    *money.Cents
	Priority          int64
	ID                int64
}

// Used by GraphQL mutation updateRule via transactions/db.Store.UpdateRule.
func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRule,
		arg.MerchantPattern,
		arg.OriginalPattern,
		arg.MerchantName,
		arg.CategoryID,
		arg.ShouldHide,
		arg.ShouldBeRecurring,
		arg.AmountMinCents,
		arg.AmountMaxCents,
		arg.Priority,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
