// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: simplefin.sql

package dbgen

import (
	"context"
	"time"
)

const createSimpleFinAccessToken = `-- name: CreateSimpleFinAccessToken :one

INSERT INTO simplefin_access_tokens (access_url, label, owner_id, sync_cron, next_sync_at)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, label, owner_id, last_synced_at, sync_cron, next_sync_at, created_at
`

type CreateSimpleFinAccessTokenParams struct {
	AccessUrl  string
	Label      *string
	OwnerID    int64
	SyncCron   string
	NextSyncAt *time.Time
}

type CreateSimpleFinAccessTokenRow struct {
	ID           int64
	Label        *string
	OwnerID      int64
	LastSyncedAt *time.Time
	SyncCron     string
	NextSyncAt   *time.Time
	CreatedAt    time.Time
}

// ============================================================
// simplefin_access_tokens
// ============================================================
// Used by GraphQL mutation createSimpleFinAccessToken (accounts.graphql) to persist the access URL claimed from a SimpleFIN setup token.
func (q *Queries) CreateSimpleFinAccessToken(ctx context.Context, arg CreateSimpleFinAccessTokenParams) (CreateSimpleFinAccessTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createSimpleFinAccessToken,
		arg.AccessUrl,
		arg.Label,
		arg.OwnerID,
		arg.SyncCron,
		arg.NextSyncAt,
	)
	var i CreateSimpleFinAccessTokenRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.OwnerID,
		&i.LastSyncedAt,
		&i.SyncCron,
		&i.NextSyncAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSimpleFinAccessToken = `-- name: DeleteSimpleFinAccessToken :exec
DELETE FROM simplefin_access_tokens WHERE id = ?1
`

type DeleteSimpleFinAccessTokenParams struct {
	ID int64
}

// Used by GraphQL mutation deleteSimpleFinAccessToken (accounts.graphql) to remove a SimpleFIN credential.
func (q *Queries) DeleteSimpleFinAccessToken(ctx context.Context, arg DeleteSimpleFinAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteSimpleFinAccessToken, arg.ID)
	return err
}

const deleteSimpleFinConnection = `-- name: DeleteSimpleFinConnection :exec
DELETE FROM simplefin_connections WHERE id = ?1
`

type DeleteSimpleFinConnectionParams struct {
	ID int64
}

// Used by accounts/db.Store.DeleteConnection and DeleteSimpleFinAccessToken to remove SimpleFIN connection rows.
func (q *Queries) DeleteSimpleFinConnection(ctx context.Context, arg DeleteSimpleFinConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSimpleFinConnection, arg.ID)
	return err
}

const logSimpleFinSyncBatch = `-- name: LogSimpleFinSyncBatch :exec

INSERT INTO simplefin_sync_log (access_token_id, start_date, added, modified, pending_removed, error)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type LogSimpleFinSyncBatchParams struct {
	AccessTokenID  int64
	StartDate      *string
	Added          string
	Modified       string
	PendingRemoved string
	Error          *string
}

// ============================================================
// simplefin_sync_log
// ============================================================
// Used by internal/transactions' SimpleFIN sync loop to log per-batch added/modified/pending-removed counts after each sync.
func (q *Queries) LogSimpleFinSyncBatch(ctx context.Context, arg LogSimpleFinSyncBatchParams) error {
	_, err := q.db.ExecContext(ctx, logSimpleFinSyncBatch,
		arg.AccessTokenID,
		arg.StartDate,
		arg.Added,
		arg.Modified,
		arg.PendingRemoved,
		arg.Error,
	)
	return err
}

const pendingSimpleFinTransactionIDs = `-- name: PendingSimpleFinTransactionIDs :many
SELECT t.external_id
FROM simplefin_connections sc
CROSS JOIN connections c ON c.source_id = sc.id AND c.source_table = 'simplefin_connections'
CROSS JOIN accounts a ON a.connection_id = c.id
CROSS JOIN transactions t ON t.account_id = a.id
WHERE sc.access_token_id = ?1
  AND t.source = 'simplefin'
  AND t.pending = 1
`

type PendingSimpleFinTransactionIDsParams struct {
	AccessTokenID int64
}

// Used by internal/transactions' SimpleFIN sync loop at the start of each sync to detect which pending transactions the provider has since resolved (posted or removed).
// Provider-first join order: EXPLAIN QUERY PLAN confirms this walks
// idx_simplefin_connections_access_token -> idx_connections_source ->
// idx_accounts_connection -> idx_transactions_account instead of scanning
// every pending SimpleFIN transaction across all tokens.
func (q *Queries) PendingSimpleFinTransactionIDs(ctx context.Context, arg PendingSimpleFinTransactionIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, pendingSimpleFinTransactionIDs, arg.AccessTokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSimpleFinTokenSyncedAt = `-- name: ResetSimpleFinTokenSyncedAt :exec
UPDATE simplefin_access_tokens
SET last_synced_at = NULL,
    next_sync_at   = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
    updated_at     = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?1
`

type ResetSimpleFinTokenSyncedAtParams struct {
	ID int64
}

// Used by GraphQL mutation resetSimpleFinSync (accounts.graphql) via accounts/simplefin.go to force a token's next sync to run immediately.
func (q *Queries) ResetSimpleFinTokenSyncedAt(ctx context.Context, arg ResetSimpleFinTokenSyncedAtParams) error {
	_, err := q.db.ExecContext(ctx, resetSimpleFinTokenSyncedAt, arg.ID)
	return err
}

const setSimpleFinConnectionHealth = `-- name: SetSimpleFinConnectionHealth :exec
UPDATE simplefin_connections
SET health_state         = ?1,
    health_error_message = ?2,
    health_updated_at    = strftime('%Y-%m-%dT%H:%M:%SZ','now'),
    last_synced_at       = ?3,
    updated_at           = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?4
`

type SetSimpleFinConnectionHealthParams struct {
	HealthState        string
	HealthErrorMessage *string
	LastSyncedAt       *time.Time
	ID                 int64
}

// Used by internal/transactions' SimpleFIN sync loop to record connection-level health/error state after each sync cycle.
func (q *Queries) SetSimpleFinConnectionHealth(ctx context.Context, arg SetSimpleFinConnectionHealthParams) error {
	_, err := q.db.ExecContext(ctx, setSimpleFinConnectionHealth,
		arg.HealthState,
		arg.HealthErrorMessage,
		arg.LastSyncedAt,
		arg.ID,
	)
	return err
}

const setSimpleFinTokenBalanceSynced = `-- name: SetSimpleFinTokenBalanceSynced :exec
UPDATE simplefin_access_tokens
SET next_balance_sync_at = ?1,
    updated_at           = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?2
`

type SetSimpleFinTokenBalanceSyncedParams struct {
	NextBalanceSyncAt *time.Time
	ID                int64
}

// Used by internal/wealth's background SimpleFIN balance-sync loop to record a completed pass and schedule the next one.
func (q *Queries) SetSimpleFinTokenBalanceSynced(ctx context.Context, arg SetSimpleFinTokenBalanceSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setSimpleFinTokenBalanceSynced, arg.NextBalanceSyncAt, arg.ID)
	return err
}

const setSimpleFinTokenSynced = `-- name: SetSimpleFinTokenSynced :exec
UPDATE simplefin_access_tokens
SET last_synced_at = ?1,
    next_sync_at   = ?2,
    updated_at     = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
`

type SetSimpleFinTokenSyncedParams struct {
	LastSyncedAt *time.Time
	NextSyncAt   *time.Time
	ID           int64
}

// Used by internal/transactions' background SimpleFIN sync loop to record a completed pass and schedule the next one.
func (q *Queries) SetSimpleFinTokenSynced(ctx context.Context, arg SetSimpleFinTokenSyncedParams) error {
	_, err := q.db.ExecContext(ctx, setSimpleFinTokenSynced, arg.LastSyncedAt, arg.NextSyncAt, arg.ID)
	return err
}

const simpleFinAccessTokens = `-- name: SimpleFinAccessTokens :many
SELECT sat.id, sat.label, sat.owner_id, o.name AS owner_name,
       sat.last_synced_at, sat.sync_cron, sat.next_sync_at, sat.created_at
FROM simplefin_access_tokens sat
JOIN owners o ON o.id = sat.owner_id
WHERE TRUE
  AND sat.id = ?1 -- :if $1
ORDER BY sat.id
`

var _simpleFinAccessTokensDynQ = dynCompile(simpleFinAccessTokens)

type SimpleFinAccessTokensParams struct {
	ID *int64
}

type SimpleFinAccessTokensRow struct {
	ID           int64
	Label        *string
	OwnerID      int64
	OwnerName    string
	LastSyncedAt *time.Time
	SyncCron     string
	NextSyncAt   *time.Time
	CreatedAt    time.Time
}

// Used by GraphQL query simpleFinAccessTokens (accounts.graphql) to list all configured SimpleFIN access tokens, optionally scoped by id.
func (q *Queries) SimpleFinAccessTokens(ctx context.Context, arg SimpleFinAccessTokensParams) ([]SimpleFinAccessTokensRow, error) {

	dynQuery, dynArgs := _simpleFinAccessTokensDynQ.Build([]any{arg.ID})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimpleFinAccessTokensRow{}
	for rows.Next() {
		var i SimpleFinAccessTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.OwnerID,
			&i.OwnerName,
			&i.LastSyncedAt,
			&i.SyncCron,
			&i.NextSyncAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const simpleFinConnections = `-- name: SimpleFinConnections :many
SELECT sc.id, sc.external_id, sc.access_token_id, sc.org_domain, sc.org_url,
       sc.last_synced_at, sc.created_at, sc.updated_at, c.id AS connection_id
FROM simplefin_connections sc
JOIN connections c ON c.source_table = 'simplefin_connections' AND c.source_id = sc.id
WHERE TRUE
  AND sc.access_token_id IN (/*SLICE:access_token_ids*/?1) -- :if $1
  AND sc.id IN (/*SLICE:ids*/?2) -- :if $2
  AND sc.external_id IN (/*SLICE:external_ids*/?3) -- :if $3
ORDER BY sc.access_token_id, sc.id
`

var _simpleFinConnectionsDynQ = dynCompile(simpleFinConnections)

type SimpleFinConnectionsParams struct {
	AccessTokenIds []int64
	Ids            []int64
	ExternalIds    []string
}

type SimpleFinConnectionsRow struct {
	ID            int64
	ExternalID    string
	AccessTokenID int64
	OrgDomain     *string
	OrgUrl        *string
	LastSyncedAt  *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ConnectionID  int64
}

// Used by SimpleFIN token, deletion, and dataloader paths with optional token and connection ID filters.
func (q *Queries) SimpleFinConnections(ctx context.Context, arg SimpleFinConnectionsParams) ([]SimpleFinConnectionsRow, error) {

	dynQuery, dynArgs := _simpleFinConnectionsDynQ.Build([]any{arg.AccessTokenIds, arg.Ids, arg.ExternalIds})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimpleFinConnectionsRow{}
	for rows.Next() {
		var i SimpleFinConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.AccessTokenID,
			&i.OrgDomain,
			&i.OrgUrl,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConnectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const simpleFinTokenSecretByConnID = `-- name: SimpleFinTokenSecretByConnID :one
SELECT sat.id, sat.access_url, sat.owner_id, sat.sync_cron,
       sat.last_synced_at, sat.next_sync_at, sat.next_balance_sync_at
FROM simplefin_access_tokens sat
JOIN simplefin_connections sc ON sc.access_token_id = sat.id
WHERE sc.id = ?1
`

type SimpleFinTokenSecretByConnIDParams struct {
	ConnID int64
}

type SimpleFinTokenSecretByConnIDRow struct {
	ID                int64
	AccessUrl         string
	OwnerID           int64
	SyncCron          string
	LastSyncedAt      *time.Time
	NextSyncAt        *time.Time
	NextBalanceSyncAt *time.Time
}

// Used by internal/transactions/db's SimpleFIN sync to fetch the access URL and schedule for a token, looked up by connection ID.
func (q *Queries) SimpleFinTokenSecretByConnID(ctx context.Context, arg SimpleFinTokenSecretByConnIDParams) (SimpleFinTokenSecretByConnIDRow, error) {
	row := q.db.QueryRowContext(ctx, simpleFinTokenSecretByConnID, arg.ConnID)
	var i SimpleFinTokenSecretByConnIDRow
	err := row.Scan(
		&i.ID,
		&i.AccessUrl,
		&i.OwnerID,
		&i.SyncCron,
		&i.LastSyncedAt,
		&i.NextSyncAt,
		&i.NextBalanceSyncAt,
	)
	return i, err
}

const simpleFinTokenSecrets = `-- name: SimpleFinTokenSecrets :many
SELECT id, access_url, owner_id, sync_cron, last_synced_at, next_sync_at, next_balance_sync_at
FROM simplefin_access_tokens sat
WHERE COALESCE(
    CASE CAST(?1 AS TEXT) WHEN 'sync' THEN next_sync_at ELSE next_balance_sync_at END,
    ?2
  ) <= ?2
  AND (
    CAST(?1 AS TEXT) != 'balance'
    OR NOT EXISTS (
      SELECT 1
      FROM simplefin_connections sc
      JOIN connections c ON c.source_table = 'simplefin_connections' AND c.source_id = sc.id
      JOIN accounts a ON a.connection_id = c.id
      WHERE sc.access_token_id = sat.id
        AND a.manual = 0
    )
    OR EXISTS (
      SELECT 1
      FROM simplefin_connections sc
      JOIN connections c ON c.source_table = 'simplefin_connections' AND c.source_id = sc.id
      JOIN accounts a ON a.connection_id = c.id
      WHERE sc.access_token_id = sat.id
        AND a.manual = 0
        AND a.is_closed = 0
    )
  )
ORDER BY id
`

type SimpleFinTokenSecretsParams struct {
	Kind string
	Now  *time.Time
}

type SimpleFinTokenSecretsRow struct {
	ID                int64
	AccessUrl         string
	OwnerID           int64
	SyncCron          string
	LastSyncedAt      *time.Time
	NextSyncAt        *time.Time
	NextBalanceSyncAt *time.Time
}

// Used by SimpleFIN sync loops to select due token secrets. Balance work also
// excludes tokens whose linked accounts exist and are all closed: the shared
// snapshot sink rejects closed-account writes, so fetching from the provider
// would discard every result. A token with no linked accounts yet (before
// the first transaction sync creates them) stays due. Transaction sync keeps
// syncing a token's open accounts regardless of a sibling closed one, so
// this filter applies only to the balance kind.
func (q *Queries) SimpleFinTokenSecrets(ctx context.Context, arg SimpleFinTokenSecretsParams) ([]SimpleFinTokenSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, simpleFinTokenSecrets, arg.Kind, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SimpleFinTokenSecretsRow{}
	for rows.Next() {
		var i SimpleFinTokenSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccessUrl,
			&i.OwnerID,
			&i.SyncCron,
			&i.LastSyncedAt,
			&i.NextSyncAt,
			&i.NextBalanceSyncAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSimpleFinConnection = `-- name: UpsertSimpleFinConnection :one

INSERT INTO simplefin_connections (external_id, access_token_id, org_id, org_domain, org_url, sfin_url, logo_url)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT(external_id) DO UPDATE SET
    access_token_id = excluded.access_token_id,
    org_id          = excluded.org_id,
    org_domain      = excluded.org_domain,
    org_url         = excluded.org_url,
    sfin_url        = excluded.sfin_url,
    logo_url        = excluded.logo_url,
    updated_at      = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertSimpleFinConnectionParams struct {
	ExternalID    string
	AccessTokenID int64
	OrgID         *string
	OrgDomain     *string
	OrgUrl        *string
	SfinUrl       *string
	LogoUrl       *string
}

// ============================================================
// simplefin_connections
// ============================================================
// Used by internal/transactions' and internal/wealth's SimpleFIN sync loops to discover and upsert connections (orgs) reported by the SimpleFIN API.
func (q *Queries) UpsertSimpleFinConnection(ctx context.Context, arg UpsertSimpleFinConnectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertSimpleFinConnection,
		arg.ExternalID,
		arg.AccessTokenID,
		arg.OrgID,
		arg.OrgDomain,
		arg.OrgUrl,
		arg.SfinUrl,
		arg.LogoUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
