// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spending.sql

package dbgen

import (
	"context"
	"time"

	"tallyo/internal/money"
)

const spendingTransactions = `-- name: SpendingTransactions :many
SELECT t.amount_cents, t.datetime, cr.cat_id, cr.cat_name, cr.cat_emoji, cr.group_name, cr.group_emoji, cr.group_kind, cr.sort_order, cr.group_id, cr.group_sort_order, cr.plaid_pfc2_codes
FROM transactions t
JOIN category_rows cr ON cr.cat_id = t.category_id
JOIN accounts a ON a.id = t.account_id -- :if $6
WHERE TRUE
  AND t.datetime >= ?1
  AND t.datetime <  ?2
  AND t.staged_for_llm = 0
  AND t.is_hidden = ?3
  AND cr.group_kind != 'TRANSFER'
  AND cr.group_kind != 'INCOME' -- :if $8
  AND t.category_id IN (/*SLICE:category_ids*/?4) -- :if $4
  AND t.id IN (SELECT transaction_id FROM transaction_tags WHERE transaction_tags.tag_id IN (/*SLICE:tag_ids*/?5)) -- :if $5
  AND t.id NOT IN (SELECT transaction_id FROM transaction_tags) -- :if $9
  AND a.owner_id IN (/*SLICE:owner_ids*/?6) -- :if $6
  AND t.account_id IN (/*SLICE:account_ids*/?7) -- :if $7
ORDER BY t.datetime ASC
`

var _spendingTransactionsDynQ = dynCompile(spendingTransactions)

type SpendingTransactionsParams struct {
	DatetimeFrom  time.Time
	DatetimeTo    time.Time
	IsHidden      bool
	CategoryIds   []int64
	TagIds        []int64
	OwnerIds      []int64
	AccountIds    []int64
	ExcludeIncome bool
	Untagged      bool
}

type SpendingTransactionsRow struct {
	AmountCents money.Cents
	Datetime    time.Time
	CategoryRow CategoryRow
}

// Used by transactions/db.Store spending reports (spendingByCategory / cashFlow).
func (q *Queries) SpendingTransactions(ctx context.Context, arg SpendingTransactionsParams) ([]SpendingTransactionsRow, error) {

	dynQuery, dynArgs := _spendingTransactionsDynQ.Build([]any{arg.DatetimeFrom, arg.DatetimeTo, arg.IsHidden, arg.CategoryIds, arg.TagIds, arg.OwnerIds, arg.AccountIds, arg.ExcludeIncome, arg.Untagged})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendingTransactionsRow{}
	for rows.Next() {
		var i SpendingTransactionsRow
		if err := rows.Scan(
			&i.AmountCents,
			&i.Datetime,
			&i.CategoryRow.CatID,
			&i.CategoryRow.CatName,
			&i.CategoryRow.CatEmoji,
			&i.CategoryRow.GroupName,
			&i.CategoryRow.GroupEmoji,
			&i.CategoryRow.GroupKind,
			&i.CategoryRow.SortOrder,
			&i.CategoryRow.GroupID,
			&i.CategoryRow.GroupSortOrder,
			&i.CategoryRow.PlaidPfc2Codes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
