// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package dbgen

import (
	"context"
	"time"

	"tallyo/internal/money"
)

const logSyncBatch = `-- name: LogSyncBatch :exec
INSERT INTO plaid_sync_log (item_id, api, added, modified, removed)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type LogSyncBatchParams struct {
	ItemID   int64
	Api      string
	Added    string
	Modified string
	Removed  string
}

// Used by internal/transactions/plaid's background sync loop to record per-batch added/modified/removed counts after each /transactions/sync call.
func (q *Queries) LogSyncBatch(ctx context.Context, arg LogSyncBatchParams) error {
	_, err := q.db.ExecContext(ctx, logSyncBatch,
		arg.ItemID,
		arg.Api,
		arg.Added,
		arg.Modified,
		arg.Removed,
	)
	return err
}

const syncedTransactionState = `-- name: SyncedTransactionState :one
SELECT is_reviewed, category_id
FROM transactions
WHERE external_id = ?1
  AND source = ?2
`

type SyncedTransactionStateParams struct {
	ExternalID string
	Source     string
}

type SyncedTransactionStateRow struct {
	IsReviewed bool
	CategoryID int64
}

// Used by internal/transactions/plaid's sync persister to check whether a transaction already exists and preserve its user-set review state/category before upserting.
func (q *Queries) SyncedTransactionState(ctx context.Context, arg SyncedTransactionStateParams) (SyncedTransactionStateRow, error) {
	row := q.db.QueryRowContext(ctx, syncedTransactionState, arg.ExternalID, arg.Source)
	var i SyncedTransactionStateRow
	err := row.Scan(&i.IsReviewed, &i.CategoryID)
	return i, err
}

const upsertSyncedTransaction = `-- name: UpsertSyncedTransaction :one
INSERT INTO transactions (
  external_id,
  account_id,
  amount_cents,
  datetime,
  posted_datetime,
  merchant_name,
  original_name,
  logo_url,
  category_id,
  is_reviewed,
  plaid_category,
  raw_provider_json,
  source,
  pending,
  is_recurring,
  is_hidden,
  staged_for_llm,
  pfc2_categorized
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17,
  ?18
)
ON CONFLICT(source, external_id) DO UPDATE SET
  account_id = excluded.account_id,
  amount_cents = excluded.amount_cents,
  datetime = excluded.datetime,
  posted_datetime = excluded.posted_datetime,
  merchant_name = excluded.merchant_name,
  original_name = excluded.original_name,
  logo_url = excluded.logo_url,
  category_id = CASE
    WHEN transactions.is_reviewed = 1 THEN transactions.category_id
    ELSE excluded.category_id
  END,
  is_reviewed = CASE
    WHEN transactions.is_reviewed = 1 THEN transactions.is_reviewed
    ELSE excluded.is_reviewed
  END,
  staged_for_llm = CASE
    WHEN transactions.is_reviewed = 1 THEN transactions.staged_for_llm
    ELSE excluded.staged_for_llm
  END,
  pfc2_categorized = CASE
    WHEN transactions.is_reviewed = 1 THEN transactions.pfc2_categorized
    ELSE excluded.pfc2_categorized
  END,
  plaid_category = excluded.plaid_category,
  raw_provider_json = excluded.raw_provider_json,
  pending = excluded.pending,
  updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
RETURNING id
`

type UpsertSyncedTransactionParams struct {
	ExternalID      string
	AccountID       int64
	AmountCents     money.Cents
	Datetime        time.Time
	PostedDatetime  time.Time
	MerchantName    *string
	OriginalName    *string
	LogoUrl         *string
	CategoryID      int64
	IsReviewed      bool
	PlaidCategory   *string
	RawProviderJson *string
	Source          string
	Pending         bool
	IsRecurring     bool
	IsHidden        bool
	StagedForLlm    bool
	Pfc2Categorized bool
}

// Used by internal/transactions/plaid's (and SimpleFIN's) background sync loop to upsert transactions returned by the provider, overwriting only provider-sourced fields when the transaction has already been reviewed.
func (q *Queries) UpsertSyncedTransaction(ctx context.Context, arg UpsertSyncedTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertSyncedTransaction,
		arg.ExternalID,
		arg.AccountID,
		arg.AmountCents,
		arg.Datetime,
		arg.PostedDatetime,
		arg.MerchantName,
		arg.OriginalName,
		arg.LogoUrl,
		arg.CategoryID,
		arg.IsReviewed,
		arg.PlaidCategory,
		arg.RawProviderJson,
		arg.Source,
		arg.Pending,
		arg.IsRecurring,
		arg.IsHidden,
		arg.StagedForLlm,
		arg.Pfc2Categorized,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
