// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbgen

import (
	"context"
	"strings"
)

const addTransactionTagsByTransactionIDs = `-- name: AddTransactionTagsByTransactionIDs :exec
INSERT OR IGNORE INTO transaction_tags (transaction_id, tag_id)
SELECT tx.id, tags.id
FROM transactions tx
JOIN tags ON tags.id IN (/*SLICE:tag_ids*/?)
WHERE tx.id IN (/*SLICE:transaction_ids*/?)
`

type AddTransactionTagsByTransactionIDsParams struct {
	TagIds         []int64
	TransactionIds []int64
}

// Used when applying a rule retroactively (createRule/updateRule with applyRetroactively=true) to add the rule's tags to every matching transaction in bulk.
func (q *Queries) AddTransactionTagsByTransactionIDs(ctx context.Context, arg AddTransactionTagsByTransactionIDsParams) error {
	query := addTransactionTagsByTransactionIDs
	var queryParams []interface{}
	if len(arg.TagIds) > 0 {
		for _, v := range arg.TagIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tag_ids*/?", strings.Repeat(",?", len(arg.TagIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tag_ids*/?", "NULL", 1)
	}
	if len(arg.TransactionIds) > 0 {
		for _, v := range arg.TransactionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", strings.Repeat(",?", len(arg.TransactionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, color) VALUES (?1, ?2) RETURNING color, created_at, id, name, transaction_count, updated_at
`

type CreateTagParams struct {
	Name  string
	Color string
}

// Used by GraphQL mutation createTag via transactions/db.Store.CreateTag.
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.Color,
		&i.CreatedAt,
		&i.ID,
		&i.Name,
		&i.TransactionCount,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = ?1
`

type DeleteTagParams struct {
	ID int64
}

// Used by GraphQL mutation deleteTag via transactions/db.Store.DeleteTag.
func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTag, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTransactionTagsByTransactionIDs = `-- name: DeleteTransactionTagsByTransactionIDs :exec
DELETE FROM transaction_tags WHERE transaction_id IN (/*SLICE:transaction_ids*/?)
`

type DeleteTransactionTagsByTransactionIDsParams struct {
	TransactionIds []int64
}

// Used by transaction update mutations to clear existing tags before re-applying the updated set.
func (q *Queries) DeleteTransactionTagsByTransactionIDs(ctx context.Context, arg DeleteTransactionTagsByTransactionIDsParams) error {
	query := deleteTransactionTagsByTransactionIDs
	var queryParams []interface{}
	if len(arg.TransactionIds) > 0 {
		for _, v := range arg.TransactionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", strings.Repeat(",?", len(arg.TransactionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const listTags = `-- name: ListTags :many
SELECT t.color, t.created_at, t.id, t.name, t.transaction_count, t.updated_at
FROM tags t
WHERE TRUE
  AND t.id = ?1 -- :if $1
ORDER BY t.name, t.id
`

var _listTagsDynQ = dynCompile(listTags)

type ListTagsParams struct {
	ID *int64
}

// Used by GraphQL tag list and node lookup paths with an optional ID filter.
func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {

	dynQuery, dynArgs := _listTagsDynQ.Build([]any{arg.ID})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.Color,
			&i.CreatedAt,
			&i.ID,
			&i.Name,
			&i.TransactionCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagsByTransactionIDs = `-- name: TagsByTransactionIDs :many
SELECT tt.transaction_id, t.color, t.created_at, t.id, t.name, t.transaction_count, t.updated_at
FROM transaction_tags tt
JOIN tags t ON t.id = tt.tag_id
WHERE tt.transaction_id IN (/*SLICE:transaction_ids*/?)
ORDER BY tt.transaction_id, t.name, t.id
`

type TagsByTransactionIDsParams struct {
	TransactionIds []int64
}

type TagsByTransactionIDsRow struct {
	TransactionID int64
	Tag           Tag
}

// Used by the Transaction.tags dataloader (internal/graph/loaders.go) to batch-load tags for a list of transactions.
func (q *Queries) TagsByTransactionIDs(ctx context.Context, arg TagsByTransactionIDsParams) ([]TagsByTransactionIDsRow, error) {
	query := tagsByTransactionIDs
	var queryParams []interface{}
	if len(arg.TransactionIds) > 0 {
		for _, v := range arg.TransactionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", strings.Repeat(",?", len(arg.TransactionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:transaction_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagsByTransactionIDsRow{}
	for rows.Next() {
		var i TagsByTransactionIDsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.Tag.Color,
			&i.Tag.CreatedAt,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.TransactionCount,
			&i.Tag.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = ?1,
    color = ?2,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id = ?3
RETURNING color, created_at, id, name, transaction_count, updated_at
`

type UpdateTagParams struct {
	Name  string
	Color string
	ID    int64
}

// Used by GraphQL mutation updateTag via transactions/db.Store.UpdateTag.
func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i Tag
	err := row.Scan(
		&i.Color,
		&i.CreatedAt,
		&i.ID,
		&i.Name,
		&i.TransactionCount,
		&i.UpdatedAt,
	)
	return i, err
}
