// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package dbgen

import (
	"context"
	"strings"
	"time"

	"tallyo/internal/money"
)

const countTransactionRecords = `-- name: CountTransactionRecords :one
SELECT COUNT(t.id) AS total_count
FROM transactions t
JOIN accounts a ON a.id = t.account_id -- :if $8
JOIN category_rows cr ON cr.cat_id = t.category_id -- :if $18
WHERE TRUE
  AND t.staged_for_llm = 0
  AND t.id IN (/*SLICE:ids*/?1) -- :if $1
  AND t.id IN (SELECT rowid FROM transactions_fts WHERE transactions_fts MATCH ?2) -- :if $2
  AND t.datetime >= ?3 -- :if $3
  AND t.datetime <  ?4 -- :if $4
  AND t.category_id IN (/*SLICE:category_ids*/?5) -- :if $5
  AND t.id IN (SELECT transaction_id FROM transaction_tags WHERE transaction_tags.tag_id IN (/*SLICE:tag_ids*/?6)) -- :if $6
  AND t.id NOT IN (SELECT transaction_id FROM transaction_tags) -- :if $19
  AND t.account_id IN (/*SLICE:account_ids*/?7) -- :if $7
  AND a.owner_id IN (/*SLICE:owner_ids*/?8) -- :if $8
  AND t.is_reviewed = ?9 -- :if $9
  AND t.is_recurring = ?10 -- :if $10
  AND t.pending = ?11 -- :if $11
  AND t.is_hidden = ?12 -- :if $12
  AND instr(lower(coalesce(t.merchant_name, t.original_name, '')), ?13) > 0 -- :if $13
  AND instr(lower(coalesce(t.original_name, '')), ?14) > 0 -- :if $14
  AND t.amount_cents =  ?15 -- :if $15
  AND t.amount_cents >= ?16 -- :if $16
  AND t.amount_cents <= ?17 -- :if $17
  AND cr.group_kind NOT IN (/*SLICE:excluded_kinds*/?18) -- :if $18
  AND TRUE
`

var _countTransactionRecordsDynQ = dynCompile(countTransactionRecords)

type CountTransactionRecordsParams struct {
	Ids            []int64
	SearchMatch    *string
	DatetimeFrom   *time.Time
	DatetimeTo     *time.Time
	CategoryIds    []int64
	TagIds         []int64
	AccountIds     []int64
	OwnerIds       []int64
	IsReviewed     *bool
	IsRecurring    *bool
	IsPending      *bool
	IsHidden       *bool
	MerchantPrefix *string
	OriginalPrefix *string
	ExactAmount    *money.Cents
	AmountMin      *money.Cents
	AmountMax      *money.Cents
	ExcludedKinds  []string
	Untagged       bool
}

// Used by transactions/db.Store.Transactions for the total count of a filtered list.
func (q *Queries) CountTransactionRecords(ctx context.Context, arg CountTransactionRecordsParams) (int64, error) {

	dynQuery, dynArgs := _countTransactionRecordsDynQ.Build([]any{arg.Ids, arg.SearchMatch, arg.DatetimeFrom, arg.DatetimeTo, arg.CategoryIds, arg.TagIds, arg.AccountIds, arg.OwnerIds, arg.IsReviewed, arg.IsRecurring, arg.IsPending, arg.IsHidden, arg.MerchantPrefix, arg.OriginalPrefix, arg.ExactAmount, arg.AmountMin, arg.AmountMax, arg.ExcludedKinds, arg.Untagged})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
  source,
  external_id,
  account_id,
  amount_cents,
  datetime,
  posted_datetime,
  merchant_name,
  original_name,
  category_id,
  is_reviewed,
  is_recurring,
  is_hidden,
  pending,
  notes
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  0,
  ?13
)
ON CONFLICT(source, external_id) DO NOTHING
RETURNING id
`

type InsertTransactionParams struct {
	Source         string
	ExternalID     string
	AccountID      int64
	AmountCents    money.Cents
	Datetime       time.Time
	PostedDatetime time.Time
	MerchantName   *string
	OriginalName   *string
	CategoryID     int64
	IsReviewed     bool
	IsRecurring    bool
	IsHidden       bool
	Notes          *string
}

// Used by GraphQL mutation createTransaction to insert manually sourced
// transactions, and by the CSV import flow as the first (insert) half of its
// upsert. A (source, external_id) conflict does nothing and returns no row
// (sql.ErrNoRows): manual creation reads that as "retry with a new synthetic
// ID"; import reads it as "fall back to UpdateTransactionBySourceExternalID".
func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTransaction,
		arg.Source,
		arg.ExternalID,
		arg.AccountID,
		arg.AmountCents,
		arg.Datetime,
		arg.PostedDatetime,
		arg.MerchantName,
		arg.OriginalName,
		arg.CategoryID,
		arg.IsReviewed,
		arg.IsRecurring,
		arg.IsHidden,
		arg.Notes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const transactionIDsByFilter = `-- name: TransactionIDsByFilter :many
SELECT t.id
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN category_rows cr ON cr.cat_id = t.category_id
WHERE TRUE
  AND t.staged_for_llm = 0
  AND t.id IN (/*SLICE:ids*/?1) -- :if $1
  AND t.id IN (SELECT rowid FROM transactions_fts WHERE transactions_fts MATCH ?2) -- :if $2
  AND t.datetime >= ?3 -- :if $3
  AND t.datetime <  ?4 -- :if $4
  AND t.category_id IN (/*SLICE:category_ids*/?5) -- :if $5
  AND t.id IN (SELECT transaction_id FROM transaction_tags WHERE transaction_tags.tag_id IN (/*SLICE:tag_ids*/?6)) -- :if $6
  AND t.id NOT IN (SELECT transaction_id FROM transaction_tags) -- :if $18
  AND t.account_id IN (/*SLICE:account_ids*/?7) -- :if $7
  AND a.owner_id IN (/*SLICE:owner_ids*/?8) -- :if $8
  AND t.is_reviewed = ?9 -- :if $9
  AND t.is_recurring = ?10 -- :if $10
  AND t.pending = ?11 -- :if $11
  AND t.is_hidden = ?12 -- :if $12
  AND instr(lower(coalesce(t.merchant_name, t.original_name, '')), ?13) > 0 -- :if $13
  AND instr(lower(coalesce(t.original_name, '')), ?14) > 0 -- :if $14
  AND t.amount_cents =  ?15 -- :if $15
  AND t.amount_cents >= ?16 -- :if $16
  AND t.amount_cents <= ?17 -- :if $17
  AND cr.group_kind != 'TRANSFER' -- :if $19
  AND cr.group_kind != 'INCOME' -- :if $20
  AND TRUE
`

var _transactionIDsByFilterDynQ = dynCompile(transactionIDsByFilter)

type TransactionIDsByFilterParams struct {
	Ids              []int64
	SearchMatch      *string
	DatetimeFrom     *time.Time
	DatetimeTo       *time.Time
	CategoryIds      []int64
	TagIds           []int64
	AccountIds       []int64
	OwnerIds         []int64
	IsReviewed       *bool
	IsRecurring      *bool
	IsPending        *bool
	IsHidden         *bool
	MerchantPrefix   *string
	OriginalPrefix   *string
	ExactAmount      *money.Cents
	AmountMin        *money.Cents
	AmountMax        *money.Cents
	Untagged         bool
	ExcludeTransfers bool
	ExcludeIncome    bool
}

// Used by transactions/db.Store bulk update/delete to resolve target ids from a filter.
func (q *Queries) TransactionIDsByFilter(ctx context.Context, arg TransactionIDsByFilterParams) ([]int64, error) {

	dynQuery, dynArgs := _transactionIDsByFilterDynQ.Build([]any{arg.Ids, arg.SearchMatch, arg.DatetimeFrom, arg.DatetimeTo, arg.CategoryIds, arg.TagIds, arg.AccountIds, arg.OwnerIds, arg.IsReviewed, arg.IsRecurring, arg.IsPending, arg.IsHidden, arg.MerchantPrefix, arg.OriginalPrefix, arg.ExactAmount, arg.AmountMin, arg.AmountMax, arg.Untagged, arg.ExcludeTransfers, arg.ExcludeIncome})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionRecords = `-- name: TransactionRecords :many
SELECT
  t.id, t.source, t.external_id, t.amount_cents,
  t.datetime, t.posted_datetime, t.merchant_name, t.original_name, t.logo_url,
  t.plaid_category, t.is_recurring, t.is_reviewed, t.is_hidden, t.pending,
  t.notes, t.created_at, t.updated_at,
  a.connection_id, a.created_at, a.external_id, a.id, a.is_closed, a.is_hidden, a.manual, a.mask, a.name, a.needs_review, a.notes, a.owner_id, a.review_reason, a.subtype, a.type, a.updated_at,
  o.name AS owner_name,
  cr.cat_id, cr.cat_name, cr.cat_emoji, cr.group_name, cr.group_emoji, cr.group_kind, cr.sort_order, cr.group_id, cr.group_sort_order, cr.plaid_pfc2_codes
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN owners o ON o.id = a.owner_id
JOIN category_rows cr ON cr.cat_id = t.category_id
WHERE TRUE
  AND t.staged_for_llm = 0
  AND t.id IN (/*SLICE:ids*/?1) -- :if $1
  AND t.id IN (SELECT rowid FROM transactions_fts WHERE transactions_fts MATCH ?2) -- :if $2
  AND t.datetime >= ?3 -- :if $3
  AND t.datetime <  ?4 -- :if $4
  AND t.category_id IN (/*SLICE:category_ids*/?5) -- :if $5
  AND t.id IN (SELECT transaction_id FROM transaction_tags WHERE transaction_tags.tag_id IN (/*SLICE:tag_ids*/?6)) -- :if $6
  AND t.id NOT IN (SELECT transaction_id FROM transaction_tags) -- :if $22
  AND t.account_id IN (/*SLICE:account_ids*/?7) -- :if $7
  AND a.owner_id IN (/*SLICE:owner_ids*/?8) -- :if $8
  AND t.is_reviewed = ?9 -- :if $9
  AND t.is_recurring = ?10 -- :if $10
  AND t.pending = ?11 -- :if $11
  AND t.is_hidden = ?12 -- :if $12
  AND instr(lower(coalesce(t.merchant_name, t.original_name, '')), ?13) > 0 -- :if $13
  AND instr(lower(coalesce(t.original_name, '')), ?14) > 0 -- :if $14
  AND t.amount_cents =  ?15 -- :if $15
  AND t.amount_cents >= ?16 -- :if $16
  AND t.amount_cents <= ?17 -- :if $17
  AND cr.group_kind != 'TRANSFER' -- :if $23
  AND cr.group_kind != 'INCOME' -- :if $24
  AND (t.datetime > ?18 OR (t.datetime = ?18 AND t.id > ?19)) -- :if $25
  AND (t.datetime < ?18 OR (t.datetime = ?18 AND t.id < ?19)) -- :if $26
  AND (t.amount_cents > ?20 OR (t.amount_cents = ?20 AND t.id > ?19)) -- :if $27
  AND (t.amount_cents < ?20 OR (t.amount_cents = ?20 AND t.id < ?19)) -- :if $28
ORDER BY
  t.amount_cents ASC, -- :if $29
  t.amount_cents DESC, -- :if $30
  t.datetime ASC, -- :if $31
  t.datetime DESC, -- :if $32
  t.id ASC, -- :if $33
  t.id DESC, -- :if $34
  -- Trailing unconditional tiebreaker: t.id is unique, so this never actually
  -- breaks a tie -- it exists only so the ORDER BY always has at least one
  -- unconditional column. Without it, whichever ` + "`" + `:if` + "`" + ` line ends up last
  -- (varies by which toggle is set) sits right before the always-present
  -- LIMIT clause, and the dynamic-filter plugin's dangling-comma/orphaned-
  -- keyword cleanup only inspects the query's true trailing edge, so it never
  -- reaches an inactive last ORDER BY line or a comma left by an inactive one.
  t.id ASC
LIMIT ?21
`

var _transactionRecordsDynQ = dynCompile(transactionRecords)

type TransactionRecordsParams struct {
	Ids               []int64
	SearchMatch       *string
	DatetimeFrom      *time.Time
	DatetimeTo        *time.Time
	CategoryIds       []int64
	TagIds            []int64
	AccountIds        []int64
	OwnerIds          []int64
	IsReviewed        *bool
	IsRecurring       *bool
	IsPending         *bool
	IsHidden          *bool
	MerchantPrefix    *string
	OriginalPrefix    *string
	ExactAmount       *money.Cents
	AmountMin         *money.Cents
	AmountMax         *money.Cents
	CursorDatetime    time.Time
	CursorID          int64
	CursorAmount      money.Cents
	RowLimit          int64
	Untagged          bool
	ExcludeTransfers  bool
	ExcludeIncome     bool
	CursorDatetimeGt  bool
	CursorDatetimeLt  bool
	CursorAmountGt    bool
	CursorAmountLt    bool
	OrderAmountAsc    bool
	OrderAmountDesc   bool
	OrderDatetimeAsc  bool
	OrderDatetimeDesc bool
	OrderIdAsc        bool
	OrderIdDesc       bool
}

type TransactionRecordsRow struct {
	ID             int64
	Source         string
	ExternalID     string
	AmountCents    money.Cents
	Datetime       time.Time
	PostedDatetime time.Time
	MerchantName   *string
	OriginalName   *string
	LogoUrl        *string
	PlaidCategory  *string
	IsRecurring    bool
	IsReviewed     bool
	IsHidden       bool
	Pending        bool
	Notes          *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Account        Account
	OwnerName      string
	CategoryRow    CategoryRow
}

// Used by GraphQL query transactions / MCP (transactions/db.Store.Transactions), the CSV
// export page (ExportTransactionPage), Transaction-by-id, and the node batch loader.
func (q *Queries) TransactionRecords(ctx context.Context, arg TransactionRecordsParams) ([]TransactionRecordsRow, error) {

	dynQuery, dynArgs := _transactionRecordsDynQ.Build([]any{arg.Ids, arg.SearchMatch, arg.DatetimeFrom, arg.DatetimeTo, arg.CategoryIds, arg.TagIds, arg.AccountIds, arg.OwnerIds, arg.IsReviewed, arg.IsRecurring, arg.IsPending, arg.IsHidden, arg.MerchantPrefix, arg.OriginalPrefix, arg.ExactAmount, arg.AmountMin, arg.AmountMax, arg.CursorDatetime, arg.CursorID, arg.CursorAmount, arg.RowLimit, arg.Untagged, arg.ExcludeTransfers, arg.ExcludeIncome, arg.CursorDatetimeGt, arg.CursorDatetimeLt, arg.CursorAmountGt, arg.CursorAmountLt, arg.OrderAmountAsc, arg.OrderAmountDesc, arg.OrderDatetimeAsc, arg.OrderDatetimeDesc, arg.OrderIdAsc, arg.OrderIdDesc})
	rows, err := q.db.QueryContext(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionRecordsRow{}
	for rows.Next() {
		var i TransactionRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.AmountCents,
			&i.Datetime,
			&i.PostedDatetime,
			&i.MerchantName,
			&i.OriginalName,
			&i.LogoUrl,
			&i.PlaidCategory,
			&i.IsRecurring,
			&i.IsReviewed,
			&i.IsHidden,
			&i.Pending,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Account.ConnectionID,
			&i.Account.CreatedAt,
			&i.Account.ExternalID,
			&i.Account.ID,
			&i.Account.IsClosed,
			&i.Account.IsHidden,
			&i.Account.Manual,
			&i.Account.Mask,
			&i.Account.Name,
			&i.Account.NeedsReview,
			&i.Account.Notes,
			&i.Account.OwnerID,
			&i.Account.ReviewReason,
			&i.Account.Subtype,
			&i.Account.Type,
			&i.Account.UpdatedAt,
			&i.OwnerName,
			&i.CategoryRow.CatID,
			&i.CategoryRow.CatName,
			&i.CategoryRow.CatEmoji,
			&i.CategoryRow.GroupName,
			&i.CategoryRow.GroupEmoji,
			&i.CategoryRow.GroupKind,
			&i.CategoryRow.SortOrder,
			&i.CategoryRow.GroupID,
			&i.CategoryRow.GroupSortOrder,
			&i.CategoryRow.PlaidPfc2Codes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionRecordsSummary = `-- name: TransactionRecordsSummary :one
SELECT
  COUNT(t.id) AS total_count,
  CAST(COALESCE(SUM(t.amount_cents), 0) AS INTEGER) AS total_amount_cents,
  AVG(t.amount_cents) AS average_amount,
  CAST(COALESCE(MAX(t.amount_cents), 0) AS INTEGER) AS largest_amount_cents,
  CAST(COALESCE(MIN(substr(t.datetime, 1, 10)), '') AS TEXT) AS first_date,
  CAST(COALESCE(MAX(substr(t.datetime, 1, 10)), '') AS TEXT) AS last_date
FROM transactions t
JOIN accounts a ON a.id = t.account_id -- :if $8
JOIN category_rows cr ON cr.cat_id = t.category_id -- :if $18
WHERE TRUE
  AND t.id IN (/*SLICE:ids*/?1) -- :if $1
  AND t.id IN (SELECT rowid FROM transactions_fts WHERE transactions_fts MATCH ?2) -- :if $2
  AND t.datetime >= ?3 -- :if $3
  AND t.datetime <  ?4 -- :if $4
  AND t.category_id IN (/*SLICE:category_ids*/?5) -- :if $5
  AND t.id IN (SELECT transaction_id FROM transaction_tags WHERE transaction_tags.tag_id IN (/*SLICE:tag_ids*/?6)) -- :if $6
  AND t.id NOT IN (SELECT transaction_id FROM transaction_tags) -- :if $19
  AND t.account_id IN (/*SLICE:account_ids*/?7) -- :if $7
  AND a.owner_id IN (/*SLICE:owner_ids*/?8) -- :if $8
  AND t.is_reviewed = ?9 -- :if $9
  AND t.is_recurring = ?10 -- :if $10
  AND t.pending = ?11 -- :if $11
  AND t.is_hidden = ?12 -- :if $12
  AND instr(lower(coalesce(t.merchant_name, t.original_name, '')), ?13) > 0 -- :if $13
  AND instr(lower(coalesce(t.original_name, '')), ?14) > 0 -- :if $14
  AND t.amount_cents =  ?15 -- :if $15
  AND t.amount_cents >= ?16 -- :if $16
  AND t.amount_cents <= ?17 -- :if $17
  AND cr.group_kind NOT IN (/*SLICE:excluded_kinds*/?18) -- :if $18
  AND t.staged_for_llm = 0
`

var _transactionRecordsSummaryDynQ = dynCompile(transactionRecordsSummary)

type TransactionRecordsSummaryParams struct {
	Ids            []int64
	SearchMatch    *string
	DatetimeFrom   *time.Time
	DatetimeTo     *time.Time
	CategoryIds    []int64
	TagIds         []int64
	AccountIds     []int64
	OwnerIds       []int64
	IsReviewed     *bool
	IsRecurring    *bool
	IsPending      *bool
	IsHidden       *bool
	MerchantPrefix *string
	OriginalPrefix *string
	ExactAmount    *money.Cents
	AmountMin      *money.Cents
	AmountMax      *money.Cents
	ExcludedKinds  []string
	Untagged       bool
}

type TransactionRecordsSummaryRow struct {
	TotalCount         int64
	TotalAmountCents   int64
	AverageAmount      *float64
	LargestAmountCents int64
	FirstDate          string
	LastDate           string
}

// Used by GraphQL query transactionsSummary (transactions/db.Store.TransactionsSummary).
func (q *Queries) TransactionRecordsSummary(ctx context.Context, arg TransactionRecordsSummaryParams) (TransactionRecordsSummaryRow, error) {

	dynQuery, dynArgs := _transactionRecordsSummaryDynQ.Build([]any{arg.Ids, arg.SearchMatch, arg.DatetimeFrom, arg.DatetimeTo, arg.CategoryIds, arg.TagIds, arg.AccountIds, arg.OwnerIds, arg.IsReviewed, arg.IsRecurring, arg.IsPending, arg.IsHidden, arg.MerchantPrefix, arg.OriginalPrefix, arg.ExactAmount, arg.AmountMin, arg.AmountMax, arg.ExcludedKinds, arg.Untagged})
	row := q.db.QueryRowContext(ctx, dynQuery, dynArgs...)
	var i TransactionRecordsSummaryRow
	err := row.Scan(
		&i.TotalCount,
		&i.TotalAmountCents,
		&i.AverageAmount,
		&i.LargestAmountCents,
		&i.FirstDate,
		&i.LastDate,
	)
	return i, err
}

const updateTransactionBySourceExternalID = `-- name: UpdateTransactionBySourceExternalID :one
UPDATE transactions
SET account_id = ?1,
    amount_cents = ?2,
    datetime = ?3,
    posted_datetime = ?4,
    merchant_name = ?5,
    original_name = ?6,
    category_id = ?7,
    is_reviewed = ?8,
    is_recurring = ?9,
    is_hidden = ?10,
    notes = ?11,
    staged_for_llm = 0,
    pfc2_categorized = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE source = ?12 AND external_id = ?13
RETURNING id
`

type UpdateTransactionBySourceExternalIDParams struct {
	AccountID      int64
	AmountCents    money.Cents
	Datetime       time.Time
	PostedDatetime time.Time
	MerchantName   *string
	OriginalName   *string
	CategoryID     int64
	IsReviewed     bool
	IsRecurring    bool
	IsHidden       bool
	Notes          *string
	Source         string
	ExternalID     string
}

// Used by the CSV import flow when InsertTransaction found an existing row
// for (source, external_id); mirrors the fields InsertTransaction sets on a
// fresh insert.
func (q *Queries) UpdateTransactionBySourceExternalID(ctx context.Context, arg UpdateTransactionBySourceExternalIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionBySourceExternalID,
		arg.AccountID,
		arg.AmountCents,
		arg.Datetime,
		arg.PostedDatetime,
		arg.MerchantName,
		arg.OriginalName,
		arg.CategoryID,
		arg.IsReviewed,
		arg.IsRecurring,
		arg.IsHidden,
		arg.Notes,
		arg.Source,
		arg.ExternalID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateTransactionFieldsByIDs = `-- name: UpdateTransactionFieldsByIDs :execrows
UPDATE transactions
SET merchant_name = CASE WHEN CAST(?1 AS BOOLEAN) = 1 THEN ?2 ELSE merchant_name END,
    notes = CASE WHEN CAST(?3 AS BOOLEAN) = 1 THEN ?4 ELSE notes END,
    is_recurring = CASE WHEN CAST(?5 AS BOOLEAN) = 1 THEN ?6 ELSE is_recurring END,
    is_hidden = CASE WHEN CAST(?7 AS BOOLEAN) = 1 THEN ?8 ELSE is_hidden END,
    category_id = CASE WHEN CAST(?9 AS BOOLEAN) = 1 THEN ?10 ELSE category_id END,
    is_reviewed = CASE WHEN CAST(?9 AS BOOLEAN) = 1 THEN 1 ELSE is_reviewed END,
    staged_for_llm = CASE WHEN CAST(?9 AS BOOLEAN) = 1 THEN 0 ELSE staged_for_llm END,
    pfc2_categorized = CASE WHEN CAST(?9 AS BOOLEAN) = 1 THEN 0 ELSE pfc2_categorized END,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ','now')
WHERE id IN (/*SLICE:ids*/?)
`

type UpdateTransactionFieldsByIDsParams struct {
	SetMerchantName bool
	MerchantName    *string
	SetNotes        bool
	Notes           *string
	SetRecurring    bool
	IsRecurring     bool
	SetHidden       bool
	IsHidden        bool
	SetCategory     bool
	CategoryID      int64
	Ids             []int64
}

// Used by GraphQL mutation updateTransaction and bulkUpdateTransactions via transactions/db.Store.
func (q *Queries) UpdateTransactionFieldsByIDs(ctx context.Context, arg UpdateTransactionFieldsByIDsParams) (int64, error) {
	query := updateTransactionFieldsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SetMerchantName)
	queryParams = append(queryParams, arg.MerchantName)
	queryParams = append(queryParams, arg.SetNotes)
	queryParams = append(queryParams, arg.Notes)
	queryParams = append(queryParams, arg.SetRecurring)
	queryParams = append(queryParams, arg.IsRecurring)
	queryParams = append(queryParams, arg.SetHidden)
	queryParams = append(queryParams, arg.IsHidden)
	queryParams = append(queryParams, arg.SetCategory)
	queryParams = append(queryParams, arg.CategoryID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
