// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction_delete.sql

package dbgen

import (
	"context"
	"strings"
)

const deleteSyncedTransaction = `-- name: DeleteSyncedTransaction :execrows
DELETE FROM transactions
WHERE source = ?1
  AND external_id = ?2
`

type DeleteSyncedTransactionParams struct {
	Source     string
	ExternalID string
}

// Used by internal/transactions/plaid's sync persister to remove a transaction when the provider reports it as removed.
func (q *Queries) DeleteSyncedTransaction(ctx context.Context, arg DeleteSyncedTransactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSyncedTransaction, arg.Source, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTransactionsByIDs = `-- name: DeleteTransactionsByIDs :execrows
DELETE FROM transactions
WHERE id IN (/*SLICE:ids*/?)
`

type DeleteTransactionsByIDsParams struct {
	Ids []int64
}

// Used by GraphQL mutation bulkDeleteTransactions via transactions/db.Store.BulkDeleteTransactions.
func (q *Queries) DeleteTransactionsByIDs(ctx context.Context, arg DeleteTransactionsByIDsParams) (int64, error) {
	query := deleteTransactionsByIDs
	var queryParams []interface{}
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
