// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn.sql

package dbgen

import (
	"context"
	"time"
)

const adminPasskeyExists = `-- name: AdminPasskeyExists :one
SELECT EXISTS(
  SELECT 1
  FROM webauthn_credentials wc
  JOIN users u ON u.id = wc.user_id
   WHERE u.role = 'admin'
)
`

// Used by internal/admin's setup-wizard configuration flow to check whether any admin has already registered a passkey.
func (q *Queries) AdminPasskeyExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, adminPasskeyExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createWebAuthnCredential = `-- name: CreateWebAuthnCredential :exec
INSERT INTO webauthn_credentials (id, user_id, name, credential)
VALUES (?1, ?2, ?3, ?4)
`

type CreateWebAuthnCredentialParams struct {
	ID         string
	UserID     int64
	Name       string
	Credential string
}

// Used by internal/auth's WebAuthn registration-finish handler to persist a new passkey after a successful attestation ceremony.
func (q *Queries) CreateWebAuthnCredential(ctx context.Context, arg CreateWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createWebAuthnCredential,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Credential,
	)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :execrows
DELETE FROM webauthn_credentials
WHERE id = ?1
  AND user_id = ?2
`

type DeleteWebAuthnCredentialParams struct {
	ID     string
	UserID int64
}

// Used by internal/auth's passkey-delete REST handler (DELETE) to remove a saved credential, scoped to its owning user.
func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebAuthnCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteWebAuthnRegistration = `-- name: DeleteWebAuthnRegistration :execrows
DELETE FROM webauthn_registrations
WHERE user_id = ?1
`

type DeleteWebAuthnRegistrationParams struct {
	UserID int64
}

// Used by internal/auth's WebAuthn registration-finish handler (and the background cleanup goroutine) to remove a ceremony session once it's consumed or expired.
func (q *Queries) DeleteWebAuthnRegistration(ctx context.Context, arg DeleteWebAuthnRegistrationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWebAuthnRegistration, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const renameWebAuthnCredential = `-- name: RenameWebAuthnCredential :execrows
UPDATE webauthn_credentials
SET name = ?1
WHERE id = ?2
  AND user_id = ?3
`

type RenameWebAuthnCredentialParams struct {
	Name   string
	ID     string
	UserID int64
}

// Used by internal/auth's passkey-rename REST handler (PATCH) to rename a saved credential, scoped to its owning user.
func (q *Queries) RenameWebAuthnCredential(ctx context.Context, arg RenameWebAuthnCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameWebAuthnCredential, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveWebAuthnRegistration = `-- name: SaveWebAuthnRegistration :exec
INSERT INTO webauthn_registrations (user_id, name, session, expires_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(user_id) DO UPDATE SET
  name = excluded.name,
  session = excluded.session,
  expires_at = excluded.expires_at
`

type SaveWebAuthnRegistrationParams struct {
	UserID    int64
	Name      string
	Session   string
	ExpiresAt time.Time
}

// Used by internal/auth's WebAuthn registration-begin handler to persist the attestation challenge/session for the ceremony.
func (q *Queries) SaveWebAuthnRegistration(ctx context.Context, arg SaveWebAuthnRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, saveWebAuthnRegistration,
		arg.UserID,
		arg.Name,
		arg.Session,
		arg.ExpiresAt,
	)
	return err
}

const updateWebAuthnCredential = `-- name: UpdateWebAuthnCredential :exec
UPDATE webauthn_credentials
SET credential = ?1,
    last_used_at = ?2
WHERE id = ?3
`

type UpdateWebAuthnCredentialParams struct {
	Credential string
	LastUsedAt *time.Time
	ID         string
}

// Used by internal/auth's WebAuthn login-finish handler to update the credential's sign counter and last-used timestamp after a successful assertion.
func (q *Queries) UpdateWebAuthnCredential(ctx context.Context, arg UpdateWebAuthnCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateWebAuthnCredential, arg.Credential, arg.LastUsedAt, arg.ID)
	return err
}

const webAuthnCredentialsByUserID = `-- name: WebAuthnCredentialsByUserID :many
SELECT
  id,
  user_id,
  name,
  credential,
  created_at,
  last_used_at
FROM webauthn_credentials
WHERE user_id = ?1
ORDER BY created_at DESC
`

type WebAuthnCredentialsByUserIDParams struct {
	UserID int64
}

type WebAuthnCredentialsByUserIDRow struct {
	ID         string
	UserID     int64
	Name       string
	Credential string
	CreatedAt  time.Time
	LastUsedAt *time.Time
}

// Used by internal/auth's WebAuthn login-begin handler and credentials-list handler to load a user's saved passkeys.
func (q *Queries) WebAuthnCredentialsByUserID(ctx context.Context, arg WebAuthnCredentialsByUserIDParams) ([]WebAuthnCredentialsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, webAuthnCredentialsByUserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebAuthnCredentialsByUserIDRow{}
	for rows.Next() {
		var i WebAuthnCredentialsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Credential,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const webAuthnRegistration = `-- name: WebAuthnRegistration :one
SELECT user_id, name, session, expires_at
FROM webauthn_registrations
WHERE user_id = ?1
`

type WebAuthnRegistrationParams struct {
	UserID int64
}

type WebAuthnRegistrationRow struct {
	UserID    int64
	Name      string
	Session   string
	ExpiresAt time.Time
}

// Used by internal/auth's WebAuthn registration-finish handler to retrieve the pending ceremony session for attestation verification.
func (q *Queries) WebAuthnRegistration(ctx context.Context, arg WebAuthnRegistrationParams) (WebAuthnRegistrationRow, error) {
	row := q.db.QueryRowContext(ctx, webAuthnRegistration, arg.UserID)
	var i WebAuthnRegistrationRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Session,
		&i.ExpiresAt,
	)
	return i, err
}
