use std::collections::HashSet;

use anyhow::{Context, Result};
use sqlx::{Row, SqlitePool};

use super::open_database;

const EXPECTED_SCHEMA: &str = include_str!("schema_snapshot.sql");

struct SchemaObject {
    object_type: String,
    name: String,
    table_name: String,
    sql: String,
}

#[tokio::test]
async fn schema_matches_snapshot() -> Result<()> {
    let pool = open_database(":memory:", None).await?;
    let snapshot = dump_schema(&pool).await?;
    let difference = first_difference(&snapshot, EXPECTED_SCHEMA);
    anyhow::ensure!(
        snapshot == EXPECTED_SCHEMA,
        "schema snapshot differs at byte {difference}: actual {:?}, expected {:?}",
        &snapshot[difference..snapshot.len().min(difference + 100)],
        &EXPECTED_SCHEMA[difference..EXPECTED_SCHEMA.len().min(difference + 100)]
    );
    Ok(())
}

fn first_difference(actual: &str, expected: &str) -> usize {
    actual
        .bytes()
        .zip(expected.bytes())
        .position(|(actual, expected)| actual != expected)
        .unwrap_or(actual.len().min(expected.len()))
}

async fn dump_schema(pool: &SqlitePool) -> Result<String> {
    let objects = sqlx::query(
        r"SELECT type AS object_type, name, tbl_name AS table_name, sql
FROM sqlite_master
WHERE type IN ('table', 'index', 'trigger', 'view')
  AND name NOT LIKE 'sqlite_%'
  AND name NOT IN ('goose_db_version', '_sqlx_migrations')
  AND sql IS NOT NULL",
    )
    .fetch_all(pool)
    .await
    .context("list schema objects")?
    .into_iter()
    .map(|row| {
        Ok(SchemaObject {
            object_type: row.try_get("object_type")?,
            name: row.try_get("name")?,
            table_name: row.try_get("table_name")?,
            sql: row.try_get("sql")?,
        })
    })
    .collect::<Result<Vec<_>, sqlx::Error>>()
    .context("decode schema objects")?;
    let virtual_tables = objects
        .iter()
        .filter(|object| {
            object.object_type == "table"
                && object
                    .sql
                    .trim_start()
                    .to_ascii_uppercase()
                    .starts_with("CREATE VIRTUAL TABLE")
        })
        .map(|object| object.name.clone())
        .collect::<HashSet<_>>();
    let mut objects = objects
        .into_iter()
        .filter(|object| {
            object.object_type != "table"
                || !virtual_tables
                    .iter()
                    .any(|table| object.name.starts_with(&format!("{table}_")))
        })
        .collect::<Vec<_>>();
    objects.sort_by(|left, right| left.name.cmp(&right.name));

    let mut snapshot = String::from("-- Schema snapshot for tallyo\n-- Generated by Rust database migration test.\n\n");
    for table in objects.iter().filter(|object| object.object_type == "table") {
        append_schema_object(&mut snapshot, table);
        for index in objects
            .iter()
            .filter(|object| object.object_type == "index" && object.table_name == table.name)
        {
            append_schema_object(&mut snapshot, index);
        }
    }
    for object in objects.iter().filter(|object| object.object_type == "view") {
        append_schema_object(&mut snapshot, object);
    }
    for object in objects.iter().filter(|object| object.object_type == "trigger") {
        append_schema_object(&mut snapshot, object);
    }
    snapshot.truncate(snapshot.len() - 1);
    Ok(snapshot)
}

fn append_schema_object(snapshot: &mut String, object: &SchemaObject) {
    snapshot.push_str(&object.sql);
    snapshot.push_str(";\n\n");
}
